# OpenROAD P&R - Generated by OpenForge EDA
read_lef /mnt/h/openforge/share/pdk/sky130/lef/sky130hd.tlef
read_lef /mnt/h/openforge/share/pdk/sky130/lef/sky130_fd_sc_hd_merged.lef
read_liberty /mnt/h/openforge/share/pdk/sky130/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog /mnt/h/openforge/examples/simple-counter/synth_build/netlist.v
link_design counter

# Read constraints
read_sdc /mnt/h/openforge/examples/simple-counter/constraints/timing.sdc

# Floorplan
initialize_floorplan -utilization 50 -aspect_ratio 1 -core_space 2 -site unithd
make_tracks

# Place pins
place_pins -hor_layers met1 -ver_layers met2

# Global placement
global_placement -density 0.6

# Detailed placement
detailed_placement
improve_placement

# Report results
report_design_area
report_checks -path_delay max

# Write outputs
write_def /mnt/h/openforge/examples/simple-counter/pnr_build/counter_placed.def
write_verilog /mnt/h/openforge/examples/simple-counter/pnr_build/counter_placed.v

puts ""
puts "=== OpenROAD P&R Complete ==="
puts "Design: counter"
puts "PDK: SKY130"
puts "DEF: pnr_build/counter_placed.def"

exit
