"""Automatic IO pad placement.

Distributes top-level signal ports around the die edges, grouping ports
by their interface prefix (``axi_``, ``uart_``, ``spi_``...) and clock
domain so related signals stay adjacent. Produces
:class:`~openforge.floorplan.model.IoPad` instances and the matching
OpenROAD ``place_pin`` commands.
"""

from __future__ import annotations

import re

from pydantic import BaseModel

from openforge.floorplan.model import Die, IoPad, Side, SignalDir


class Port(BaseModel):
    """A top-level RTL port."""

    name: str
    direction: SignalDir = "INOUT"
    width: int = 1
    clock_domain: str = ""


_PREFIX_RE = re.compile(r"^([a-zA-Z][a-zA-Z0-9]*?)(?:_|$)")


def _group_key(port: Port) -> str:
    """Return a grouping key for ``port``.

    Ports sharing a clock domain or a common ``foo_`` prefix are placed
    together. Fallback: the first token of the name.
    """
    if port.clock_domain:
        return f"clk::{port.clock_domain}"
    m = _PREFIX_RE.match(port.name)
    if m:
        return f"iface::{m.group(1).lower()}"
    return f"net::{port.name}"


def auto_place_pins(
    top_ports: list[Port],
    die: Die,
    layer: str = "met2",
    symmetric: bool = True,
) -> list[IoPad]:
    """Distribute ``top_ports`` around the die edges as :class:`IoPad`."""
    if not top_ports:
        return []

    # Group ports to keep related signals adjacent.
    groups: dict[str, list[Port]] = {}
    for p in top_ports:
        groups.setdefault(_group_key(p), []).append(p)

    ordered_groups = sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0]))

    # Allocate groups to sides round-robin.
    sides: list[Side] = ["W", "E", "N", "S"]
    side_buckets: dict[Side, list[Port]] = {s: [] for s in sides}

    if symmetric:
        # Put inputs on W/S and outputs on E/N for easier read.
        for _key, ports in ordered_groups:
            inputs = [p for p in ports if p.direction == "INPUT"]
            outputs = [p for p in ports if p.direction == "OUTPUT"]
            inouts = [p for p in ports if p.direction == "INOUT"]
            side_buckets["W"].extend(inputs[: len(inputs) // 2 + len(inputs) % 2])
            side_buckets["S"].extend(inputs[len(inputs) // 2 + len(inputs) % 2 :])
            side_buckets["E"].extend(outputs[: len(outputs) // 2 + len(outputs) % 2])
            side_buckets["N"].extend(outputs[len(outputs) // 2 + len(outputs) % 2 :])
            # IO splits across the remaining room.
            for i, p in enumerate(inouts):
                side_buckets[sides[i % 4]].append(p)
    else:
        flat: list[Port] = []
        for _, ports in ordered_groups:
            flat.extend(ports)
        for i, p in enumerate(flat):
            side_buckets[sides[i % 4]].append(p)

    pads: list[IoPad] = []
    for side, ports in side_buckets.items():
        if not ports:
            continue
        length = die.width_um if side in ("N", "S") else die.height_um
        margin = max(2.0, length * 0.05)
        usable = max(length - 2 * margin, 1.0)
        step = usable / (len(ports) + 1)
        for i, p in enumerate(ports, start=1):
            offset = margin + step * i
            pads.append(
                IoPad(
                    name=p.name,
                    side=side,
                    offset_um=offset,
                    signal_dir=p.direction,
                    layer=layer,
                )
            )
    return pads


def to_openroad_pin_constraints(pads: list[IoPad]) -> str:
    """Return an OpenROAD Tcl snippet pinning each pad to a die edge."""
    lines: list[str] = ["# IO pin constraints - generated by OpenForge"]
    for pad in pads:
        edge_map = {"N": "top", "S": "bottom", "E": "right", "W": "left"}
        lines.append(
            f"set_io_pin_constraint -region {edge_map[pad.side]}:"
            f"{pad.offset_um:g} -pin_names {{{pad.name}}}"
        )
    return "\n".join(lines) + "\n"
