"""Tests for the Magic <-> OpenForge interop adapter."""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from openforge.integrations.magic import (
    MagicTechFile,
    magic_to_drx,
    parse_magic_tech,
)

FIXTURE = Path(__file__).parent / "fixtures" / "magic_minimal" / "sky130A.tech"

# Resolve the openforge-drc binary built by the Rust workspace.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_DRC_BIN_CANDIDATES = [
    _REPO_ROOT / "target" / "release" / "openforge-drc.exe",
    _REPO_ROOT / "target" / "release" / "openforge-drc",
    _REPO_ROOT / "target" / "debug" / "openforge-drc.exe",
    _REPO_ROOT / "target" / "debug" / "openforge-drc",
]


def _drc_binary() -> Path | None:
    for c in _DRC_BIN_CANDIDATES:
        if c.is_file():
            return c
    found = shutil.which("openforge-drc")
    return Path(found) if found else None


def test_parse_magic_tech_extracts_rules() -> None:
    tech = parse_magic_tech(FIXTURE)
    assert isinstance(tech, MagicTechFile)
    assert tech.name == "sky130A"
    # 4 width rules in the fixture
    assert len(tech.width_rules) == 4
    layers = {r.layer for r in tech.width_rules}
    assert {"li1", "met1", "met2", "poly"}.issubset(layers)
    # First width rule values
    li_rule = next(r for r in tech.width_rules if r.layer == "li1")
    assert li_rule.distance == pytest.approx(0.17)
    assert "0.17" in li_rule.message


def test_parse_magic_tech_spacing_and_area() -> None:
    tech = parse_magic_tech(FIXTURE)
    assert len(tech.spacing_rules) == 4
    # Same-layer met1 spacing
    met1_sp = next(r for r in tech.spacing_rules if r.layer_a == "met1" and r.layer_b == "met1")
    assert met1_sp.distance == pytest.approx(0.14)
    # Inter-layer nwell-diff
    inter = next(r for r in tech.spacing_rules if {r.layer_a, r.layer_b} == {"nwell", "diff"})
    assert inter.distance == pytest.approx(0.34)
    # Area + unsupported
    assert len(tech.area_rules) == 1
    assert tech.area_rules[0].area == pytest.approx(0.083)
    # The fixture's `edge poly diff ...` is still unsupported (multi-arg edge),
    # but `surround`, `overhang`, and `edge4way` are now first-class.
    assert any(u.raw.startswith("edge ") for u in tech.unsupported)
    assert len(tech.surround_rules) == 1
    assert tech.surround_rules[0].outer == "nwell"
    assert tech.surround_rules[0].inner == "diff"
    assert tech.surround_rules[0].distance == pytest.approx(0.18)
    assert len(tech.overhang_rules) == 1
    assert tech.overhang_rules[0].distance == pytest.approx(0.06)
    assert len(tech.notch_rules) == 1
    assert tech.notch_rules[0].layer == "met1"
    assert tech.notch_rules[0].distance == pytest.approx(0.14)


def test_magic_to_drx_emits_expected_rules() -> None:
    tech = parse_magic_tech(FIXTURE)
    drx = magic_to_drx(tech)
    # Header + report
    assert drx.startswith("# Auto-generated by openforge")
    assert 'report("sky130A' in drx
    # Layer declarations should reference real sky130 GDS numbers.
    assert "li1 = input(67, 20)" in drx
    assert "met1 = input(68, 20)" in drx
    # Width + space DRX method calls
    assert "li1.width(0.17)" in drx
    assert "met1.space(0.14)" in drx
    # Inter-layer spacing -> .separation() primitive (v0.4+).
    assert "nwell.separation(diff, 0.34)" in drx
    # Area -> .area() primitive (v0.4+).
    assert "met1.area(0.083)" in drx
    # Surround -> .surround() primitive (v0.4+).
    assert "nwell.surround(diff, 0.18)" in drx
    # Overhang -> .overhang() primitive (v0.4+).
    assert "met1.overhang(licon, 0.06)" in drx
    # edge4way (notch) -> .notch() primitive (v0.4+).
    assert "met1.notch(0.14)" in drx
    # Truly-unsupported `edge` rule still preserved as a TODO comment.
    assert "edge poly diff" in drx


def test_magic_to_drx_no_longer_emits_todo_for_now_supported_constructs() -> None:
    """The constructs we just added DRX primitives for must NOT come out as TODOs."""
    tech = parse_magic_tech(FIXTURE)
    drx = magic_to_drx(tech)
    # No TODO should mention these now-supported phrases.
    forbidden = [
        "inter-layer spacing not supported",
        "DRX has no .area()",
        "TODO: met1.area(",
        "'surround' rule not yet translated",
        "'overhang' rule not yet translated",
        "'edge4way' rule not yet translated",
    ]
    for needle in forbidden:
        assert needle not in drx, f"unexpected TODO in DRX output: {needle!r}\n{drx}"

    # Sanity: each supported construct appears as an actual DRX call (not in
    # a comment line).
    drx_lines = [ln for ln in drx.splitlines() if not ln.lstrip().startswith("#")]
    drx_active = "\n".join(drx_lines)
    for needle in (
        ".separation(",
        ".area(",
        ".surround(",
        ".overhang(",
        ".notch(",
    ):
        assert needle in drx_active, f"{needle} should be emitted as a real DRX call"


def test_magic_to_drx_writes_temp_file_and_is_consumable_by_drc(
    tmp_path: Path,
) -> None:
    """The translated DRX should be parseable by openforge-drc.

    We don't have a GDS in the fixture, so we can't run a full check; but we
    can verify the binary at least accepts the rule deck without a parser
    error by feeding it a minimal empty GDS via a temp file. If the binary
    is missing (clean checkout, no `cargo build --release`), skip.
    """
    drc = _drc_binary()
    if drc is None or os.environ.get("OPENFORGE_SKIP_RUST", "") == "1":
        pytest.skip("openforge-drc binary not available")

    tech = parse_magic_tech(FIXTURE)
    drx = magic_to_drx(tech)
    drx_path = tmp_path / "sky130A.drx"
    drx_path.write_text(drx, encoding="utf-8")

    # Minimal empty GDSII: a 2-byte HEADER record won't parse; instead try
    # `--help` round-trip (parser is invoked lazily) and accept either:
    #   * non-zero exit with a "GDS" / "no such file" complaint (means the
    #     deck parsed and only the GDS arg failed), or
    #   * any successful exit.
    # We invoke with a non-existent GDS argument; the deck is still parsed
    # eagerly by the binary's CLI before GDS load.
    result = subprocess.run(
        [
            str(drc),
            "check",
            "--rules-drx",
            str(drx_path),
            str(tmp_path / "nonexistent.gds"),
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    combined = (result.stdout + result.stderr).lower()
    # The deck must parse cleanly; the only error we tolerate is the GDS
    # not being found (we deliberately pointed at a missing file).
    assert "parsing drx deck" in combined
    assert "gds parse error" in combined or "no such file" in combined or "cannot find" in combined
    # No DRX-syntax errors (the lexer / parser would say "expected ..." or
    # "unexpected ..." at a specific line).
    assert "drx parse" not in combined and "syntax error" not in combined


def test_magic_to_drx_handles_empty_rule_set() -> None:
    """An empty MagicTechFile should still produce a valid (header-only) deck."""
    empty = MagicTechFile(name="empty")
    drx = magic_to_drx(empty)
    assert "report(" in drx
    # No rule lines, no crash.
    assert "width(" not in drx
    assert "space(" not in drx
