"""Unified constraint model with SDC/XDC/LPF/PCF/CST serialization.

This module provides a tool-agnostic representation of FPGA/ASIC timing and
physical constraints. A ``ConstraintSet`` can be emitted as:

- SDC  -- Synopsys Design Constraints (OpenROAD, Yosys, Quartus, etc.)
- XDC  -- Xilinx Design Constraints (Vivado) -- SDC superset + ``set_property``
- LPF  -- Lattice Preference File (ECP5, project Trellis / nextpnr)
- PCF  -- Physical Constraints File (iCE40, project IceStorm / nextpnr)
- CST  -- Gowin Constraint file (GW1N / GW2A families)

And parsed back from the same. The model is intentionally loose (free-form
``attrs`` dict) so we can round-trip vendor-specific keys we don't model
explicitly.
"""

from __future__ import annotations

import re
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ConstraintKind(StrEnum):
    """Kind of constraint. Covers both timing (SDC) and physical (IO)."""

    CLOCK = "clock"
    GENERATED_CLOCK = "generated_clock"
    INPUT_DELAY = "input_delay"
    OUTPUT_DELAY = "output_delay"
    FALSE_PATH = "false_path"
    MULTICYCLE_PATH = "multicycle_path"
    MAX_DELAY = "max_delay"
    MIN_DELAY = "min_delay"
    SET_LOAD = "set_load"
    SET_DRIVE = "set_drive"
    GROUP_PATH = "group_path"
    CASE_ANALYSIS = "case_analysis"
    IO_STANDARD = "io_standard"
    PIN_LOCATION = "pin_location"
    DRIVE_STRENGTH = "drive_strength"
    SLEW_RATE = "slew_rate"
    PULL = "pull"


class Constraint(BaseModel):
    """A single constraint entry.

    ``target`` is a port / pin / net name (for physical constraints) or a
    collection reference like ``[get_ports clk]`` for SDC-style commands.
    ``value`` holds the primary numeric or string value (period, delay, pin).
    ``attrs`` holds extra key/value pairs (waveform, clock ref, from/to/through).
    """

    model_config = ConfigDict(extra="allow")

    kind: ConstraintKind
    name: str = ""
    target: str = ""
    value: Any = None
    units: str = ""
    attrs: dict[str, Any] = Field(default_factory=dict)


# ─────────────────────────────────────────────────────────────────────────────
# ConstraintSet
# ─────────────────────────────────────────────────────────────────────────────


class ConstraintSet(BaseModel):
    """A named collection of constraints with multi-format I/O."""

    model_config = ConfigDict(extra="allow")

    name: str = "default"
    constraints: list[Constraint] = Field(default_factory=list)

    # ── add helpers ─────────────────────────────────────────────────────────

    def add(self, c: Constraint) -> ConstraintSet:
        self.constraints.append(c)
        return self

    def extend(self, cs: list[Constraint]) -> ConstraintSet:
        self.constraints.extend(cs)
        return self

    def by_kind(self, kind: ConstraintKind) -> list[Constraint]:
        return [c for c in self.constraints if c.kind == kind]

    # ── SDC ─────────────────────────────────────────────────────────────────

    def to_sdc(self) -> str:
        """Emit Synopsys Design Constraints text."""
        lines: list[str] = [
            f"# OpenForge SDC -- {self.name}",
            "# Generated by openforge.constraints",
        ]
        for c in self.constraints:
            line = _sdc_line(c)
            if line:
                lines.append(line)
        return "\n".join(lines) + "\n"

    @classmethod
    def from_sdc(cls, text: str, name: str = "default") -> ConstraintSet:
        cs = cls(name=name)
        for raw in _iter_tcl_lines(text):
            c = _parse_sdc_line(raw)
            if c is not None:
                cs.constraints.append(c)
        return cs

    # ── XDC (Vivado) ────────────────────────────────────────────────────────

    def to_xdc(self) -> str:
        """Emit Xilinx XDC text. XDC is SDC + ``set_property`` for IO."""
        lines: list[str] = [
            f"# OpenForge XDC -- {self.name}",
            "# Vivado constraint file",
        ]
        for c in self.constraints:
            if c.kind in _SDC_KINDS:
                line = _sdc_line(c)
                if line:
                    lines.append(line)
            elif c.kind == ConstraintKind.PIN_LOCATION:
                # set_property PACKAGE_PIN H16 [get_ports clk]
                port = c.target or c.name
                lines.append(f"set_property PACKAGE_PIN {c.value} [get_ports {{{port}}}]")
            elif c.kind == ConstraintKind.IO_STANDARD:
                port = c.target or c.name
                lines.append(f"set_property IOSTANDARD {c.value} [get_ports {{{port}}}]")
            elif c.kind == ConstraintKind.DRIVE_STRENGTH:
                port = c.target or c.name
                lines.append(f"set_property DRIVE {c.value} [get_ports {{{port}}}]")
            elif c.kind == ConstraintKind.SLEW_RATE:
                port = c.target or c.name
                lines.append(f"set_property SLEW {c.value} [get_ports {{{port}}}]")
            elif c.kind == ConstraintKind.PULL:
                port = c.target or c.name
                # Vivado: PULLUP / PULLDOWN / PULLNONE / KEEPER -> via set_property
                v = str(c.value).upper()
                if v in ("UP", "PULLUP"):
                    prop = "PULLUP TRUE"
                elif v in ("DOWN", "PULLDOWN"):
                    prop = "PULLDOWN TRUE"
                elif v in ("KEEPER",):
                    prop = "KEEPER TRUE"
                else:
                    prop = "PULLUP FALSE"
                key, val = prop.split(" ", 1)
                lines.append(f"set_property {key} {val} [get_ports {{{port}}}]")
        return "\n".join(lines) + "\n"

    @classmethod
    def from_xdc(cls, text: str, name: str = "default") -> ConstraintSet:
        cs = cls(name=name)
        # set_property PROP VAL [get_ports {name}]
        set_prop_re = re.compile(
            r"^\s*set_property\s+(\S+)\s+(\S+)\s+\[\s*get_ports\s+\{?([^\]\}]+)\}?\s*\]",
            re.IGNORECASE,
        )
        for raw in _iter_tcl_lines(text):
            m = set_prop_re.match(raw)
            if m:
                prop, val, port = m.group(1), m.group(2), m.group(3).strip()
                kind = _XDC_PROP_TO_KIND.get(prop.upper())
                if kind is not None:
                    # Handle booleans for PULL
                    if kind == ConstraintKind.PULL:
                        if prop.upper() == "PULLUP" and val.upper() == "TRUE":
                            val = "UP"
                        elif prop.upper() == "PULLDOWN" and val.upper() == "TRUE":
                            val = "DOWN"
                        elif prop.upper() == "KEEPER" and val.upper() == "TRUE":
                            val = "KEEPER"
                        else:
                            continue
                    cs.constraints.append(Constraint(kind=kind, target=port, value=val))
                    continue
            # Fallback to SDC
            c = _parse_sdc_line(raw)
            if c is not None:
                cs.constraints.append(c)
        return cs

    # ── LPF (Lattice ECP5 / nextpnr-ecp5) ───────────────────────────────────

    def to_lpf(self) -> str:
        """Emit Lattice Preference File (LPF).

        Real LPF syntax as consumed by nextpnr-ecp5 / Diamond:
            LOCATE COMP "led" SITE "E16";
            IOBUF PORT "led" IO_TYPE=LVCMOS33 DRIVE=8;
            FREQUENCY PORT "clk" 25.000000 MHz;
        """
        lines: list[str] = [
            f"# OpenForge LPF -- {self.name}",
            "BLOCK RESETPATHS;",
            "BLOCK ASYNCPATHS;",
        ]
        # Aggregate per-port IOBUF props (IO_TYPE/DRIVE/SLEW/PULL) so we only
        # emit one IOBUF line per port.
        iobuf: dict[str, dict[str, str]] = {}
        for c in self.constraints:
            port = c.target or c.name
            if c.kind == ConstraintKind.PIN_LOCATION:
                lines.append(f'LOCATE COMP "{port}" SITE "{c.value}";')
            elif c.kind == ConstraintKind.IO_STANDARD:
                iobuf.setdefault(port, {})["IO_TYPE"] = str(c.value)
            elif c.kind == ConstraintKind.DRIVE_STRENGTH:
                iobuf.setdefault(port, {})["DRIVE"] = str(c.value)
            elif c.kind == ConstraintKind.SLEW_RATE:
                iobuf.setdefault(port, {})["SLEWRATE"] = str(c.value).upper()
            elif c.kind == ConstraintKind.PULL:
                v = str(c.value).upper()
                if v in ("UP", "PULLUP"):
                    iobuf.setdefault(port, {})["PULLMODE"] = "UP"
                elif v in ("DOWN", "PULLDOWN"):
                    iobuf.setdefault(port, {})["PULLMODE"] = "DOWN"
                elif v in ("NONE",):
                    iobuf.setdefault(port, {})["PULLMODE"] = "NONE"
            elif c.kind == ConstraintKind.CLOCK:
                period = _as_float(c.value)
                if period and period > 0:
                    freq = 1000.0 / period  # period ns -> MHz
                    tgt = c.attrs.get("port") or c.target or c.name
                    # Strip [get_ports ...] if present
                    tgt = _strip_get_ports(tgt)
                    lines.append(f'FREQUENCY PORT "{tgt}" {freq:.6f} MHz;')
        for port, props in iobuf.items():
            parts = " ".join(f"{k}={v}" for k, v in props.items())
            lines.append(f'IOBUF PORT "{port}" {parts};')
        return "\n".join(lines) + "\n"

    @classmethod
    def from_lpf(cls, text: str, name: str = "default") -> ConstraintSet:
        cs = cls(name=name)
        locate_re = re.compile(
            r'^\s*LOCATE\s+COMP\s+"([^"]+)"\s+SITE\s+"([^"]+)"\s*;',
            re.IGNORECASE,
        )
        iobuf_re = re.compile(r'^\s*IOBUF\s+PORT\s+"([^"]+)"\s+(.*?);', re.IGNORECASE)
        freq_re = re.compile(
            r'^\s*FREQUENCY\s+PORT\s+"([^"]+)"\s+([\d.]+)\s*MHz\s*;',
            re.IGNORECASE,
        )
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("//"):
                continue
            m = locate_re.match(line)
            if m:
                cs.constraints.append(
                    Constraint(
                        kind=ConstraintKind.PIN_LOCATION,
                        target=m.group(1),
                        value=m.group(2),
                    )
                )
                continue
            m = iobuf_re.match(line)
            if m:
                port, body = m.group(1), m.group(2)
                for kv in body.split():
                    if "=" not in kv:
                        continue
                    k, v = kv.split("=", 1)
                    k = k.strip().upper()
                    v = v.strip()
                    if k == "IO_TYPE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.IO_STANDARD,
                                target=port,
                                value=v,
                            )
                        )
                    elif k == "DRIVE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.DRIVE_STRENGTH,
                                target=port,
                                value=v,
                            )
                        )
                    elif k == "SLEWRATE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.SLEW_RATE,
                                target=port,
                                value=v,
                            )
                        )
                    elif k == "PULLMODE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.PULL,
                                target=port,
                                value=v,
                            )
                        )
                continue
            m = freq_re.match(line)
            if m:
                port, mhz = m.group(1), float(m.group(2))
                period = 1000.0 / mhz if mhz > 0 else 0.0
                cs.constraints.append(
                    Constraint(
                        kind=ConstraintKind.CLOCK,
                        name=port,
                        target=f"[get_ports {port}]",
                        value=period,
                        units="ns",
                        attrs={"port": port, "freq_mhz": mhz},
                    )
                )
        return cs

    # ── PCF (iCE40 / nextpnr-ice40 / arachne-pnr) ───────────────────────────

    def to_pcf(self) -> str:
        """Emit PCF (Physical Constraints File).

        Real PCF syntax as used by nextpnr-ice40 / IceStorm:
            set_io led 95
            set_io -pullup yes btn 63
        """
        lines: list[str] = [f"# OpenForge PCF -- {self.name}"]
        pull_map: dict[str, str] = {}
        for c in self.constraints:
            if c.kind == ConstraintKind.PULL:
                port = c.target or c.name
                v = str(c.value).upper()
                if v in ("UP", "PULLUP"):
                    pull_map[port] = "yes"
        for c in self.constraints:
            if c.kind == ConstraintKind.PIN_LOCATION:
                port = c.target or c.name
                pin = c.value
                pu = pull_map.get(port)
                if pu:
                    lines.append(f"set_io -pullup {pu} {port} {pin}")
                else:
                    lines.append(f"set_io {port} {pin}")
        return "\n".join(lines) + "\n"

    @classmethod
    def from_pcf(cls, text: str, name: str = "default") -> ConstraintSet:
        cs = cls(name=name)
        for raw in text.splitlines():
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            if not line.startswith("set_io"):
                continue
            toks = line.split()
            # set_io [-nowarn] [-pullup yes|no] [-warn-no-port] port pin
            pullup: str | None = None
            i = 1
            port: str | None = None
            pin: str | None = None
            while i < len(toks):
                t = toks[i]
                if t == "-pullup" and i + 1 < len(toks):
                    pullup = toks[i + 1]
                    i += 2
                    continue
                if t.startswith("-"):
                    i += 1
                    continue
                if port is None:
                    port = t
                elif pin is None:
                    pin = t
                i += 1
            if port and pin:
                cs.constraints.append(
                    Constraint(
                        kind=ConstraintKind.PIN_LOCATION,
                        target=port,
                        value=pin,
                    )
                )
                if pullup and pullup.lower() in ("yes", "true", "1"):
                    cs.constraints.append(
                        Constraint(
                            kind=ConstraintKind.PULL,
                            target=port,
                            value="UP",
                        )
                    )
        return cs

    # ── CST (Gowin) ─────────────────────────────────────────────────────────

    def to_cst(self) -> str:
        """Emit Gowin CST text.

        Real CST syntax:
            IO_LOC "led[0]" 10;
            IO_PORT "led[0]" IO_TYPE=LVCMOS33 DRIVE=8 PULL_MODE=NONE;
        """
        lines: list[str] = [f"// OpenForge CST -- {self.name}"]
        port_attrs: dict[str, dict[str, str]] = {}
        for c in self.constraints:
            port = c.target or c.name
            if c.kind == ConstraintKind.PIN_LOCATION:
                lines.append(f'IO_LOC "{port}" {c.value};')
            elif c.kind == ConstraintKind.IO_STANDARD:
                port_attrs.setdefault(port, {})["IO_TYPE"] = str(c.value)
            elif c.kind == ConstraintKind.DRIVE_STRENGTH:
                port_attrs.setdefault(port, {})["DRIVE"] = str(c.value)
            elif c.kind == ConstraintKind.SLEW_RATE:
                port_attrs.setdefault(port, {})["SLEW_RATE"] = str(c.value).upper()
            elif c.kind == ConstraintKind.PULL:
                v = str(c.value).upper()
                mode = {
                    "UP": "UP",
                    "PULLUP": "UP",
                    "DOWN": "DOWN",
                    "PULLDOWN": "DOWN",
                    "NONE": "NONE",
                    "KEEPER": "KEEPER",
                }.get(v, "NONE")
                port_attrs.setdefault(port, {})["PULL_MODE"] = mode
        for port, props in port_attrs.items():
            parts = " ".join(f"{k}={v}" for k, v in props.items())
            lines.append(f'IO_PORT "{port}" {parts};')
        # Clock frequency comment (Gowin uses SDC for timing; CST is IO only)
        for c in self.by_kind(ConstraintKind.CLOCK):
            period = _as_float(c.value)
            if period and period > 0:
                freq = 1000.0 / period
                lines.append(
                    f"// create_clock {_strip_get_ports(c.target) or c.name} {freq:.3f}MHz"
                )
        return "\n".join(lines) + "\n"

    @classmethod
    def from_cst(cls, text: str, name: str = "default") -> ConstraintSet:
        cs = cls(name=name)
        io_loc_re = re.compile(r'^\s*IO_LOC\s+"([^"]+)"\s+([A-Za-z0-9_/]+)\s*;', re.IGNORECASE)
        io_port_re = re.compile(r'^\s*IO_PORT\s+"([^"]+)"\s+(.*?);', re.IGNORECASE)
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("//") or line.startswith("#"):
                continue
            m = io_loc_re.match(line)
            if m:
                cs.constraints.append(
                    Constraint(
                        kind=ConstraintKind.PIN_LOCATION,
                        target=m.group(1),
                        value=m.group(2),
                    )
                )
                continue
            m = io_port_re.match(line)
            if m:
                port, body = m.group(1), m.group(2)
                for kv in body.split():
                    if "=" not in kv:
                        continue
                    k, v = kv.split("=", 1)
                    k = k.strip().upper()
                    v = v.strip()
                    if k == "IO_TYPE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.IO_STANDARD,
                                target=port,
                                value=v,
                            )
                        )
                    elif k == "DRIVE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.DRIVE_STRENGTH,
                                target=port,
                                value=v,
                            )
                        )
                    elif k == "SLEW_RATE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.SLEW_RATE,
                                target=port,
                                value=v,
                            )
                        )
                    elif k == "PULL_MODE":
                        cs.constraints.append(
                            Constraint(
                                kind=ConstraintKind.PULL,
                                target=port,
                                value=v,
                            )
                        )
        return cs


# ─────────────────────────────────────────────────────────────────────────────
# Internals
# ─────────────────────────────────────────────────────────────────────────────


_SDC_KINDS = {
    ConstraintKind.CLOCK,
    ConstraintKind.GENERATED_CLOCK,
    ConstraintKind.INPUT_DELAY,
    ConstraintKind.OUTPUT_DELAY,
    ConstraintKind.FALSE_PATH,
    ConstraintKind.MULTICYCLE_PATH,
    ConstraintKind.MAX_DELAY,
    ConstraintKind.MIN_DELAY,
    ConstraintKind.SET_LOAD,
    ConstraintKind.SET_DRIVE,
    ConstraintKind.GROUP_PATH,
    ConstraintKind.CASE_ANALYSIS,
}

_XDC_PROP_TO_KIND: dict[str, ConstraintKind] = {
    "PACKAGE_PIN": ConstraintKind.PIN_LOCATION,
    "LOC": ConstraintKind.PIN_LOCATION,
    "IOSTANDARD": ConstraintKind.IO_STANDARD,
    "DRIVE": ConstraintKind.DRIVE_STRENGTH,
    "SLEW": ConstraintKind.SLEW_RATE,
    "PULLUP": ConstraintKind.PULL,
    "PULLDOWN": ConstraintKind.PULL,
    "KEEPER": ConstraintKind.PULL,
}


def _as_float(v: Any) -> float | None:
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _strip_get_ports(expr: str) -> str:
    if not expr:
        return ""
    m = re.search(r"get_ports\s+\{?([^\]\}]+)\}?", expr)
    if m:
        return m.group(1).strip()
    return expr.strip("[] {}")


def _iter_tcl_lines(text: str):
    """Yield logical TCL lines, handling backslash continuation and comments."""
    buf: list[str] = []
    for raw in text.splitlines():
        # strip full-line comment
        if raw.lstrip().startswith("#"):
            continue
        s = raw.rstrip()
        if s.endswith("\\"):
            buf.append(s[:-1])
            continue
        buf.append(s)
        line = " ".join(x.strip() for x in buf if x.strip())
        buf.clear()
        if line:
            yield line


def _sdc_line(c: Constraint) -> str:
    k = c.kind
    if k == ConstraintKind.CLOCK:
        # create_clock -name clk -period 10.0 [-waveform {0 5}] [get_ports clk]
        period = _as_float(c.value) or 0.0
        name = c.name or _strip_get_ports(c.target) or "clk"
        parts = ["create_clock", "-name", name, "-period", f"{period:g}"]
        wf = c.attrs.get("waveform")
        if isinstance(wf, (list, tuple)) and len(wf) == 2:
            parts += ["-waveform", f"{{{wf[0]} {wf[1]}}}"]
        tgt = c.target or f"[get_ports {name}]"
        parts.append(tgt)
        return " ".join(parts)
    if k == ConstraintKind.GENERATED_CLOCK:
        parts = ["create_generated_clock", "-name", c.name]
        if "source" in c.attrs:
            parts += ["-source", str(c.attrs["source"])]
        if "divide_by" in c.attrs:
            parts += ["-divide_by", str(c.attrs["divide_by"])]
        if "multiply_by" in c.attrs:
            parts += ["-multiply_by", str(c.attrs["multiply_by"])]
        parts.append(c.target or f"[get_pins {c.name}]")
        return " ".join(parts)
    if k == ConstraintKind.INPUT_DELAY:
        clk = c.attrs.get("clock", "clk")
        delay = _as_float(c.value) or 0.0
        flag = ""
        if c.attrs.get("max"):
            flag = " -max"
        elif c.attrs.get("min"):
            flag = " -min"
        return f"set_input_delay -clock {clk}{flag} {delay:g} {c.target}"
    if k == ConstraintKind.OUTPUT_DELAY:
        clk = c.attrs.get("clock", "clk")
        delay = _as_float(c.value) or 0.0
        flag = ""
        if c.attrs.get("max"):
            flag = " -max"
        elif c.attrs.get("min"):
            flag = " -min"
        return f"set_output_delay -clock {clk}{flag} {delay:g} {c.target}"
    if k == ConstraintKind.FALSE_PATH:
        parts = ["set_false_path"]
        if "from" in c.attrs:
            parts += ["-from", str(c.attrs["from"])]
        if "to" in c.attrs:
            parts += ["-to", str(c.attrs["to"])]
        if "through" in c.attrs:
            parts += ["-through", str(c.attrs["through"])]
        return " ".join(parts)
    if k == ConstraintKind.MULTICYCLE_PATH:
        parts = ["set_multicycle_path", str(c.value)]
        if c.attrs.get("setup"):
            parts.append("-setup")
        if c.attrs.get("hold"):
            parts.append("-hold")
        if "from" in c.attrs:
            parts += ["-from", str(c.attrs["from"])]
        if "to" in c.attrs:
            parts += ["-to", str(c.attrs["to"])]
        if "through" in c.attrs:
            parts += ["-through", str(c.attrs["through"])]
        return " ".join(parts)
    if k == ConstraintKind.MAX_DELAY:
        parts = ["set_max_delay", str(c.value)]
        if "from" in c.attrs:
            parts += ["-from", str(c.attrs["from"])]
        if "to" in c.attrs:
            parts += ["-to", str(c.attrs["to"])]
        return " ".join(parts)
    if k == ConstraintKind.MIN_DELAY:
        parts = ["set_min_delay", str(c.value)]
        if "from" in c.attrs:
            parts += ["-from", str(c.attrs["from"])]
        if "to" in c.attrs:
            parts += ["-to", str(c.attrs["to"])]
        return " ".join(parts)
    if k == ConstraintKind.SET_LOAD:
        return f"set_load {c.value} {c.target}"
    if k == ConstraintKind.SET_DRIVE:
        return f"set_drive {c.value} {c.target}"
    if k == ConstraintKind.GROUP_PATH:
        parts = ["group_path", "-name", c.name]
        if "from" in c.attrs:
            parts += ["-from", str(c.attrs["from"])]
        if "to" in c.attrs:
            parts += ["-to", str(c.attrs["to"])]
        if "weight" in c.attrs:
            parts += ["-weight", str(c.attrs["weight"])]
        return " ".join(parts)
    if k == ConstraintKind.CASE_ANALYSIS:
        return f"set_case_analysis {c.value} {c.target}"
    return ""


_CLOCK_RE = re.compile(r"^create_clock\s+(.*)$", re.IGNORECASE)
_GEN_CLOCK_RE = re.compile(r"^create_generated_clock\s+(.*)$", re.IGNORECASE)
_INPUT_DELAY_RE = re.compile(r"^set_input_delay\s+(.*)$", re.IGNORECASE)
_OUTPUT_DELAY_RE = re.compile(r"^set_output_delay\s+(.*)$", re.IGNORECASE)


def _tokenize_tcl(s: str) -> list[str]:
    """Simple TCL-ish tokenizer. Groups {...} and [...] together."""
    tokens: list[str] = []
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        if ch.isspace():
            i += 1
            continue
        if ch == "{":
            depth = 1
            j = i + 1
            while j < n and depth:
                if s[j] == "{":
                    depth += 1
                elif s[j] == "}":
                    depth -= 1
                j += 1
            tokens.append(s[i:j])
            i = j
            continue
        if ch == "[":
            depth = 1
            j = i + 1
            while j < n and depth:
                if s[j] == "[":
                    depth += 1
                elif s[j] == "]":
                    depth -= 1
                j += 1
            tokens.append(s[i:j])
            i = j
            continue
        if ch == '"':
            j = i + 1
            while j < n and s[j] != '"':
                j += 1
            tokens.append(s[i : j + 1])
            i = j + 1
            continue
        j = i
        while j < n and not s[j].isspace():
            j += 1
        tokens.append(s[i:j])
        i = j
    return tokens


def _parse_sdc_line(line: str) -> Constraint | None:
    line = line.strip()
    if not line:
        return None
    toks = _tokenize_tcl(line)
    if not toks:
        return None
    head = toks[0].lower()
    rest = toks[1:]

    def _get_opt(name: str) -> str | None:
        for i, t in enumerate(rest):
            if t == name and i + 1 < len(rest):
                return rest[i + 1]
        return None

    def _has_flag(name: str) -> bool:
        return name in rest

    def _positional() -> list[str]:
        out: list[str] = []
        skip = False
        for _i, t in enumerate(rest):
            if skip:
                skip = False
                continue
            if t.startswith("-") and t not in ("-setup", "-hold", "-max", "-min"):
                skip = True
                continue
            if t in ("-setup", "-hold", "-max", "-min"):
                continue
            out.append(t)
        return out

    if head == "create_clock":
        name = _get_opt("-name") or ""
        period = _as_float(_get_opt("-period")) or 0.0
        waveform = _get_opt("-waveform")
        pos = _positional()
        target = pos[-1] if pos else ""
        if not name:
            name = _strip_get_ports(target) or "clk"
        attrs: dict[str, Any] = {}
        if waveform:
            nums = re.findall(r"[\d.]+", waveform)
            if len(nums) >= 2:
                attrs["waveform"] = [float(nums[0]), float(nums[1])]
        return Constraint(
            kind=ConstraintKind.CLOCK,
            name=name,
            target=target,
            value=period,
            units="ns",
            attrs=attrs,
        )
    if head == "create_generated_clock":
        name = _get_opt("-name") or ""
        source = _get_opt("-source")
        div = _get_opt("-divide_by")
        mul = _get_opt("-multiply_by")
        pos = _positional()
        target = pos[-1] if pos else ""
        attrs: dict[str, Any] = {}
        if source:
            attrs["source"] = source
        if div:
            attrs["divide_by"] = int(div)
        if mul:
            attrs["multiply_by"] = int(mul)
        return Constraint(
            kind=ConstraintKind.GENERATED_CLOCK,
            name=name,
            target=target,
            attrs=attrs,
        )
    if head == "set_input_delay":
        clk = _get_opt("-clock") or ""
        pos = _positional()
        if len(pos) < 2:
            return None
        delay = _as_float(pos[0]) or 0.0
        target = pos[1]
        attrs: dict[str, Any] = {"clock": clk}
        if _has_flag("-max"):
            attrs["max"] = True
        if _has_flag("-min"):
            attrs["min"] = True
        return Constraint(
            kind=ConstraintKind.INPUT_DELAY,
            target=target,
            value=delay,
            units="ns",
            attrs=attrs,
        )
    if head == "set_output_delay":
        clk = _get_opt("-clock") or ""
        pos = _positional()
        if len(pos) < 2:
            return None
        delay = _as_float(pos[0]) or 0.0
        target = pos[1]
        attrs: dict[str, Any] = {"clock": clk}
        if _has_flag("-max"):
            attrs["max"] = True
        if _has_flag("-min"):
            attrs["min"] = True
        return Constraint(
            kind=ConstraintKind.OUTPUT_DELAY,
            target=target,
            value=delay,
            units="ns",
            attrs=attrs,
        )
    if head == "set_false_path":
        attrs: dict[str, Any] = {}
        for k in ("-from", "-to", "-through"):
            v = _get_opt(k)
            if v:
                attrs[k.lstrip("-")] = v
        return Constraint(kind=ConstraintKind.FALSE_PATH, attrs=attrs)
    if head == "set_multicycle_path":
        pos = _positional()
        val = pos[0] if pos else "1"
        attrs = {}
        for k in ("-from", "-to", "-through"):
            v = _get_opt(k)
            if v:
                attrs[k.lstrip("-")] = v
        if _has_flag("-setup"):
            attrs["setup"] = True
        if _has_flag("-hold"):
            attrs["hold"] = True
        return Constraint(kind=ConstraintKind.MULTICYCLE_PATH, value=val, attrs=attrs)
    if head == "set_max_delay":
        pos = _positional()
        val = pos[0] if pos else "0"
        attrs = {}
        for k in ("-from", "-to", "-through"):
            v = _get_opt(k)
            if v:
                attrs[k.lstrip("-")] = v
        return Constraint(kind=ConstraintKind.MAX_DELAY, value=val, attrs=attrs)
    if head == "set_min_delay":
        pos = _positional()
        val = pos[0] if pos else "0"
        attrs = {}
        for k in ("-from", "-to", "-through"):
            v = _get_opt(k)
            if v:
                attrs[k.lstrip("-")] = v
        return Constraint(kind=ConstraintKind.MIN_DELAY, value=val, attrs=attrs)
    if head == "set_load":
        pos = _positional()
        if len(pos) >= 2:
            return Constraint(kind=ConstraintKind.SET_LOAD, value=pos[0], target=pos[1])
    if head == "set_drive":
        pos = _positional()
        if len(pos) >= 2:
            return Constraint(kind=ConstraintKind.SET_DRIVE, value=pos[0], target=pos[1])
    if head == "group_path":
        name = _get_opt("-name") or ""
        attrs = {}
        for k in ("-from", "-to", "-weight"):
            v = _get_opt(k)
            if v:
                attrs[k.lstrip("-")] = v
        return Constraint(kind=ConstraintKind.GROUP_PATH, name=name, attrs=attrs)
    if head == "set_case_analysis":
        pos = _positional()
        if len(pos) >= 2:
            return Constraint(kind=ConstraintKind.CASE_ANALYSIS, value=pos[0], target=pos[1])
    return None
