/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/counter.v:2.1-22.10" *)
module counter(clk, rst_n, enable, count, overflow);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* force_downto = 32'd1 *)
  (* src = "src/counter.v:18.22-18.34|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "src/counter.v:18.22-18.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _08_;
  (* src = "src/counter.v:5.29-5.32" *)
  input clk;
  wire clk;
  (* src = "src/counter.v:8.29-8.34" *)
  output [7:0] count;
  reg [7:0] count;
  (* src = "src/counter.v:7.29-7.35" *)
  input enable;
  wire enable;
  (* src = "src/counter.v:9.29-9.37" *)
  output overflow;
  wire overflow;
  (* src = "src/counter.v:6.29-6.34" *)
  input rst_n;
  wire rst_n;
  assign _07_[0] = ~count[0];
  assign _00_ = count[0] & count[1];
  assign _01_ = count[2] & _00_;
  assign _02_ = count[3] & _01_;
  assign _03_ = count[4] & _02_;
  assign _04_ = count[5] & _03_;
  assign _05_ = count[6] & _04_;
  assign _06_ = count[7] & _05_;
  assign overflow = enable & _06_;
  assign _08_[1] = count[0] ^ count[1];
  assign _08_[2] = count[2] ^ _00_;
  assign _08_[3] = count[3] ^ _01_;
  assign _08_[4] = count[4] ^ _02_;
  assign _08_[5] = count[5] ^ _03_;
  assign _08_[6] = count[6] ^ _04_;
  assign _08_[7] = count[7] ^ _05_;
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[0] <= 1'h0;
    else if (enable) count[0] <= _07_[0];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[1] <= 1'h0;
    else if (enable) count[1] <= _08_[1];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[2] <= 1'h0;
    else if (enable) count[2] <= _08_[2];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[3] <= 1'h0;
    else if (enable) count[3] <= _08_[3];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[4] <= 1'h0;
    else if (enable) count[4] <= _08_[4];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[5] <= 1'h0;
    else if (enable) count[5] <= _08_[5];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[6] <= 1'h0;
    else if (enable) count[6] <= _08_[6];
  (* src = "src/counter.v:14.5-20.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[7] <= 1'h0;
    else if (enable) count[7] <= _08_[7];
  assign _07_[7:1] = count[7:1];
  assign _08_[0] = _07_[0];
endmodule
