/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* top =  1  *)
(* src = "src/uart_tx.v:7.1-106.10" *)
module uart_tx(clk, rst_n, tx_data, tx_valid, tx_ready, tx_out, tx_active);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  (* src = "src/uart_tx.v:27.16-27.25" *)
  wire [2:0] bit_index;
  (* src = "src/uart_tx.v:10.23-10.26" *)
  input clk;
  wire clk;
  (* src = "src/uart_tx.v:26.16-26.25" *)
  wire [15:0] clk_count;
  (* src = "src/uart_tx.v:11.23-11.28" *)
  input rst_n;
  wire rst_n;
  (* src = "src/uart_tx.v:25.16-25.21" *)
  wire [2:0] state;
  (* src = "src/uart_tx.v:16.23-16.32" *)
  output tx_active;
  wire tx_active;
  (* src = "src/uart_tx.v:12.23-12.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "src/uart_tx.v:15.23-15.29" *)
  output tx_out;
  wire tx_out;
  (* src = "src/uart_tx.v:14.23-14.31" *)
  output tx_ready;
  wire tx_ready;
  (* src = "src/uart_tx.v:28.16-28.24" *)
  wire [7:0] tx_shift;
  (* src = "src/uart_tx.v:13.23-13.31" *)
  input tx_valid;
  wire tx_valid;
  sky130_fd_sc_hd__nand2_1 _130_ (
    .A(clk_count[1]),
    .B(clk_count[2]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__inv_1 _131_ (
    .A(clk_count[3]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__and2b_2 _133_ (
    .A_N(clk_count[7]),
    .B(clk_count[6]),
    .X(_109_)
  );
  sky130_fd_sc_hd__and2b_2 _134_ (
    .A_N(clk_count[5]),
    .B(clk_count[4]),
    .X(_110_)
  );
  sky130_fd_sc_hd__a21o_2 _135_ (
    .A1(clk_count[5]),
    .A2(clk_count[6]),
    .B1(clk_count[7]),
    .X(_111_)
  );
  sky130_fd_sc_hd__a31oi_1 _136_ (
    .A1(_108_),
    .A2(_109_),
    .A3(_110_),
    .B1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(clk_count[14]),
    .B(clk_count[15]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__inv_1 _138_ (
    .A(clk_count[12]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__inv_1 _139_ (
    .A(clk_count[13]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand3_1 _140_ (
    .A(_113_),
    .B(_114_),
    .C(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__inv_1 _141_ (
    .A(clk_count[8]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__inv_1 _142_ (
    .A(clk_count[9]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__inv_1 _143_ (
    .A(clk_count[10]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__inv_1 _144_ (
    .A(clk_count[11]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand4_1 _145_ (
    .A(_117_),
    .B(_118_),
    .C(_119_),
    .D(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(_116_),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__lpflow_clkinvkapwr_1 _147_ (
    .A(state[2]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__inv_1 _148_ (
    .A(state[0]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__inv_1 _149_ (
    .A(state[1]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(_124_),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand4_1 _151_ (
    .A(_112_),
    .B(_122_),
    .C(_123_),
    .D(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__inv_1 _152_ (
    .A(clk_count[0]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(state[2]),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a21oi_1 _154_ (
    .A1(_127_),
    .A2(_128_),
    .B1(_129_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(clk_count[1]),
    .B(_129_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(_126_),
    .B(_123_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand3_1 _157_ (
    .A(_108_),
    .B(_109_),
    .C(_110_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor4_1 _158_ (
    .A(clk_count[12]),
    .B(clk_count[13]),
    .C(clk_count[14]),
    .D(clk_count[15]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor4_1 _159_ (
    .A(clk_count[8]),
    .B(clk_count[9]),
    .C(clk_count[10]),
    .D(clk_count[11]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(clk_count[5]),
    .A2(clk_count[6]),
    .B1(clk_count[7]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand4_1 _161_ (
    .A(_034_),
    .B(_035_),
    .C(_036_),
    .D(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_033_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _163_ (
    .A(state[2]),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(_032_),
    .B(_040_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a21oi_1 _165_ (
    .A1(_129_),
    .A2(clk_count[1]),
    .B1(clk_count[2]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _166_ (
    .A(state[2]),
    .B(_128_),
    .C(_106_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor3_1 _167_ (
    .A(_041_),
    .B(_042_),
    .C(_040_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_1 _168_ (
    .A(_107_),
    .B(_042_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _169_ (
    .A(_043_),
    .B(_040_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_1 _170_ (
    .A(clk_count[4]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkbuf_8 _171_ (
    .A(_123_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(_128_),
    .B(_106_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_046_),
    .B(clk_count[3]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_044_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_047_),
    .B(_044_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand3b_1 _176_ (
    .A_N(_048_),
    .B(_039_),
    .C(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _177_ (
    .A1(_044_),
    .A2(_045_),
    .B1(_050_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21oi_1 _178_ (
    .A1(_048_),
    .A2(_123_),
    .B1(clk_count[5]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and3_2 _179_ (
    .A(_048_),
    .B(clk_count[5]),
    .C(_123_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _180_ (
    .A(_051_),
    .B(_052_),
    .C(_040_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_1 _181_ (
    .A(clk_count[6]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(clk_count[4]),
    .B(clk_count[5]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(_054_),
    .B(_047_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(_055_),
    .B(clk_count[6]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _185_ (
    .A1(_054_),
    .A2(_047_),
    .B1(_053_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand3_1 _186_ (
    .A(_039_),
    .B(_056_),
    .C(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _187_ (
    .A1(_053_),
    .A2(_123_),
    .B1(_058_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_1 _188_ (
    .A(clk_count[7]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(_059_),
    .B(_045_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(_117_),
    .B(_045_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(_118_),
    .B(_045_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_119_),
    .B(_045_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _193_ (
    .A(_120_),
    .B(_045_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(_114_),
    .B(_045_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(_115_),
    .B(_045_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_1 _196_ (
    .A(clk_count[14]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_060_),
    .B(_045_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_1 _198_ (
    .A(clk_count[15]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(_061_),
    .B(_045_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_1 _200_ (
    .A(bit_index[0]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _201_ (
    .A(tx_shift[5]),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__inv_1 _202_ (
    .A(bit_index[1]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o21ai_0 _203_ (
    .A1(bit_index[0]),
    .A2(tx_shift[4]),
    .B1(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(bit_index[0]),
    .B(_064_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_062_),
    .B(_064_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__inv_1 _206_ (
    .A(bit_index[2]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a221oi_1 _207_ (
    .A1(_066_),
    .A2(tx_shift[6]),
    .B1(_067_),
    .B2(tx_shift[7]),
    .C1(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _208_ (
    .A1(_063_),
    .A2(_065_),
    .B1(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _209_ (
    .A1(bit_index[0]),
    .A2(tx_shift[0]),
    .B1(_064_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _210_ (
    .A(tx_shift[1]),
    .B(_062_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_066_),
    .B(tx_shift[2]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_067_),
    .B(tx_shift[3]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o2111ai_1 _213_ (
    .A1(_071_),
    .A2(_072_),
    .B1(_068_),
    .C1(_073_),
    .D1(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(_124_),
    .B(_123_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_125_),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand3_1 _216_ (
    .A(_070_),
    .B(_075_),
    .C(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(tx_out),
    .B(state[2]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor3_1 _218_ (
    .A(state[2]),
    .B(_124_),
    .C(_125_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand3_1 _219_ (
    .A(_124_),
    .B(_125_),
    .C(_123_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__inv_1 _220_ (
    .A(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand3_1 _222_ (
    .A(_078_),
    .B(_079_),
    .C(_083_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_1 _223_ (
    .A(_080_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(_084_),
    .B(_038_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(_083_),
    .A2(_085_),
    .B1(tx_active),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_2 _226_ (
    .A(_082_),
    .B(tx_valid),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_086_),
    .B(_087_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(_067_),
    .B(bit_index[2]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand3_1 _229_ (
    .A(_038_),
    .B(_077_),
    .C(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__or2_2 _230_ (
    .A(tx_valid),
    .B(_081_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand3_1 _231_ (
    .A(_089_),
    .B(_127_),
    .C(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_091_),
    .B(state[0]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_038_),
    .B(_077_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21a_1 _234_ (
    .A1(_088_),
    .A2(_093_),
    .B1(_087_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_092_),
    .B(_094_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_091_),
    .B(state[1]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand4_1 _237_ (
    .A(_038_),
    .B(state[0]),
    .C(_125_),
    .D(_123_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21a_1 _238_ (
    .A1(_088_),
    .A2(_093_),
    .B1(_096_),
    .X(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_095_),
    .B(_097_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a31oi_1 _240_ (
    .A1(_112_),
    .A2(_122_),
    .A3(state[1]),
    .B1(_076_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _241_ (
    .A(_038_),
    .B(_062_),
    .C(_077_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21ai_0 _242_ (
    .A1(_062_),
    .A2(_098_),
    .B1(_099_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _243_ (
    .A(bit_index[1]),
    .B(_062_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21ai_0 _244_ (
    .A1(_066_),
    .A2(_100_),
    .B1(_038_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o32ai_1 _245_ (
    .A1(_125_),
    .A2(_076_),
    .A3(_101_),
    .B1(_064_),
    .B2(_098_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xor2_1 _246_ (
    .A(bit_index[2]),
    .B(_067_),
    .X(_102_)
  );
  sky130_fd_sc_hd__nand3_1 _247_ (
    .A(_102_),
    .B(_038_),
    .C(_077_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _248_ (
    .A1(_068_),
    .A2(_098_),
    .B1(_103_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__mux2_2 _249_ (
    .A0(tx_data[0]),
    .A1(tx_shift[0]),
    .S(_087_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_2 _250_ (
    .A0(tx_data[1]),
    .A1(tx_shift[1]),
    .S(_087_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_2 _251_ (
    .A0(tx_data[2]),
    .A1(tx_shift[2]),
    .S(_087_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_2 _252_ (
    .A0(tx_data[3]),
    .A1(tx_shift[3]),
    .S(_087_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_2 _253_ (
    .A0(tx_data[4]),
    .A1(tx_shift[4]),
    .S(_087_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_2 _254_ (
    .A0(tx_data[5]),
    .A1(tx_shift[5]),
    .S(_087_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_2 _255_ (
    .A0(tx_data[6]),
    .A1(tx_shift[6]),
    .S(_087_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_2 _256_ (
    .A0(tx_data[7]),
    .A1(tx_shift[7]),
    .S(_087_),
    .X(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _257_ (
    .A1(_083_),
    .A2(_085_),
    .B1(tx_ready),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(_038_),
    .B(_080_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand3_1 _259_ (
    .A(_104_),
    .B(_090_),
    .C(_105_),
    .Y(_031_)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _260_ (
    .CLK(clk),
    .D(_000_),
    .Q(clk_count[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _261_ (
    .CLK(clk),
    .D(_001_),
    .Q(clk_count[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _262_ (
    .CLK(clk),
    .D(_002_),
    .Q(clk_count[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _263_ (
    .CLK(clk),
    .D(_003_),
    .Q(clk_count[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _264_ (
    .CLK(clk),
    .D(_004_),
    .Q(clk_count[4]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _265_ (
    .CLK(clk),
    .D(_005_),
    .Q(clk_count[5]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _266_ (
    .CLK(clk),
    .D(_006_),
    .Q(clk_count[6]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _267_ (
    .CLK(clk),
    .D(_007_),
    .Q(clk_count[7]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _268_ (
    .CLK(clk),
    .D(_008_),
    .Q(clk_count[8]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _269_ (
    .CLK(clk),
    .D(_009_),
    .Q(clk_count[9]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _270_ (
    .CLK(clk),
    .D(_010_),
    .Q(clk_count[10]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _271_ (
    .CLK(clk),
    .D(_011_),
    .Q(clk_count[11]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _272_ (
    .CLK(clk),
    .D(_012_),
    .Q(clk_count[12]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _273_ (
    .CLK(clk),
    .D(_013_),
    .Q(clk_count[13]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _274_ (
    .CLK(clk),
    .D(_014_),
    .Q(clk_count[14]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _275_ (
    .CLK(clk),
    .D(_015_),
    .Q(clk_count[15]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfstp_2 _276_ (
    .CLK(clk),
    .D(_016_),
    .Q(tx_out),
    .SET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _277_ (
    .CLK(clk),
    .D(_017_),
    .Q(tx_active),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _278_ (
    .CLK(clk),
    .D(_018_),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _279_ (
    .CLK(clk),
    .D(_019_),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _280_ (
    .CLK(clk),
    .D(1'h0),
    .Q(state[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _281_ (
    .CLK(clk),
    .D(_020_),
    .Q(bit_index[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _282_ (
    .CLK(clk),
    .D(_021_),
    .Q(bit_index[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _283_ (
    .CLK(clk),
    .D(_022_),
    .Q(bit_index[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _284_ (
    .CLK(clk),
    .D(_023_),
    .Q(tx_shift[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _285_ (
    .CLK(clk),
    .D(_024_),
    .Q(tx_shift[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _286_ (
    .CLK(clk),
    .D(_025_),
    .Q(tx_shift[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _287_ (
    .CLK(clk),
    .D(_026_),
    .Q(tx_shift[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _288_ (
    .CLK(clk),
    .D(_027_),
    .Q(tx_shift[4]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _289_ (
    .CLK(clk),
    .D(_028_),
    .Q(tx_shift[5]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _290_ (
    .CLK(clk),
    .D(_029_),
    .Q(tx_shift[6]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfrtp_1 _291_ (
    .CLK(clk),
    .D(_030_),
    .Q(tx_shift[7]),
    .RESET_B(rst_n)
  );
  (* src = "src/uart_tx.v:30.5-104.8" *)
  sky130_fd_sc_hd__dfstp_2 _292_ (
    .CLK(clk),
    .D(_031_),
    .Q(tx_ready),
    .SET_B(rst_n)
  );
endmodule
