"""Address map editor for OpenForge block designs.

Pydantic v2 schema of AXI address ranges with auto-assign, overlap
detection, and exporters for synthesizable Verilog address decoders,
Linux device tree fragments, and C header files.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


def _fmt_hex(value: int, width_bits: int = 32) -> str:
    digits = max(8, (width_bits + 3) // 4)
    return f"0x{value:0{digits}X}"


def _size_human(size: int) -> str:
    if size % (1 << 30) == 0:
        return f"{size >> 30}G"
    if size % (1 << 20) == 0:
        return f"{size >> 20}M"
    if size % (1 << 10) == 0:
        return f"{size >> 10}K"
    return f"{size}B"


class AddressRange(BaseModel):
    """One address-space allocation."""

    master: str
    slave: str
    interface: str = "S_AXI"
    base_addr: int = 0
    range_size: int = 0x1000
    locked: bool = False
    name: str = ""

    @property
    def end_addr(self) -> int:
        return self.base_addr + self.range_size - 1

    def overlaps_with(self, other: AddressRange) -> bool:
        if self.master != other.master:
            return False
        return not (
            self.end_addr < other.base_addr or other.end_addr < self.base_addr
        )


class AddressMap(BaseModel):
    """Collection of :class:`AddressRange` entries."""

    ranges: list[AddressRange] = Field(default_factory=list)
    address_width: int = 32

    # ------------------------------------------------------------------
    def auto_assign(
        self,
        masters: list[str],
        slaves: list[dict],
        base: int = 0x4000_0000,
    ) -> AddressMap:
        """Assign non-overlapping, naturally-aligned regions to all slaves.

        ``slaves`` is a list of ``{name, interface, size}`` dicts. Locked
        ranges are preserved in place.
        """
        locked = [r for r in self.ranges if r.locked]
        ranges: list[AddressRange] = list(locked)

        def _round_up(addr: int, align: int) -> int:
            return (addr + align - 1) & ~(align - 1)

        for master in masters or ["M_AXI"]:
            cursor = base
            for slave in slaves:
                size = int(slave.get("size", 0x1000))
                align = 1 << max(12, (size - 1).bit_length())
                cursor = _round_up(cursor, align)
                # Skip over any locked ranges in this master
                while any(
                    r.master == master and not (cursor + size - 1 < r.base_addr or r.end_addr < cursor)
                    for r in locked
                ):
                    conflict = next(
                        r for r in locked
                        if r.master == master and not (cursor + size - 1 < r.base_addr or r.end_addr < cursor)
                    )
                    cursor = _round_up(conflict.end_addr + 1, align)
                ranges.append(
                    AddressRange(
                        master=master,
                        slave=slave["name"],
                        interface=slave.get("interface", "S_AXI"),
                        base_addr=cursor,
                        range_size=size,
                        name=f"{slave['name']}_reg",
                    )
                )
                cursor += size
        self.ranges = ranges
        return self

    # ------------------------------------------------------------------
    def overlaps(self) -> list[tuple[AddressRange, AddressRange]]:
        conflicts: list[tuple[AddressRange, AddressRange]] = []
        for i, a in enumerate(self.ranges):
            for b in self.ranges[i + 1:]:
                if a.overlaps_with(b):
                    conflicts.append((a, b))
        return conflicts

    # ------------------------------------------------------------------
    def to_verilog_decoder(self, top_module: str) -> str:
        """Generate a synthesizable Verilog address decoder.

        One ``sel_<slave>`` output is emitted per range; the input is the
        full-width address on the master. The module uses a combinational
        ``always @*`` block and registers are not inferred.
        """
        aw = self.address_width
        lines: list[str] = []
        lines.append("// ===========================================================")
        lines.append(f"// {top_module} -- address decoder")
        lines.append("// Auto-generated by OpenForge AddressMap.to_verilog_decoder")
        lines.append("// ===========================================================")
        lines.append("`default_nettype none")
        lines.append(f"module {top_module} (")
        lines.append(f"    input  wire [{aw - 1}:0] addr,")
        for i, r in enumerate(self.ranges):
            comma = "," if i < len(self.ranges) - 1 else ""
            lines.append(f"    output reg  sel_{r.slave}{comma}")
        lines.append(");")
        lines.append("")
        for r in self.ranges:
            lines.append(
                f"    localparam [{aw - 1}:0] BASE_{r.slave.upper()} = "
                f"{aw}'h{r.base_addr:0{(aw + 3) // 4}X};"
            )
            lines.append(
                f"    localparam [{aw - 1}:0] MASK_{r.slave.upper()} = "
                f"{aw}'h{(~(r.range_size - 1)) & ((1 << aw) - 1):0{(aw + 3) // 4}X};"
            )
        lines.append("")
        lines.append("    always @* begin")
        for r in self.ranges:
            lines.append(f"        sel_{r.slave} = 1'b0;")
        for r in self.ranges:
            lines.append(
                f"        if ((addr & MASK_{r.slave.upper()}) == BASE_{r.slave.upper()})"
                f" sel_{r.slave} = 1'b1;"
            )
        lines.append("    end")
        lines.append("endmodule")
        lines.append("`default_nettype wire")
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    def to_device_tree(self) -> str:
        """Emit a Linux device-tree fragment with reg properties."""
        lines = ["/ {", "    openforge_bus {"]
        lines.append("        #address-cells = <1>;")
        lines.append("        #size-cells = <1>;")
        for r in self.ranges:
            node = r.slave.lower().replace("_", "-")
            lines.append(
                f"        {node}@{r.base_addr:x} {{"
            )
            lines.append(f'            compatible = "openforge,{node}";')
            lines.append(
                f"            reg = <0x{r.base_addr:08x} 0x{r.range_size:08x}>;"
            )
            lines.append("        };")
        lines.append("    };")
        lines.append("};")
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    def to_header_file(self) -> str:
        lines = [
            "/* Auto-generated by OpenForge AddressMap.to_header_file */",
            "#ifndef OPENFORGE_ADDRESS_MAP_H",
            "#define OPENFORGE_ADDRESS_MAP_H",
            "",
        ]
        for r in self.ranges:
            sym = r.slave.upper()
            lines.append(
                f"#define BASE_{sym:<20} {_fmt_hex(r.base_addr, self.address_width)}"
            )
            lines.append(
                f"#define SIZE_{sym:<20} {_fmt_hex(r.range_size, self.address_width)}"
            )
        lines.append("")
        lines.append("#endif /* OPENFORGE_ADDRESS_MAP_H */")
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    def memory_map_diagram(self) -> str:
        """Return a simple ASCII memory map."""
        if not self.ranges:
            return "(empty address map)\n"
        ordered = sorted(self.ranges, key=lambda r: r.base_addr)
        width = max(len(r.slave) for r in ordered) + 2
        lines = [f"+{'-' * (width + 30)}+"]
        lines.append(f"| {'Slave'.ljust(width)} {'Base'.ljust(12)} {'Size'.ljust(12)} |")
        lines.append(f"+{'-' * (width + 30)}+")
        for r in ordered:
            lines.append(
                f"| {r.slave.ljust(width)} "
                f"{_fmt_hex(r.base_addr, self.address_width).ljust(12)} "
                f"{_size_human(r.range_size).ljust(12)} |"
            )
        lines.append(f"+{'-' * (width + 30)}+")
        return "\n".join(lines) + "\n"


__all__ = ["AddressRange", "AddressMap"]
