"""Caravel user_project_wrapper template generator.

Generates a complete Caravel-compatible project skeleton matching the
official ``caravel_user_project`` repository layout:

    <project>/
        openforge.yaml
        verilog/rtl/<user_module>.v
        verilog/rtl/user_project_wrapper.v
        openlane/<user_module>/config.json
        sdc/user_proj.sdc
        signoff/
        README.md

The wrapper Verilog matches the official Caravel user_project_wrapper
interface (38-bit io, 128-bit logic analyzer, wishbone slave, 3 IRQs).
"""
from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, Field


class CaravelConfig(BaseModel):
    project_name: str
    user_module_name: str = "user_proj_example"
    io_count: int = 38
    la_count: int = 128
    wb_enabled: bool = True
    irq_count: int = 3
    target_freq_mhz: float = 25.0
    clock_port: str = "wb_clk_i"
    pdk: str = "sky130A"
    std_cell_library: str = "sky130_fd_sc_hd"
    extra: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Verilog templates
# ---------------------------------------------------------------------------

_USER_MODULE_TMPL = """\
// SPDX-License-Identifier: Apache-2.0
// Generated by OpenForge Caravel template
`default_nettype none

module {module} #(
    parameter BITS = 32
) (
`ifdef USE_POWER_PINS
    inout vccd1,
    inout vssd1,
`endif
    // Wishbone slave
    input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire        wbs_stb_i,
    input  wire        wbs_cyc_i,
    input  wire        wbs_we_i,
    input  wire [3:0]  wbs_sel_i,
    input  wire [31:0] wbs_dat_i,
    input  wire [31:0] wbs_adr_i,
    output wire        wbs_ack_o,
    output wire [31:0] wbs_dat_o,

    // Logic Analyzer
    input  wire [{la_hi}:0] la_data_in,
    output wire [{la_hi}:0] la_data_out,
    input  wire [{la_hi}:0] la_oenb,

    // IO pads
    input  wire [{io_hi}:0] io_in,
    output wire [{io_hi}:0] io_out,
    output wire [{io_hi}:0] io_oeb,

    // IRQs
    output wire [{irq_hi}:0] user_irq
);

    // Minimal example: wishbone-accessible counter
    reg [BITS-1:0] count;
    reg            ack;

    wire valid  = wbs_cyc_i && wbs_stb_i;
    wire we     = valid && wbs_we_i;

    always @(posedge wb_clk_i) begin
        if (wb_rst_i) begin
            count <= {{BITS{{1'b0}}}};
            ack   <= 1'b0;
        end else begin
            ack <= valid && !ack;
            if (we && ack) begin
                count <= wbs_dat_i[BITS-1:0];
            end else if (!we) begin
                count <= count + 1'b1;
            end
        end
    end

    assign wbs_ack_o = ack;
    assign wbs_dat_o = {{{{(32-BITS){{1'b0}}}}, count}};

    // IO: drive low bits from counter, leave the rest Hi-Z
    assign io_out  = {{{{({io_count}-BITS){{1'b0}}}}, count}};
    assign io_oeb  = {{{io_count}{{1'b0}}}};

    // Logic analyzer: expose count on low bits
    assign la_data_out = {{{{({la_count}-BITS){{1'b0}}}}, count}};

    // IRQs unused
    assign user_irq = {irq_count}'b0;

endmodule
`default_nettype wire
"""


_WRAPPER_TMPL = """\
// SPDX-License-Identifier: Apache-2.0
// Generated by OpenForge Caravel template
// Matches the official caravel user_project_wrapper interface.
`default_nettype none

module user_project_wrapper (
`ifdef USE_POWER_PINS
    inout vdda1,    // User area 1 3.3V supply
    inout vdda2,    // User area 2 3.3V supply
    inout vssa1,    // User area 1 analog ground
    inout vssa2,    // User area 2 analog ground
    inout vccd1,    // User area 1 1.8V supply
    inout vccd2,    // User area 2 1.8V supply
    inout vssd1,    // User area 1 digital ground
    inout vssd2,    // User area 2 digital ground
`endif
    // Wishbone slave from Caravel management SoC
    input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire        wbs_stb_i,
    input  wire        wbs_cyc_i,
    input  wire        wbs_we_i,
    input  wire [3:0]  wbs_sel_i,
    input  wire [31:0] wbs_dat_i,
    input  wire [31:0] wbs_adr_i,
    output wire        wbs_ack_o,
    output wire [31:0] wbs_dat_o,

    // Logic analyzer (128 bits)
    input  wire [127:0] la_data_in,
    output wire [127:0] la_data_out,
    input  wire [127:0] la_oenb,

    // IOs (38)
    input  wire [`MPRJ_IO_PADS-1:0] io_in,
    output wire [`MPRJ_IO_PADS-1:0] io_out,
    output wire [`MPRJ_IO_PADS-1:0] io_oeb,

    // Independent clock
    input  wire user_clock2,

    // User maskable interrupt signals
    output wire [2:0] user_irq
);

    {module} #(
        .BITS(32)
    ) u_{module} (
`ifdef USE_POWER_PINS
        .vccd1(vccd1),
        .vssd1(vssd1),
`endif
        .wb_clk_i (wb_clk_i),
        .wb_rst_i (wb_rst_i),
        .wbs_stb_i(wbs_stb_i),
        .wbs_cyc_i(wbs_cyc_i),
        .wbs_we_i (wbs_we_i),
        .wbs_sel_i(wbs_sel_i),
        .wbs_dat_i(wbs_dat_i),
        .wbs_adr_i(wbs_adr_i),
        .wbs_ack_o(wbs_ack_o),
        .wbs_dat_o(wbs_dat_o),

        .la_data_in (la_data_in),
        .la_data_out(la_data_out),
        .la_oenb    (la_oenb),

        .io_in (io_in),
        .io_out(io_out),
        .io_oeb(io_oeb),

        .user_irq(user_irq)
    );

endmodule
`default_nettype wire
"""


_SDC_TMPL = """\
# Generated by OpenForge Caravel template
set ::env(CLOCK_PORT) {clock}
set ::env(CLOCK_PERIOD) {period}

create_clock -name clk -period {period} [get_ports {{{clock}}}]
set_clock_uncertainty 0.25 [get_clocks clk]
set_clock_transition  0.15 [get_clocks clk]

set_input_delay  -clock clk -max 2.0 [all_inputs]
set_output_delay -clock clk -max 2.0 [all_outputs]

set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 [all_inputs]
set_load 0.1 [all_outputs]
"""


_OPENFORGE_YAML_TMPL = """\
# Generated by OpenForge Caravel template
project:
  name: {name}
  top_module: user_project_wrapper
  description: Caravel user_project_wrapper for {name}

design:
  sources:
    - verilog/rtl/{module}.v
    - verilog/rtl/user_project_wrapper.v
  constraints:
    - sdc/user_proj.sdc

pdk:
  name: {pdk}
  std_cell_library: {stdcell}

flow:
  target: asic
  tool: openlane2
  clock_port: {clock}
  clock_period_ns: {period}
"""


_README_TMPL = """\
# {name}

Caravel user_project_wrapper generated by **OpenForge** for Efabless / SkyWater sky130 MPW shuttles.

## Layout

```
{name}/
  openforge.yaml              # OpenForge project config
  verilog/rtl/{module}.v
  verilog/rtl/user_project_wrapper.v
  openlane/{module}/config.json
  sdc/user_proj.sdc
  signoff/                    # DRC / LVS / antenna reports land here
```

## Build

```bash
# from the project root
openforge pdk install {pdk}
openforge openlane run --design openlane/{module}
```

Or from the OpenForge desktop app, open this directory and use the
**OpenLane** dock to run the full RTL → GDSII flow.

## Interface

The wrapper matches the official Caravel ``user_project_wrapper`` pinout:

- 38 GPIO (`io_in` / `io_out` / `io_oeb`)
- 128 logic analyzer bits (`la_data_in` / `la_data_out` / `la_oenb`)
- Wishbone slave (`wbs_*`)
- 3 user IRQs (`user_irq`)
- Clock: ``{clock}`` @ {freq} MHz
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def _format_verilog(module: str, cfg: CaravelConfig) -> str:
    return _USER_MODULE_TMPL.format(
        module=module,
        io_hi=cfg.io_count - 1,
        io_count=cfg.io_count,
        la_hi=cfg.la_count - 1,
        la_count=cfg.la_count,
        irq_hi=max(cfg.irq_count - 1, 0),
        irq_count=cfg.irq_count,
    )


def _format_wrapper(module: str) -> str:
    return _WRAPPER_TMPL.format(module=module)


def _format_sdc(cfg: CaravelConfig) -> str:
    period = 1000.0 / cfg.target_freq_mhz
    return _SDC_TMPL.format(clock=cfg.clock_port, period=f"{period:.3f}")


def _format_openforge_yaml(cfg: CaravelConfig) -> str:
    period = 1000.0 / cfg.target_freq_mhz
    return _OPENFORGE_YAML_TMPL.format(
        name=cfg.project_name,
        module=cfg.user_module_name,
        pdk=cfg.pdk,
        stdcell=cfg.std_cell_library,
        clock=cfg.clock_port,
        period=f"{period:.3f}",
    )


def _format_readme(cfg: CaravelConfig) -> str:
    return _README_TMPL.format(
        name=cfg.project_name,
        module=cfg.user_module_name,
        pdk=cfg.pdk,
        clock=cfg.clock_port,
        freq=cfg.target_freq_mhz,
    )


def _openlane_config(cfg: CaravelConfig) -> dict:
    period = 1000.0 / cfg.target_freq_mhz
    return {
        "DESIGN_NAME": cfg.user_module_name,
        "VERILOG_FILES": [
            f"dir::../../verilog/rtl/{cfg.user_module_name}.v",
        ],
        "CLOCK_PORT": cfg.clock_port,
        "CLOCK_PERIOD": round(period, 3),
        "FP_CORE_UTIL": 45,
        "PL_TARGET_DENSITY": 0.55,
        "SYNTH_STRATEGY": "AREA 0",
        "PDK": cfg.pdk,
        "STD_CELL_LIBRARY": cfg.std_cell_library,
        "DESIGN_IS_CORE": False,
        "BASE_SDC_FILE": "dir::../../sdc/user_proj.sdc",
        "FP_PDN_CORE_RING": False,
        "RUN_CVC": False,
    }


def create_caravel_project(
    name: str,
    root_dir: Path,
    config: CaravelConfig | None = None,
) -> Path:
    """Generate a Caravel user_project_wrapper directory under ``root_dir``.

    Returns the project directory path.
    """
    cfg = config or CaravelConfig(project_name=name)
    cfg.project_name = name
    root = Path(root_dir) / name
    root.mkdir(parents=True, exist_ok=True)

    module = cfg.user_module_name

    # Directory skeleton
    (root / "verilog" / "rtl").mkdir(parents=True, exist_ok=True)
    (root / "openlane" / module).mkdir(parents=True, exist_ok=True)
    (root / "sdc").mkdir(parents=True, exist_ok=True)
    (root / "signoff" / "drc").mkdir(parents=True, exist_ok=True)
    (root / "signoff" / "lvs").mkdir(parents=True, exist_ok=True)
    (root / "signoff" / "antenna").mkdir(parents=True, exist_ok=True)

    # Files
    (root / "openforge.yaml").write_text(_format_openforge_yaml(cfg))
    (root / "verilog" / "rtl" / f"{module}.v").write_text(_format_verilog(module, cfg))
    (root / "verilog" / "rtl" / "user_project_wrapper.v").write_text(_format_wrapper(module))
    (root / "openlane" / module / "config.json").write_text(
        json.dumps(_openlane_config(cfg), indent=2)
    )
    (root / "sdc" / "user_proj.sdc").write_text(_format_sdc(cfg))
    (root / "README.md").write_text(_format_readme(cfg))
    (root / "signoff" / ".gitkeep").write_text("")

    return root
