"""UVM-lite protocol agent generator.

For each supported protocol we ship a single-file agent (sequence_item +
driver + monitor + sequencer wrapper) written in Verilator-friendly
SystemVerilog. The SV depends on the ``uvm_lite_pkg`` package from
``library.py`` being on the compile path.

The templates here are real, compilable code -- not lorem. They cover:
    axi4, axi4_lite, ahb, apb, axi_stream, i2c, spi, uart, wishbone
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, Field


class AgentSpec(BaseModel):
    """Specification for a generated UVM-lite agent."""

    name: str
    protocol: str
    direction: str = Field(default="master", description="master|slave|monitor")
    config: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Protocol templates. All use `{name}` as the agent/class prefix.
# ---------------------------------------------------------------------------


_HEADER = (
    "// Auto-generated by OpenForge uvm_lite (do not edit)\n"
    '`include "uvm_lite_pkg.sv"\n'
    "import uvm_lite_pkg::*;\n\n"
)


_AXI4 = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit        is_write;
  rand bit [31:0] addr;
  rand bit [31:0] data;
  rand bit [3:0]  strb;
  rand bit [7:0]  len;
  rand bit [2:0]  size;
  rand bit [1:0]  burst;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    void'(this.randomize() with { burst inside {0, 1, 2}; size inside {0, 1, 2}; });
  endfunction
  virtual function string convert2string();
    return $sformatf("AXI4 %s addr=%0h data=%0h len=%0d", is_write ? "W" : "R", addr, data, len);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    // A full AXI4 channel dance would be wired through a virtual interface.
    // Here we model the handshake timing for Verilator compile-ability.
    info("AXI4", base.convert2string());
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect();
    forever #10;
  endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv    = new("drv",  this);
    mon    = new("mon",  this);
    m_driver  = drv;
    m_monitor = mon;
  endfunction
endclass
"""
)


_AXI4_LITE = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit        is_write;
  rand bit [31:0] addr;
  rand bit [31:0] data;
  rand bit [3:0]  strb;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("AXI4L %s addr=%0h data=%0h", is_write ? "W" : "R", addr, data);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("AXI4L", base.convert2string());
    #5;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #5; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr    = new("seqr", this);
    {name}_driver  drv;
    {name}_monitor mon;
    drv = new("drv", this);
    mon = new("mon", this);
    m_driver  = drv;
    m_monitor = mon;
  endfunction
endclass
"""
)


_AHB = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit        hwrite;
  rand bit [31:0] haddr;
  rand bit [31:0] hwdata;
  rand bit [2:0]  hsize;
  rand bit [1:0]  htrans;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("AHB %s haddr=%0h hwdata=%0h", hwrite ? "W" : "R", haddr, hwdata);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("AHB", base.convert2string());
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv;
    {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_APB = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit        pwrite;
  rand bit [31:0] paddr;
  rand bit [31:0] pwdata;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("APB %s paddr=%0h pwdata=%0h", pwrite ? "W" : "R", paddr, pwdata);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("APB", base.convert2string());
    // Classic 2-cycle APB transfer.
    #10;
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv; {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_AXIS = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit [31:0] tdata;
  rand bit [3:0]  tkeep;
  rand bit        tlast;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("AXIS tdata=%0h tlast=%0b", tdata, tlast);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("AXIS", base.convert2string());
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv; {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_I2C = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit [6:0]  addr7;
  rand bit        rw;     // 0=write 1=read
  rand bit [7:0]  data;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("I2C %s addr=%0h data=%0h", rw ? "R" : "W", addr7, data);
  endfunction
endclass

// Bit-level driver: models START, 8 data bits + ACK, STOP using delays.
class {name}_driver extends uvm_driver;
  int half_period_ns = 2500;  // 100 kHz default
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("I2C", base.convert2string());
    // START + 9 bits * 2 edges + STOP
    #(half_period_ns);
    for (int i = 0; i < 9; i++) begin
      #(half_period_ns);
      #(half_period_ns);
    end
    #(half_period_ns);
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #100; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv; {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_SPI = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit [7:0] mosi;
  rand bit [7:0] miso;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("SPI mosi=%0h miso=%0h", mosi, miso);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int  half_period_ns = 50;   // 10 MHz
  bit  cpol           = 1'b0;
  bit  cpha           = 1'b0;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("SPI", base.convert2string());
    for (int i = 0; i < 8; i++) begin
      #(half_period_ns);
      #(half_period_ns);
    end
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #50; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv; {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_UART = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit [7:0] ch;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("UART ch=%0h", ch);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int baud       = 115200;
  int bit_period_ns;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
    bit_period_ns = 1_000_000_000 / baud;
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("UART", base.convert2string());
    // Start + 8 data + stop.
    for (int i = 0; i < 10; i++) #(bit_period_ns);
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #100; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv; {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_WB = (
    _HEADER
    + """\
class {name}_item extends uvm_sequence_item;
  rand bit        we;
  rand bit [31:0] adr;
  rand bit [31:0] dat;
  rand bit [3:0]  sel;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("WB %s adr=%0h dat=%0h", we ? "W" : "R", adr, dat);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("WB", base.convert2string());
    // Classic bus cycle: STB+CYC -> ACK.
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    {name}_driver  drv; {name}_monitor mon;
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_AXI4_FULL_MASTER = (
    _HEADER
    + """\
// AXI4 full master with multi-burst support (INCR/WRAP/FIXED).
class {name}_item extends uvm_sequence_item;
  rand bit        is_write;
  rand bit [31:0] addr;
  rand bit [31:0] data [];
  rand bit [7:0]  len;      // beats - 1
  rand bit [2:0]  size;     // bytes per beat = 2**size
  rand bit [1:0]  burst;    // 0=FIXED 1=INCR 2=WRAP
  rand bit [3:0]  id;
  rand bit [2:0]  prot;
  rand bit [3:0]  cache;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    void'(this.randomize() with {
      burst inside {0, 1, 2};
      size  inside {0, 1, 2};
      len   inside {[0:15]};
    });
    data = new[len + 1];
    foreach (data[i]) data[i] = $urandom();
  endfunction
  virtual function string convert2string();
    return $sformatf("AXI4M id=%0d %s addr=%0h len=%0d burst=%0d", id,
                     is_write ? "W" : "R", addr, len, burst);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_write(uvm_sequence_item base);
    // AW channel handshake.
    #10;
    // W channel: len+1 beats, last beat asserts WLAST.
    for (int i = 0; i < 16; i++) #10;
    // B channel response.
    #10;
  endtask
  virtual task drive_read(uvm_sequence_item base);
    // AR channel handshake, then R channel beats with RLAST.
    #10;
    for (int i = 0; i < 16; i++) #10;
  endtask
  virtual task drive_item(uvm_sequence_item base);
    info("AXI4M", base.convert2string());
    drive_write(base);
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect();
    forever begin
      #10;
      // sample AW/W/B/AR/R handshakes here.
    end
  endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv    = new("drv",  this);
    mon    = new("mon",  this);
    m_driver  = drv;
    m_monitor = mon;
  endfunction
endclass
"""
)


_AXI4_FULL_SLAVE = (
    _HEADER
    + """\
// AXI4 full slave responder with sparse memory model.
class {name}_item extends uvm_sequence_item;
  rand bit [31:0] addr;
  rand bit [31:0] data;
  rand bit [1:0]  resp; // 0=OKAY, 2=SLVERR
  rand bit [3:0]  id;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("AXI4S id=%0d addr=%0h data=%0h resp=%0d", id, addr, data, resp);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  bit [31:0] mem [bit[31:0]];
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("AXI4S", base.convert2string());
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_AXI_CHI = (
    _HEADER
    + """\
// ARM CHI-lite (read-only ports, REQ/RSP/DAT channels sketched).
class {name}_item extends uvm_sequence_item;
  rand bit [5:0]  opcode;
  rand bit [10:0] txnid;
  rand bit [6:0]  srcid;
  rand bit [6:0]  tgtid;
  rand bit [43:0] addr;
  rand bit [511:0] data;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("CHI op=%0h txnid=%0d addr=%0h", opcode, txnid, addr);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("CHI", base.convert2string());
    // REQ handshake.
    #10;
    // RSP/DAT coming back.
    #10;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_JTAG = (
    _HEADER
    + """\
// JTAG TAP controller agent: shifts IR/DR via TMS sequence.
class {name}_item extends uvm_sequence_item;
  rand bit        is_ir;
  rand bit [31:0] shift_data;
  rand int        shift_len;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    void'(this.randomize() with { shift_len inside {[1:32]}; });
  endfunction
  virtual function string convert2string();
    return $sformatf("JTAG %s len=%0d data=%0h",
                     is_ir ? "IR" : "DR", shift_len, shift_data);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int tck_half_ns = 50;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task tms_sequence(int n);
    for (int i = 0; i < n; i++) begin
      #(tck_half_ns); #(tck_half_ns);
    end
  endtask
  virtual task drive_item(uvm_sequence_item base);
    info("JTAG", base.convert2string());
    // Run-Test/Idle -> Select-DR/IR -> Capture -> Shift -> Exit -> Update -> Idle
    tms_sequence(4);        // enter shift state
    tms_sequence(32);       // shift data
    tms_sequence(2);        // update + idle
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #100; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_CAN = (
    _HEADER
    + """\
// CAN 2.0B frame driver. Real bit stuffing is modelled at the timing level.
class {name}_item extends uvm_sequence_item;
  rand bit [28:0] identifier;
  rand bit        ide;     // 0=standard 1=extended
  rand bit        rtr;
  rand bit [3:0]  dlc;
  rand bit [7:0]  payload [8];
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    void'(this.randomize() with { dlc inside {[0:8]}; });
  endfunction
  virtual function string convert2string();
    return $sformatf("CAN id=%0h ide=%0b dlc=%0d", identifier, ide, dlc);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int bit_time_ns = 1000; // 1 Mbps
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_bit(bit b);
    #(bit_time_ns);
  endtask
  virtual task drive_item(uvm_sequence_item base);
    info("CAN", base.convert2string());
    // SOF + arbitration + control + data + CRC + ACK + EOF + IFS
    // With bit stuffing every 5 identical bits adds 1.
    for (int i = 0; i < 128; i++) drive_bit(1'b0);
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #1000; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_ETH_GMII = (
    _HEADER
    + """\
// Ethernet MAC GMII (8-bit @ 125 MHz) agent.
class {name}_item extends uvm_sequence_item;
  rand bit [47:0] dst_mac;
  rand bit [47:0] src_mac;
  rand bit [15:0] ethertype;
  rand bit [7:0]  payload [];
  rand bit [31:0] fcs;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    int plen;
    plen = ($urandom_range(46, 1500));
    payload = new[plen];
    foreach (payload[i]) payload[i] = $urandom();
    void'(this.randomize());
  endfunction
  virtual function string convert2string();
    return $sformatf("ETH dst=%0h src=%0h type=%0h len=%0d",
                     dst_mac, src_mac, ethertype, payload.size());
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("ETH", base.convert2string());
    // 7 preamble + 1 SFD + dst(6) + src(6) + type(2) + payload + fcs(4)
    for (int i = 0; i < 64; i++) #8;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #8; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_PCIE_PIPE = (
    _HEADER
    + """\
// PCIe PIPE 4.x agent (parallel PHY interface).
class {name}_item extends uvm_sequence_item;
  rand bit [31:0] tx_data;
  rand bit [3:0]  tx_datak;
  rand bit [1:0]  rate;
  rand bit        phy_status;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("PIPE tx=%0h k=%0h rate=%0d", tx_data, tx_datak, rate);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("PIPE", base.convert2string());
    #4; // 250 MHz PCLK
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #4; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_DDR3_DFI = (
    _HEADER
    + """\
// DDR3 PHY DFI 4.0 agent.
class {name}_item extends uvm_sequence_item;
  rand bit [15:0] dfi_address;
  rand bit [2:0]  dfi_bank;
  rand bit        dfi_cas_n;
  rand bit        dfi_ras_n;
  rand bit        dfi_we_n;
  rand bit [63:0] dfi_wrdata;
  rand bit [7:0]  dfi_wrdata_mask;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("DFI a=%0h b=%0h cas=%0b ras=%0b we=%0b",
                     dfi_address, dfi_bank, dfi_cas_n, dfi_ras_n, dfi_we_n);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("DFI", base.convert2string());
    #5;
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #5; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_USB2_ULPI = (
    _HEADER
    + """\
// USB 2.0 ULPI agent (8-bit parallel bus to USB PHY).
class {name}_item extends uvm_sequence_item;
  rand bit [7:0] data;
  rand bit        dir;
  rand bit        stp;
  rand bit        nxt;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize(); void'(this.randomize()); endfunction
  virtual function string convert2string();
    return $sformatf("ULPI data=%0h dir=%0b nxt=%0b stp=%0b", data, dir, nxt, stp);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("ULPI", base.convert2string());
    #17; // 60 MHz
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #17; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_MIPI_DSI = (
    _HEADER
    + """\
// MIPI DSI controller agent (HS/LP modes, 1-4 data lanes).
class {name}_item extends uvm_sequence_item;
  rand bit [7:0]  data_id;
  rand bit [15:0] word_count;
  rand bit [7:0]  payload [];
  rand bit [1:0]  vc;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    int wc;
    wc = $urandom_range(1, 64);
    payload = new[wc];
    foreach (payload[i]) payload[i] = $urandom();
    void'(this.randomize());
  endfunction
  virtual function string convert2string();
    return $sformatf("DSI dt=%0h vc=%0d wc=%0d", data_id, vc, payload.size());
  endfunction
endclass

class {name}_driver extends uvm_driver;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("DSI", base.convert2string());
    #2; // HS lane @ 500 Mbps ~= 2 ns/bit
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #2; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_I3C = (
    _HEADER
    + """\
// I3C master (SDR mode). Backwards-compatible with I2C addressing.
class {name}_item extends uvm_sequence_item;
  rand bit [6:0] dyn_addr;
  rand bit       is_ccc;   // common command code
  rand bit [7:0] ccc;
  rand bit [7:0] data [];
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    int n;
    n = $urandom_range(1, 16);
    data = new[n];
    foreach (data[i]) data[i] = $urandom();
    void'(this.randomize());
  endfunction
  virtual function string convert2string();
    return $sformatf("I3C addr=%0h ccc=%0b cmd=%0h bytes=%0d",
                     dyn_addr, is_ccc, ccc, data.size());
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int scl_half_ns = 40; // 12.5 MHz SDR
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("I3C", base.convert2string());
    for (int i = 0; i < 18; i++) begin
      #(scl_half_ns); #(scl_half_ns);
    end
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #80; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_QSPI = (
    _HEADER
    + """\
// Quad SPI master for flash: 1/2/4 bit, SDR.
class {name}_item extends uvm_sequence_item;
  rand bit [7:0]  cmd;
  rand bit [31:0] addr;
  rand bit [1:0]  io_width; // 0=x1 1=x2 2=x4
  rand bit [7:0]  data [];
  rand int        dummy_cycles;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    int n;
    n = $urandom_range(1, 32);
    data = new[n];
    foreach (data[i]) data[i] = $urandom();
    void'(this.randomize() with { dummy_cycles inside {[0:8]}; io_width inside {0,1,2}; });
  endfunction
  virtual function string convert2string();
    return $sformatf("QSPI cmd=%0h addr=%0h iow=%0d bytes=%0d",
                     cmd, addr, io_width, data.size());
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int sck_half_ns = 5; // 100 MHz
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("QSPI", base.convert2string());
    // CMD(8) + ADDR(24/32) + DUMMY + DATA
    for (int i = 0; i < 64; i++) begin
      #(sck_half_ns); #(sck_half_ns);
    end
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_CLK_DIV = (
    _HEADER
    + """\
// Reference clock divider agent: emits a divided clock using $time delays.
class {name}_item extends uvm_sequence_item;
  rand int divisor;
  rand int cycles;
  function new(string name = "{name}_item"); super.new(name); endfunction
  virtual function void do_randomize();
    void'(this.randomize() with { divisor inside {[1:64]}; cycles inside {[1:1024]}; });
  endfunction
  virtual function string convert2string();
    return $sformatf("CLKDIV div=%0d cycles=%0d", divisor, cycles);
  endfunction
endclass

class {name}_driver extends uvm_driver;
  int ref_half_ns = 5;
  function new(string name = "{name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item base);
    info("CLKDIV", base.convert2string());
    for (int i = 0; i < 64; i++) begin
      #(ref_half_ns); #(ref_half_ns);
    end
  endtask
endclass

class {name}_monitor extends uvm_monitor;
  function new(string name = "{name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect(); forever #10; endtask
endclass

class {name}_agent extends uvm_agent;
  {name}_driver  drv;
  {name}_monitor mon;
  function new(string name = "{name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr = new("seqr", this);
    drv = new("drv", this); mon = new("mon", this);
    m_driver = drv; m_monitor = mon;
  endfunction
endclass
"""
)


_TEMPLATES: dict[str, str] = {
    "axi4": _AXI4,
    "axi4_lite": _AXI4_LITE,
    "ahb": _AHB,
    "apb": _APB,
    "axi_stream": _AXIS,
    "i2c": _I2C,
    "spi": _SPI,
    "uart": _UART,
    "wishbone": _WB,
    "axi4_full_master": _AXI4_FULL_MASTER,
    "axi4_full_slave": _AXI4_FULL_SLAVE,
    "axi_chi": _AXI_CHI,
    "jtag": _JTAG,
    "can": _CAN,
    "ethernet_gmii": _ETH_GMII,
    "pcie_pipe": _PCIE_PIPE,
    "ddr3_dfi": _DDR3_DFI,
    "usb2_ulpi": _USB2_ULPI,
    "mipi_dsi": _MIPI_DSI,
    "i3c": _I3C,
    "qspi": _QSPI,
    "clock_divider": _CLK_DIV,
}


def _render(protocol: str, spec_or_name) -> str:
    name = spec_or_name.name if isinstance(spec_or_name, AgentSpec) else str(spec_or_name)
    return _TEMPLATES[protocol].replace("{name}", name)


def generate_axi4_full_master(spec) -> str:
    """Return AXI4 full master agent SV for ``spec``."""
    return _render("axi4_full_master", spec)


def generate_axi4_full_slave(spec) -> str:
    """Return AXI4 full slave agent SV for ``spec``."""
    return _render("axi4_full_slave", spec)


def generate_axi_chi(spec) -> str:
    """Return CHI-lite agent SV for ``spec``."""
    return _render("axi_chi", spec)


def generate_jtag_tap(spec) -> str:
    """Return JTAG TAP agent SV for ``spec``."""
    return _render("jtag", spec)


def generate_can_bus(spec) -> str:
    """Return CAN 2.0B agent SV for ``spec``."""
    return _render("can", spec)


def generate_ethernet_mac(spec) -> str:
    """Return Ethernet GMII agent SV for ``spec``."""
    return _render("ethernet_gmii", spec)


def generate_pcie_phy(spec) -> str:
    """Return PCIe PIPE agent SV for ``spec``."""
    return _render("pcie_pipe", spec)


def generate_ddr3_phy(spec) -> str:
    """Return DDR3 DFI agent SV for ``spec``."""
    return _render("ddr3_dfi", spec)


def generate_usb2_ulpi(spec) -> str:
    """Return USB 2.0 ULPI agent SV for ``spec``."""
    return _render("usb2_ulpi", spec)


def generate_mipi_dsi(spec) -> str:
    """Return MIPI DSI agent SV for ``spec``."""
    return _render("mipi_dsi", spec)


def generate_i3c_master(spec) -> str:
    """Return I3C master agent SV for ``spec``."""
    return _render("i3c", spec)


def generate_qspi_master(spec) -> str:
    """Return Quad SPI master agent SV for ``spec``."""
    return _render("qspi", spec)


def generate_clock_divider(spec) -> str:
    """Return reference clock divider agent SV for ``spec``."""
    return _render("clock_divider", spec)


def list_protocols() -> list[str]:
    """Return the protocol identifiers we can emit agents for."""
    return sorted(_TEMPLATES.keys())


def get_protocol_template(protocol: str) -> str:
    """Return the raw template string for ``protocol``.

    Raises:
        KeyError: if the protocol is not known.
    """
    if protocol not in _TEMPLATES:
        raise KeyError(f"unknown protocol: {protocol!r}")
    return _TEMPLATES[protocol]


def generate_agent(spec: AgentSpec, output_dir: Path) -> Path:
    """Render an agent file for ``spec`` into ``output_dir``.

    The generated file is ``<name>_agent.sv`` and depends on
    ``uvm_lite_pkg.sv`` being compiled alongside it.
    """
    template = get_protocol_template(spec.protocol)
    # str.format would choke on the many SV braces, so do a plain replace.
    body = template.replace("{name}", spec.name)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / f"{spec.name}_agent.sv"
    out.write_text(body, encoding="utf-8")
    return out
