"""UVM-lite SystemVerilog library and test skeleton generator.

The SV in this module is intentionally a small, synthesizable-by-Verilator
subset of UVM: class-based, no UVM macros, no virtual interface arrays, no
$cast on parameterized bases. It gives users the *structure* of UVM (phases,
env/agent/driver/monitor/sequencer/sequence_item) without pulling in the full
UVM library, which Verilator cannot compile.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Base package -- dropped as-is into the user's tb directory
# ---------------------------------------------------------------------------

UVM_LITE_BASE: str = r"""// =======================================================================
// uvm_lite_pkg.sv
// Verilator-friendly UVM-lite base classes. Generated by OpenForge.
// =======================================================================
`ifndef UVM_LITE_PKG_SV
`define UVM_LITE_PKG_SV

package uvm_lite_pkg;

  // -------------------------------------------------------------------
  // Severity / verbosity
  // -------------------------------------------------------------------
  typedef enum int {
    UVM_LITE_INFO    = 0,
    UVM_LITE_WARNING = 1,
    UVM_LITE_ERROR   = 2,
    UVM_LITE_FATAL   = 3
  } uvm_lite_severity_e;

  // Global counters (package-scoped)
  int uvm_lite_info_count    = 0;
  int uvm_lite_warning_count = 0;
  int uvm_lite_error_count   = 0;
  int uvm_lite_fatal_count   = 0;

  function automatic void uvm_lite_report(
      input uvm_lite_severity_e sev,
      input string              id,
      input string              msg
  );
    string tag;
    case (sev)
      UVM_LITE_INFO:    begin tag = "UVM_INFO";    uvm_lite_info_count++;    end
      UVM_LITE_WARNING: begin tag = "UVM_WARNING"; uvm_lite_warning_count++; end
      UVM_LITE_ERROR:   begin tag = "UVM_ERROR";   uvm_lite_error_count++;   end
      UVM_LITE_FATAL:   begin tag = "UVM_FATAL";   uvm_lite_fatal_count++;   end
      default:          tag = "UVM_INFO";
    endcase
    $display("[%0t] %s [%s] %s", $time, tag, id, msg);
    if (sev == UVM_LITE_FATAL) $finish;
  endfunction

  // -------------------------------------------------------------------
  // uvm_object -- the root of the class tree
  // -------------------------------------------------------------------
  class uvm_object;
    string m_name;
    function new(string name = "");
      m_name = name;
    endfunction
    virtual function string get_name();
      return m_name;
    endfunction
    virtual function void set_name(string n);
      m_name = n;
    endfunction
    virtual function string convert2string();
      return m_name;
    endfunction
  endclass

  // -------------------------------------------------------------------
  // uvm_component -- supports a build/connect/run/report phase cycle
  // -------------------------------------------------------------------
  class uvm_component extends uvm_object;
    uvm_component m_parent;
    uvm_component m_children[$];

    function new(string name = "", uvm_component parent = null);
      super.new(name);
      m_parent = parent;
      if (parent != null) parent.m_children.push_back(this);
    endfunction

    virtual function void build_phase();
      foreach (m_children[i]) m_children[i].build_phase();
    endfunction

    virtual function void connect_phase();
      foreach (m_children[i]) m_children[i].connect_phase();
    endfunction

    virtual task run_phase();
      // Children are launched in parallel by the env/test; default is a no-op.
    endtask

    virtual function void report_phase();
      foreach (m_children[i]) m_children[i].report_phase();
    endfunction

    function void info(string id, string msg);
      uvm_lite_report(UVM_LITE_INFO, id, msg);
    endfunction
    function void warning(string id, string msg);
      uvm_lite_report(UVM_LITE_WARNING, id, msg);
    endfunction
    function void error(string id, string msg);
      uvm_lite_report(UVM_LITE_ERROR, id, msg);
    endfunction
    function void fatal(string id, string msg);
      uvm_lite_report(UVM_LITE_FATAL, id, msg);
    endfunction
  endclass

  // -------------------------------------------------------------------
  // uvm_sequence_item -- transaction payload base
  // -------------------------------------------------------------------
  class uvm_sequence_item extends uvm_object;
    int unsigned m_id;
    static int unsigned s_next_id = 0;

    function new(string name = "");
      super.new(name);
      m_id = s_next_id++;
    endfunction

    // Subclasses override to randomize protocol-specific fields.
    virtual function void do_randomize();
    endfunction

    virtual function string convert2string();
      return $sformatf("%s(id=%0d)", m_name, m_id);
    endfunction
  endclass

  // -------------------------------------------------------------------
  // A minimal item mailbox -- plays the role of uvm_tlm_fifo / seq_item_port
  // -------------------------------------------------------------------
  class uvm_lite_item_mbx;
    mailbox #(uvm_sequence_item) m_mbx;

    function new();
      m_mbx = new();  // unbounded
    endfunction

    task put(uvm_sequence_item item);
      m_mbx.put(item);
    endtask

    task get(output uvm_sequence_item item);
      m_mbx.get(item);
    endtask

    function int num();
      return m_mbx.num();
    endfunction
  endclass

  // -------------------------------------------------------------------
  // uvm_sequence -- generates sequence_items into a mailbox
  // -------------------------------------------------------------------
  class uvm_sequence extends uvm_object;
    uvm_lite_item_mbx m_port;

    function new(string name = "");
      super.new(name);
    endfunction

    virtual task body();
      // Subclasses override to create items and call `start_item`/`finish_item`.
    endtask

    task start_item(uvm_sequence_item item);
      // Hook for pre-transmit randomization.
      item.do_randomize();
    endtask

    task finish_item(uvm_sequence_item item);
      if (m_port == null) begin
        uvm_lite_report(UVM_LITE_ERROR, "SEQ", "sequence port not connected");
        return;
      end
      m_port.put(item);
    endtask
  endclass

  // -------------------------------------------------------------------
  // uvm_sequencer -- owns the item mailbox, arbitrates between sequences
  // -------------------------------------------------------------------
  class uvm_sequencer extends uvm_component;
    uvm_lite_item_mbx m_port;

    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
      m_port = new();
    endfunction

    task get_next_item(output uvm_sequence_item item);
      m_port.get(item);
    endtask
  endclass

  // -------------------------------------------------------------------
  // uvm_driver -- pulls items from its sequencer, drives pins via
  //               protocol-specific subclass
  // -------------------------------------------------------------------
  class uvm_driver extends uvm_component;
    uvm_sequencer m_seqr;

    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
    endfunction

    virtual task drive_item(uvm_sequence_item item);
      // Override in protocol subclass.
    endtask

    virtual task run_phase();
      uvm_sequence_item item;
      forever begin
        if (m_seqr == null) begin
          #1;
          continue;
        end
        m_seqr.get_next_item(item);
        drive_item(item);
      end
    endtask
  endclass

  // -------------------------------------------------------------------
  // uvm_monitor -- samples pins into sequence_items
  // -------------------------------------------------------------------
  class uvm_monitor extends uvm_component;
    uvm_lite_item_mbx m_ap;  // analysis port

    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
      m_ap = new();
    endfunction

    virtual task collect();
      // Override in protocol subclass.
    endtask

    virtual task run_phase();
      collect();
    endtask
  endclass

  // -------------------------------------------------------------------
  // uvm_scoreboard -- collects monitor outputs, compares vs reference
  // -------------------------------------------------------------------
  class uvm_scoreboard extends uvm_component;
    int m_expected;
    int m_matched;
    int m_mismatched;

    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
      m_expected   = 0;
      m_matched    = 0;
      m_mismatched = 0;
    endfunction

    virtual function void check(uvm_sequence_item exp, uvm_sequence_item act);
      if (exp.convert2string() == act.convert2string()) m_matched++;
      else                                              m_mismatched++;
    endfunction

    virtual function void report_phase();
      info("SCB", $sformatf("matched=%0d mismatched=%0d", m_matched, m_mismatched));
      super.report_phase();
    endfunction
  endclass

  // -------------------------------------------------------------------
  // uvm_agent -- groups driver + monitor + sequencer
  // -------------------------------------------------------------------
  class uvm_agent extends uvm_component;
    uvm_driver    m_driver;
    uvm_monitor   m_monitor;
    uvm_sequencer m_seqr;
    bit           m_is_active;

    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
      m_is_active = 1'b1;
    endfunction

    virtual function void connect_phase();
      if (m_is_active && (m_driver != null) && (m_seqr != null)) begin
        m_driver.m_seqr = m_seqr;
      end
      super.connect_phase();
    endfunction
  endclass

  // -------------------------------------------------------------------
  // uvm_env -- container for agents + scoreboards
  // -------------------------------------------------------------------
  class uvm_env extends uvm_component;
    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
    endfunction
  endclass

  // -------------------------------------------------------------------
  // uvm_test -- top-level user entry point
  // -------------------------------------------------------------------
  class uvm_test extends uvm_component;
    function new(string name = "", uvm_component parent = null);
      super.new(name, parent);
    endfunction

    virtual task main_phase();
      // Override with sequence starts.
    endtask

    virtual task run_phase();
      build_phase();
      connect_phase();
      main_phase();
      report_phase();
      info("TEST", $sformatf(
          "done: info=%0d warn=%0d err=%0d fatal=%0d",
          uvm_lite_info_count,
          uvm_lite_warning_count,
          uvm_lite_error_count,
          uvm_lite_fatal_count));
    endtask
  endclass

endpackage : uvm_lite_pkg

`endif  // UVM_LITE_PKG_SV
"""


# ---------------------------------------------------------------------------
# A parametric agent template (one generic example used as a fallback when
# the requested protocol doesn't have a built-in emitter).
# ---------------------------------------------------------------------------

UVM_LITE_AGENT_TEMPLATE: str = r"""// =======================================================================
// {agent_name}_agent.sv -- generic placeholder agent
// =======================================================================
`include "uvm_lite_pkg.sv"
import uvm_lite_pkg::*;

class {agent_name}_item extends uvm_sequence_item;
  rand bit [31:0] data;
  function new(string name = "{agent_name}_item");
    super.new(name);
  endfunction
  virtual function void do_randomize();
    void'(this.randomize());
  endfunction
endclass

class {agent_name}_driver extends uvm_driver;
  function new(string name = "{agent_name}_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task drive_item(uvm_sequence_item item);
    info("DRV", item.convert2string());
    #10;
  endtask
endclass

class {agent_name}_monitor extends uvm_monitor;
  function new(string name = "{agent_name}_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction
  virtual task collect();
    forever #10;
  endtask
endclass

class {agent_name}_agent extends uvm_agent;
  function new(string name = "{agent_name}_agent", uvm_component parent = null);
    super.new(name, parent);
    m_seqr    = new("seqr",    this);
    m_driver  = new("driver",  this);
    m_monitor = new("monitor", this);
    {agent_name}_driver drv;
    drv = new("driver", this);
    m_driver = drv;
  endfunction
endclass
"""


# ---------------------------------------------------------------------------
# File emitters
# ---------------------------------------------------------------------------


def write_uvm_lite_library(target_dir: Path) -> Path:
    """Drop the uvm_lite_pkg.sv into ``target_dir``.

    Returns the absolute path to the written file.
    """
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    out = target_dir / "uvm_lite_pkg.sv"
    out.write_text(UVM_LITE_BASE, encoding="utf-8")
    return out


def _test_file(test_name: str, dut_module: str, agents: list[str]) -> str:
    agent_news = (
        "\n".join(f'      m_{a} = new("{a}", this);' for a in agents) or "      // no agents"
    )
    agent_decls = "\n".join(f"  {a}_pkg::{a}_agent m_{a};" for a in agents) or "  // no agents"
    return (
        "// Auto-generated by OpenForge uvm_lite\n"
        '`include "uvm_lite_pkg.sv"\n'
        "import uvm_lite_pkg::*;\n\n"
        f"class {test_name}_env extends uvm_env;\n"
        f"{agent_decls}\n"
        f'  function new(string name = "{test_name}_env", uvm_component parent = null);\n'
        "    super.new(name, parent);\n"
        f"{agent_news}\n"
        "  endfunction\n"
        "endclass\n\n"
        f"class {test_name}_test extends uvm_test;\n"
        f"  {test_name}_env m_env;\n"
        f'  function new(string name = "{test_name}_test", uvm_component parent = null);\n'
        "    super.new(name, parent);\n"
        f'    m_env = new("env", this);\n'
        "  endfunction\n"
        "  virtual task main_phase();\n"
        f'    info("TEST", "running {test_name} against {dut_module}");\n'
        "    #1000;\n"
        "  endtask\n"
        "endclass\n"
    )


def _tb_top(test_name: str, dut_module: str) -> str:
    return (
        "// Auto-generated testbench top by OpenForge uvm_lite\n"
        "`timescale 1ns/1ps\n"
        f'`include "{test_name}_test.sv"\n'
        f"module tb_{test_name};\n"
        "  logic clk = 0;\n"
        "  logic rst_n = 0;\n"
        "  always #5 clk = ~clk;\n\n"
        f"  // DUT instantiation stub -- wire up ports manually.\n"
        f"  // {dut_module} dut(.clk(clk), .rst_n(rst_n));\n\n"
        "  initial begin\n"
        "    rst_n = 0;\n"
        "    #20 rst_n = 1;\n"
        "  end\n\n"
        "  initial begin\n"
        f"    {test_name}_test t;\n"
        f'    t = new("t");\n'
        "    t.run_phase();\n"
        "    $finish;\n"
        "  end\n"
        "endmodule\n"
    )


def _seq_file(test_name: str) -> str:
    return (
        "// Auto-generated sequences\n"
        '`include "uvm_lite_pkg.sv"\n'
        "import uvm_lite_pkg::*;\n\n"
        f"class {test_name}_base_seq extends uvm_sequence;\n"
        f'  function new(string name = "{test_name}_base_seq");\n'
        "    super.new(name);\n"
        "  endfunction\n"
        "  virtual task body();\n"
        "    uvm_sequence_item it;\n"
        "    repeat (16) begin\n"
        '      it = new("it");\n'
        "      start_item(it);\n"
        "      finish_item(it);\n"
        "    end\n"
        "  endtask\n"
        "endclass\n"
    )


def _verilator_cmd(test_name: str) -> str:
    return (
        "#!/bin/sh\n"
        f"# Build tb_{test_name} with Verilator 5.x\n"
        "verilator --binary --sv -Wno-fatal \\\n"
        "    uvm_lite_pkg.sv \\\n"
        f"    {test_name}_seqs.sv \\\n"
        f"    {test_name}_test.sv \\\n"
        f"    tb_{test_name}.sv \\\n"
        f"    --top-module tb_{test_name}\n"
        f"./obj_dir/Vtb_{test_name}\n"
    )


def generate_test_skeleton(
    test_name: str,
    dut_module: str,
    agents: list[str],
    target_dir: Path,
) -> dict[str, Path]:
    """Create a full UVM-lite test skeleton under ``target_dir``.

    Produces (at minimum):
      - uvm_lite_pkg.sv        -- base package
      - <test_name>_test.sv    -- env + test class
      - <test_name>_seqs.sv    -- base sequence
      - tb_<test_name>.sv      -- tb top
      - run_<test_name>.sh     -- verilator build/run

    Returns a dict keyed by ``pkg``, ``test``, ``seqs``, ``tb``, ``run``.
    """
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    out: dict[str, Path] = {}
    out["pkg"] = write_uvm_lite_library(target_dir)

    test_path = target_dir / f"{test_name}_test.sv"
    test_path.write_text(_test_file(test_name, dut_module, agents), encoding="utf-8")
    out["test"] = test_path

    seq_path = target_dir / f"{test_name}_seqs.sv"
    seq_path.write_text(_seq_file(test_name), encoding="utf-8")
    out["seqs"] = seq_path

    tb_path = target_dir / f"tb_{test_name}.sv"
    tb_path.write_text(_tb_top(test_name, dut_module), encoding="utf-8")
    out["tb"] = tb_path

    run_path = target_dir / f"run_{test_name}.sh"
    run_path.write_text(_verilator_cmd(test_name), encoding="utf-8")
    out["run"] = run_path

    return out
