"""UVM-lite scoreboard library.

Ships a small SystemVerilog package with a generic scoreboard base class plus
a handful of specialised scoreboards (AXI, AXI-Stream, sparse-memory) that
compile on Verilator 5.x. Python helpers write the package to disk and emit
per-agent scoreboard stubs.
"""

from __future__ import annotations

from pathlib import Path

SCOREBOARD_BASE_SV = """\
// Auto-generated by OpenForge uvm_lite scoreboard (do not edit)
`ifndef UVM_LITE_SCOREBOARD_PKG_SV
`define UVM_LITE_SCOREBOARD_PKG_SV

`include "uvm_lite_pkg.sv"

package uvm_lite_scoreboard_pkg;
  import uvm_lite_pkg::*;

  // ------------------------------------------------------------------
  // Generic scoreboard: in-order compare of expected vs actual queues.
  // Subclasses must override the virtual compare() method.
  // ------------------------------------------------------------------
  class scoreboard #(type T = uvm_object) extends uvm_component;
    T   expected_q [$];
    T   actual_q   [$];
    int pass_count;
    int fail_count;

    function new(string name = "scoreboard", uvm_component parent = null);
      super.new(name, parent);
      pass_count = 0;
      fail_count = 0;
    endfunction

    virtual function void write_expected(T item);
      expected_q.push_back(item);
      check();
    endfunction

    virtual function void write_actual(T item);
      actual_q.push_back(item);
      check();
    endfunction

    virtual function void check();
      T exp_item;
      T act_item;
      while (expected_q.size() > 0 && actual_q.size() > 0) begin
        exp_item = expected_q.pop_front();
        act_item = actual_q.pop_front();
        if (compare(exp_item, act_item)) begin
          pass_count++;
        end else begin
          fail_count++;
          $display("[%0t] SCOREBOARD FAIL expected vs actual", $time);
        end
      end
    endfunction

    virtual function bit compare(T a, T b);
      return 1'b1;
    endfunction

    virtual function void report_phase();
      $display("[%s] SCOREBOARD pass=%0d fail=%0d leftover_exp=%0d leftover_act=%0d",
               name, pass_count, fail_count, expected_q.size(), actual_q.size());
    endfunction
  endclass

  // ------------------------------------------------------------------
  // AXI read/write scoreboard.
  // ------------------------------------------------------------------
  class axi_scoreboard extends scoreboard #(uvm_object);
    function new(string name = "axi_scoreboard", uvm_component parent = null);
      super.new(name, parent);
    endfunction

    virtual function bit compare(uvm_object a, uvm_object b);
      return (a != null && b != null);
    endfunction
  endclass

  // ------------------------------------------------------------------
  // AXI-Stream scoreboard: order preserving, tracks tlast alignment.
  // ------------------------------------------------------------------
  class axis_scoreboard extends scoreboard #(uvm_object);
    int packet_count;

    function new(string name = "axis_scoreboard", uvm_component parent = null);
      super.new(name, parent);
      packet_count = 0;
    endfunction

    virtual function bit compare(uvm_object a, uvm_object b);
      return (a != null && b != null);
    endfunction
  endclass

  // ------------------------------------------------------------------
  // Sparse memory reference model: write updates, read checks.
  // ------------------------------------------------------------------
  class memory_scoreboard extends scoreboard #(uvm_object);
    bit [31:0] mem [bit[31:0]];
    int read_hits;
    int read_misses;

    function new(string name = "memory_scoreboard", uvm_component parent = null);
      super.new(name, parent);
      read_hits   = 0;
      read_misses = 0;
    endfunction

    virtual function void write(bit [31:0] addr, bit [31:0] data);
      mem[addr] = data;
    endfunction

    virtual function bit [31:0] read(bit [31:0] addr);
      if (mem.exists(addr)) begin
        read_hits++;
        return mem[addr];
      end
      read_misses++;
      return 32'hDEAD_BEEF;
    endfunction

    virtual function bit compare_rdata(bit [31:0] addr, bit [31:0] rdata);
      if (!mem.exists(addr)) return 1'b1; // uninitialised -> accept
      return mem[addr] == rdata;
    endfunction

    virtual function void report_phase();
      $display("[%s] MEMSB hits=%0d misses=%0d entries=%0d",
               name, read_hits, read_misses, mem.num());
    endfunction
  endclass
endpackage

`endif
"""


_SCOREBOARD_STUB = """\
// Auto-generated per-agent scoreboard
`include "uvm_lite_scoreboard_pkg.sv"
import uvm_lite_scoreboard_pkg::*;

class {name}_scoreboard extends {base};
  function new(string name = "{name}_scoreboard", uvm_component parent = null);
    super.new(name, parent);
  endfunction
endclass
"""


_PROTOCOL_BASE: dict[str, str] = {
    "axi": "axi_scoreboard",
    "axi4": "axi_scoreboard",
    "axis": "axis_scoreboard",
    "axi_stream": "axis_scoreboard",
    "memory": "memory_scoreboard",
    "generic": "scoreboard #(uvm_object)",
}


def write_scoreboard_library(target_dir: Path) -> Path:
    """Drop ``uvm_lite_scoreboard_pkg.sv`` into ``target_dir``."""
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    out = target_dir / "uvm_lite_scoreboard_pkg.sv"
    out.write_text(SCOREBOARD_BASE_SV, encoding="utf-8")
    return out


def generate_scoreboard(name: str, protocol: str, target_dir: Path) -> Path:
    """Write a ``<name>_scoreboard.sv`` stub for ``protocol``.

    Raises:
        KeyError: if the protocol does not have a base class.
    """
    if protocol not in _PROTOCOL_BASE:
        raise KeyError(f"unknown scoreboard protocol: {protocol!r}")
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    base = _PROTOCOL_BASE[protocol]
    body = _SCOREBOARD_STUB.format(name=name, base=base)
    out = target_dir / f"{name}_scoreboard.sv"
    out.write_text(body, encoding="utf-8")
    return out


def list_scoreboard_protocols() -> list[str]:
    """Return known scoreboard protocol identifiers."""
    return sorted(_PROTOCOL_BASE.keys())
