"""UVM (Universal Verification Methodology) testbench scaffolding generator.

This module produces UVM 1.2 SystemVerilog source files for a given DUT
description. The generated testbench follows the canonical UVM topology:

    test -> env -> agent (sequencer + driver + monitor) -> interface -> DUT
                \\-> scoreboard

The output is intentionally vendor neutral and uses ``import uvm_pkg::*``
together with an include of ``uvm_macros.svh``. It compiles cleanly with
commercial simulators (VCS, Questa, Xcelium) and with the limited UVM
support in Verilator/Icarus when the UVM source tree is on the include
path.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable


# ---------------------------------------------------------------------------
# Port description helpers
# ---------------------------------------------------------------------------


@dataclass
class UvmPort:
    """Normalized representation of a single DUT port."""

    name: str
    direction: str = "input"  # input / output / inout
    width: int = 1

    @property
    def is_input(self) -> bool:
        return self.direction.lower() == "input"

    @property
    def is_output(self) -> bool:
        return self.direction.lower() == "output"

    @property
    def vector(self) -> str:
        if self.width <= 1:
            return ""
        return f"[{self.width - 1}:0] "

    @property
    def sv_type(self) -> str:
        if self.width <= 1:
            return "logic"
        return f"logic [{self.width - 1}:0]"


def _normalize_ports(ports: Iterable[dict]) -> list[UvmPort]:
    out: list[UvmPort] = []
    for p in ports:
        name = p.get("name") or p.get("signal")
        if not name:
            continue
        direction = (p.get("direction") or "input").lower()
        width = int(p.get("width", 1) or 1)
        out.append(UvmPort(name=name, direction=direction, width=width))
    return out


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class UvmGenerator:
    """Generate UVM testbench scaffolding for a DUT.

    Parameters
    ----------
    dut_name:
        Name of the DUT module being verified. Used as the prefix for all
        generated component class names.
    ports:
        List of port dicts with the keys ``name``, ``direction`` and
        ``width``. Direction is one of ``input``/``output``/``inout``.
    """

    HEADER = "// Generated by OpenForge UVM scaffolding\n// DO NOT EDIT BY HAND\n"

    def __init__(self, dut_name: str, ports: list[dict]) -> None:
        self.dut_name = dut_name
        self.ports: list[UvmPort] = _normalize_ports(ports)

    # ------------------------------------------------------------------
    # Convenience accessors
    # ------------------------------------------------------------------
    @property
    def cls_prefix(self) -> str:
        return self.dut_name

    @property
    def inputs(self) -> list[UvmPort]:
        return [p for p in self.ports if p.is_input]

    @property
    def outputs(self) -> list[UvmPort]:
        return [p for p in self.ports if p.is_output]

    def _has_clock(self) -> bool:
        return any(p.name in ("clk", "clock") for p in self.ports)

    def _has_reset(self) -> bool:
        return any(p.name in ("rst", "reset", "rst_n", "resetn") for p in self.ports)

    # ------------------------------------------------------------------
    # Interface
    # ------------------------------------------------------------------
    def generate_interface(self) -> str:
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {self.dut_name.upper()}_IF_SV")
        lines.append(f"`define {self.dut_name.upper()}_IF_SV")
        lines.append("")
        lines.append(f"interface {self.dut_name}_if (input logic clk);")
        for p in self.ports:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"    {p.sv_type} {p.name};")
        lines.append("")
        lines.append("    // Driver clocking block - drives DUT inputs")
        lines.append("    clocking drv_cb @(posedge clk);")
        lines.append("        default input #1step output #1ns;")
        for p in self.inputs:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"        output {p.name};")
        for p in self.outputs:
            lines.append(f"        input  {p.name};")
        lines.append("    endclocking")
        lines.append("")
        lines.append("    // Monitor clocking block - samples all signals")
        lines.append("    clocking mon_cb @(posedge clk);")
        lines.append("        default input #1step;")
        for p in self.ports:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"        input {p.name};")
        lines.append("    endclocking")
        lines.append("")
        lines.append("    modport DRV (clocking drv_cb, input clk);")
        lines.append("    modport MON (clocking mon_cb, input clk);")
        lines.append(f"endinterface : {self.dut_name}_if")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Transaction
    # ------------------------------------------------------------------
    def generate_transaction(self) -> str:
        cls = f"{self.cls_prefix}_transaction"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append("")
        lines.append(f"class {cls} extends uvm_sequence_item;")
        # Field declarations
        for p in self.ports:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"    rand {p.sv_type} {p.name};")
        lines.append("")
        lines.append(f"    `uvm_object_utils_begin({cls})")
        for p in self.ports:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"        `uvm_field_int({p.name}, UVM_ALL_ON)")
        lines.append("    `uvm_object_utils_end")
        lines.append("")
        lines.append(f'    function new(string name = "{cls}");')
        lines.append("        super.new(name);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    constraint c_default {")
        for p in self.inputs:
            if p.name in ("clk", "clock"):
                continue
            if p.name in ("rst", "reset"):
                lines.append(f"        {p.name} dist {{ 0 := 95, 1 := 5 }};")
            elif p.name in ("rst_n", "resetn"):
                lines.append(f"        {p.name} dist {{ 1 := 95, 0 := 5 }};")
        lines.append("    }")
        lines.append("")
        lines.append("    function string convert2string();")
        parts = " ".join(
            f"{p.name}=0x%0h" for p in self.ports if p.name not in ("clk", "clock")
        )
        names = ", ".join(p.name for p in self.ports if p.name not in ("clk", "clock"))
        lines.append(f'        return $sformatf("{parts}", {names});')
        lines.append("    endfunction")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Sequence
    # ------------------------------------------------------------------
    def generate_sequence(self) -> str:
        cls = f"{self.cls_prefix}_sequence"
        item = f"{self.cls_prefix}_transaction"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{item}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends uvm_sequence #({item});")
        lines.append(f"    `uvm_object_utils({cls})")
        lines.append("")
        lines.append("    rand int unsigned num_items = 32;")
        lines.append("    constraint c_num { num_items inside {[16:256]}; }")
        lines.append("")
        lines.append(f'    function new(string name = "{cls}");')
        lines.append("        super.new(name);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    virtual task body();")
        lines.append(f"        {item} tr;")
        lines.append('        `uvm_info(get_type_name(), $sformatf("Starting %0d transactions", num_items), UVM_LOW)')
        lines.append("        repeat (num_items) begin")
        lines.append(f'            tr = {item}::type_id::create("tr");')
        lines.append("            start_item(tr);")
        lines.append('            if (!tr.randomize()) `uvm_error(get_type_name(), "Randomize failed")')
        lines.append("            finish_item(tr);")
        lines.append("        end")
        lines.append("    endtask")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Driver
    # ------------------------------------------------------------------
    def generate_driver(self) -> str:
        cls = f"{self.cls_prefix}_driver"
        item = f"{self.cls_prefix}_transaction"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{item}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends uvm_driver #({item});")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append(f"    virtual {self.dut_name}_if vif;")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void build_phase(uvm_phase phase);")
        lines.append("        super.build_phase(phase);")
        lines.append(
            f'        if (!uvm_config_db#(virtual {self.dut_name}_if)::get(this, "", "vif", vif))'
        )
        lines.append('            `uvm_fatal(get_type_name(), "Virtual interface not set")')
        lines.append("    endfunction")
        lines.append("")
        lines.append("    virtual task run_phase(uvm_phase phase);")
        lines.append(f"        {item} tr;")
        lines.append("        forever begin")
        lines.append("            seq_item_port.get_next_item(tr);")
        lines.append("            drive(tr);")
        lines.append("            seq_item_port.item_done();")
        lines.append("        end")
        lines.append("    endtask")
        lines.append("")
        lines.append(f"    virtual task drive({item} tr);")
        lines.append("        @(vif.drv_cb);")
        for p in self.inputs:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"        vif.drv_cb.{p.name} <= tr.{p.name};")
        lines.append('        `uvm_info(get_type_name(), {"DRV ", tr.convert2string()}, UVM_HIGH)')
        lines.append("    endtask")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Monitor
    # ------------------------------------------------------------------
    def generate_monitor(self) -> str:
        cls = f"{self.cls_prefix}_monitor"
        item = f"{self.cls_prefix}_transaction"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{item}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends uvm_monitor;")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append(f"    virtual {self.dut_name}_if vif;")
        lines.append(f"    uvm_analysis_port #({item}) ap;")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append('        ap = new("ap", this);')
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void build_phase(uvm_phase phase);")
        lines.append("        super.build_phase(phase);")
        lines.append(
            f'        if (!uvm_config_db#(virtual {self.dut_name}_if)::get(this, "", "vif", vif))'
        )
        lines.append('            `uvm_fatal(get_type_name(), "Virtual interface not set")')
        lines.append("    endfunction")
        lines.append("")
        lines.append("    virtual task run_phase(uvm_phase phase);")
        lines.append(f"        {item} tr;")
        lines.append("        forever begin")
        lines.append("            @(vif.mon_cb);")
        lines.append(f'            tr = {item}::type_id::create("tr");')
        for p in self.ports:
            if p.name in ("clk", "clock"):
                continue
            lines.append(f"            tr.{p.name} = vif.mon_cb.{p.name};")
        lines.append("            ap.write(tr);")
        lines.append('            `uvm_info(get_type_name(), {"MON ", tr.convert2string()}, UVM_HIGH)')
        lines.append("        end")
        lines.append("    endtask")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Scoreboard
    # ------------------------------------------------------------------
    def generate_scoreboard(self) -> str:
        cls = f"{self.cls_prefix}_scoreboard"
        item = f"{self.cls_prefix}_transaction"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{item}.sv"')
        lines.append("")
        lines.append(f"`uvm_analysis_imp_decl(_actual)")
        lines.append("")
        lines.append(f"class {cls} extends uvm_scoreboard;")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append(f"    uvm_analysis_imp_actual #({item}, {cls}) actual_export;")
        lines.append("")
        lines.append("    int unsigned num_checked = 0;")
        lines.append("    int unsigned num_errors = 0;")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append('        actual_export = new("actual_export", this);')
        lines.append("    endfunction")
        lines.append("")
        lines.append(f"    virtual function void write_actual({item} tr);")
        lines.append("        num_checked++;")
        lines.append("        // TODO: implement reference model comparison")
        lines.append('        `uvm_info(get_type_name(), {"SB  ", tr.convert2string()}, UVM_HIGH)')
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void report_phase(uvm_phase phase);")
        lines.append("        `uvm_info(get_type_name(),")
        lines.append('            $sformatf("Scoreboard: checked=%0d errors=%0d", num_checked, num_errors),')
        lines.append("            UVM_LOW)")
        lines.append("    endfunction")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Agent
    # ------------------------------------------------------------------
    def generate_agent(self) -> str:
        cls = f"{self.cls_prefix}_agent"
        drv = f"{self.cls_prefix}_driver"
        mon = f"{self.cls_prefix}_monitor"
        item = f"{self.cls_prefix}_transaction"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{drv}.sv"')
        lines.append(f'`include "{mon}.sv"')
        lines.append(f'`include "{item}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends uvm_agent;")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append(f"    {drv} driver;")
        lines.append(f"    {mon} monitor;")
        lines.append(f"    uvm_sequencer #({item}) sequencer;")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void build_phase(uvm_phase phase);")
        lines.append("        super.build_phase(phase);")
        lines.append(f'        monitor = {mon}::type_id::create("monitor", this);')
        lines.append("        if (get_is_active() == UVM_ACTIVE) begin")
        lines.append(f'            driver = {drv}::type_id::create("driver", this);')
        lines.append(f'            sequencer = uvm_sequencer#({item})::type_id::create("sequencer", this);')
        lines.append("        end")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void connect_phase(uvm_phase phase);")
        lines.append("        if (get_is_active() == UVM_ACTIVE)")
        lines.append("            driver.seq_item_port.connect(sequencer.seq_item_export);")
        lines.append("    endfunction")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Environment
    # ------------------------------------------------------------------
    def generate_env(self) -> str:
        cls = f"{self.cls_prefix}_env"
        agent = f"{self.cls_prefix}_agent"
        sb = f"{self.cls_prefix}_scoreboard"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{agent}.sv"')
        lines.append(f'`include "{sb}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends uvm_env;")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append(f"    {agent} agent;")
        lines.append(f"    {sb} scoreboard;")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void build_phase(uvm_phase phase);")
        lines.append("        super.build_phase(phase);")
        lines.append(f'        agent = {agent}::type_id::create("agent", this);')
        lines.append(f'        scoreboard = {sb}::type_id::create("scoreboard", this);')
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void connect_phase(uvm_phase phase);")
        lines.append("        agent.monitor.ap.connect(scoreboard.actual_export);")
        lines.append("    endfunction")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Tests
    # ------------------------------------------------------------------
    def generate_test_base(self) -> str:
        cls = f"{self.cls_prefix}_test_base"
        env = f"{self.cls_prefix}_env"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{env}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends uvm_test;")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append(f"    {env} env;")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void build_phase(uvm_phase phase);")
        lines.append("        super.build_phase(phase);")
        lines.append(f'        env = {env}::type_id::create("env", this);')
        lines.append("    endfunction")
        lines.append("")
        lines.append("    function void end_of_elaboration_phase(uvm_phase phase);")
        lines.append("        uvm_top.print_topology();")
        lines.append("    endfunction")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    def generate_test_smoke(self) -> str:
        cls = f"{self.cls_prefix}_test_smoke"
        base = f"{self.cls_prefix}_test_base"
        seq = f"{self.cls_prefix}_sequence"
        lines: list[str] = [self.HEADER]
        lines.append(f"`ifndef {cls.upper()}_SV")
        lines.append(f"`define {cls.upper()}_SV")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{base}.sv"')
        lines.append(f'`include "{seq}.sv"')
        lines.append("")
        lines.append(f"class {cls} extends {base};")
        lines.append(f"    `uvm_component_utils({cls})")
        lines.append("")
        lines.append("    function new(string name, uvm_component parent);")
        lines.append("        super.new(name, parent);")
        lines.append("    endfunction")
        lines.append("")
        lines.append("    virtual task run_phase(uvm_phase phase);")
        lines.append(f"        {seq} seq;")
        lines.append("        phase.raise_objection(this);")
        lines.append(f'        seq = {seq}::type_id::create("seq");')
        lines.append("        seq.num_items = 32;")
        lines.append("        seq.start(env.agent.sequencer);")
        lines.append("        #1us;")
        lines.append("        phase.drop_objection(this);")
        lines.append("    endtask")
        lines.append(f"endclass : {cls}")
        lines.append("")
        lines.append("`endif")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Top
    # ------------------------------------------------------------------
    def generate_top(self) -> str:
        lines: list[str] = [self.HEADER]
        lines.append("`timescale 1ns/1ps")
        lines.append("")
        lines.append('`include "uvm_macros.svh"')
        lines.append("import uvm_pkg::*;")
        lines.append(f'`include "{self.dut_name}_if.sv"')
        lines.append(f'`include "{self.dut_name}_test_smoke.sv"')
        lines.append("")
        lines.append(f"module {self.dut_name}_tb_top;")
        lines.append("    logic clk = 0;")
        lines.append("    always #5 clk = ~clk;  // 100 MHz")
        lines.append("")
        lines.append(f"    {self.dut_name}_if dut_if(.clk(clk));")
        lines.append("")
        lines.append(f"    {self.dut_name} dut (")
        port_conns: list[str] = []
        for p in self.ports:
            if p.name in ("clk", "clock"):
                port_conns.append(f"        .{p.name}(clk)")
            else:
                port_conns.append(f"        .{p.name}(dut_if.{p.name})")
        lines.append(",\n".join(port_conns))
        lines.append("    );")
        lines.append("")
        lines.append("    initial begin")
        lines.append(
            f'        uvm_config_db#(virtual {self.dut_name}_if)::set(null, "*", "vif", dut_if);'
        )
        lines.append('        $dumpfile("dump.vcd");')
        lines.append(f"        $dumpvars(0, {self.dut_name}_tb_top);")
        lines.append(f'        run_test("{self.dut_name}_test_smoke");')
        lines.append("    end")
        lines.append("")
        lines.append("    initial begin")
        lines.append("        #1ms;")
        lines.append('        `uvm_fatal("TIMEOUT", "Simulation hit watchdog timeout")')
        lines.append("    end")
        lines.append(f"endmodule : {self.dut_name}_tb_top")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # File system orchestration
    # ------------------------------------------------------------------
    def generate_all(self, output_dir: Path) -> dict[str, Path]:
        """Generate the complete UVM testbench source tree.

        Returns a dict mapping logical component name to the path of the
        generated file on disk.
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        files: dict[str, str] = {
            "interface": self.generate_interface(),
            "transaction": self.generate_transaction(),
            "sequence": self.generate_sequence(),
            "driver": self.generate_driver(),
            "monitor": self.generate_monitor(),
            "scoreboard": self.generate_scoreboard(),
            "agent": self.generate_agent(),
            "env": self.generate_env(),
            "test_base": self.generate_test_base(),
            "test_smoke": self.generate_test_smoke(),
            "top": self.generate_top(),
        }

        suffix_map = {
            "interface": f"{self.dut_name}_if.sv",
            "transaction": f"{self.dut_name}_transaction.sv",
            "sequence": f"{self.dut_name}_sequence.sv",
            "driver": f"{self.dut_name}_driver.sv",
            "monitor": f"{self.dut_name}_monitor.sv",
            "scoreboard": f"{self.dut_name}_scoreboard.sv",
            "agent": f"{self.dut_name}_agent.sv",
            "env": f"{self.dut_name}_env.sv",
            "test_base": f"{self.dut_name}_test_base.sv",
            "test_smoke": f"{self.dut_name}_test_smoke.sv",
            "top": f"{self.dut_name}_tb_top.sv",
        }

        out: dict[str, Path] = {}
        for key, content in files.items():
            path = output_dir / suffix_map[key]
            path.write_text(content, encoding="utf-8")
            out[key] = path

        # Also drop a small filelist to make it easy for sims.
        filelist = output_dir / f"{self.dut_name}_uvm.f"
        filelist.write_text(
            "\n".join(str(p.name) for p in out.values()) + "\n",
            encoding="utf-8",
        )
        out["filelist"] = filelist
        return out
