"""openforge init -- scaffold a new OpenForge project."""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

console = Console()


class Template(StrEnum):
    crypto_accelerator = "crypto-accelerator"
    simple_counter = "simple-counter"
    empty = "empty"


# ---------------------------------------------------------------------------
# Template content generators
# ---------------------------------------------------------------------------

_OPENFORGE_YAML_TEMPLATE = """\
# OpenForge EDA project configuration
project:
  name: "{name}"
  top_module: "{name}"
  target_pdk: "sky130"

design:
  sources:
    - src/*.sv
    - src/*.v
  includes: []
  constraints:
    - constraints/timing.sdc

verification:
  simulation:
    tool: verilator
    testbenches:
      - tb/tb_{name}.sv
    coverage:
      line: true
      toggle: true

  formal:
    tool: symbiyosys
    properties: []
    depth: 100
"""

_CRYPTO_YAML_TEMPLATE = """\
# OpenForge EDA project configuration -- Crypto Accelerator
project:
  name: "{name}"
  top_module: "{name}"
  target_pdk: "sky130"

design:
  sources:
    - src/*.sv
  includes:
    - src/include/
  constraints:
    - constraints/timing.sdc

verification:
  simulation:
    tool: verilator
    testbenches:
      - tb/tb_{name}.sv
    coverage:
      line: true
      toggle: true
      fsm: true

  formal:
    tool: symbiyosys
    properties:
      - formal/crypto_properties.sv
    depth: 100

  crypto_verification:
    constant_time:
      enabled: true
      secrets:
        - secret_key
      public:
        - ciphertext

    side_channel:
      enabled: true
      power_model: hamming_distance
      tvla_threshold: 4.5
      num_traces: 10000

    fips_compliance:
      enabled: true
      level: "140-3 Level 2"
      checks:
        - key_zeroization
        - self_test_coverage

analysis:
  timing:
    tool: opensta
    clock_period: "10.0ns"
"""

_COUNTER_SV = """\
// Simple up-counter generated by OpenForge
module {name} #(
    parameter WIDTH = 8
) (
    input  logic clk,
    input  logic rst_n,
    input  logic en,
    output logic [WIDTH-1:0] count
);
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            count <= '0;
        else if (en)
            count <= count + 1;
    end
endmodule
"""

_CRYPTO_SV = """\
// AES S-Box placeholder generated by OpenForge
// TODO: Replace with full crypto-accelerator RTL
module {name} (
    input  logic        clk,
    input  logic        rst_n,
    input  logic [7:0]  data_in,
    input  logic        valid_in,
    output logic [7:0]  data_out,
    output logic        valid_out
);
    // TODO: Implement S-Box lookup / SubBytes
    assign data_out  = data_in;  // passthrough stub
    assign valid_out = valid_in;
endmodule
"""

_TB_TEMPLATE = """\
// Basic testbench for {name}
`timescale 1ns / 1ps

module tb_{name};
    logic clk = 0;
    always #5 clk = ~clk;

    logic rst_n;

    {name} dut (
        .clk   (clk),
        .rst_n (rst_n)
    );

    initial begin
        rst_n = 0;
        #20 rst_n = 1;
        #200;
        $finish;
    end
endmodule
"""


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    console.print(f"  [dim]create[/] {path}")


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


def init(
    name: str = typer.Argument(..., help="Project name (used as top-level directory)."),
    template: Template = typer.Option(
        Template.empty,
        "--template",
        "-t",
        help="Project template to scaffold from.",
    ),
) -> None:
    """Create a new OpenForge project from a template."""
    project_dir = Path.cwd() / name

    if project_dir.exists():
        console.print(f"[red]Error:[/] directory [bold]{name}[/] already exists.")
        raise typer.Exit(code=1)

    console.print(
        Panel(
            f"Creating project [bold cyan]{name}[/] with template [green]{template.value}[/]",
            title="openforge init",
        )
    )

    # Constraints directory
    (project_dir / "constraints").mkdir(parents=True, exist_ok=True)
    _write(
        project_dir / "constraints" / "timing.sdc",
        "create_clock -name clk -period 10.0 [get_ports clk]\n",
    )

    # openforge.yaml -- pick template-appropriate config
    yaml_template = (
        _CRYPTO_YAML_TEMPLATE
        if template == Template.crypto_accelerator
        else _OPENFORGE_YAML_TEMPLATE
    )
    _write(
        project_dir / "openforge.yaml",
        yaml_template.format(name=name),
    )

    # Source files based on template
    if template == Template.simple_counter:
        _write(project_dir / "src" / f"{name}.sv", _COUNTER_SV.format(name=name))
        _write(project_dir / "tb" / f"tb_{name}.sv", _TB_TEMPLATE.format(name=name))
    elif template == Template.crypto_accelerator:
        _write(project_dir / "src" / f"{name}.sv", _CRYPTO_SV.format(name=name))
        (project_dir / "src" / "include").mkdir(parents=True, exist_ok=True)
        _write(project_dir / "tb" / f"tb_{name}.sv", _TB_TEMPLATE.format(name=name))
        (project_dir / "formal").mkdir(parents=True, exist_ok=True)
        console.print(f"  [dim]create[/] {project_dir / 'formal'}/")
    else:
        # empty template -- just create directory stubs
        (project_dir / "src").mkdir(parents=True, exist_ok=True)
        console.print(f"  [dim]create[/] {project_dir / 'src'}/")
        (project_dir / "tb").mkdir(parents=True, exist_ok=True)
        console.print(f"  [dim]create[/] {project_dir / 'tb'}/")

    console.print()
    console.print(f"[bold green]Done![/] Project created at [cyan]{project_dir}[/]")
    console.print(f"  cd {name} && openforge lint")
