"""openforge project management commands -- init, open, info, validate."""

from __future__ import annotations

import json as json_mod
import sys
from enum import Enum
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

app = typer.Typer(
    name="project",
    help="Project management commands.",
    no_args_is_help=True,
)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class ProjectKind(str, Enum):
    asic = "asic"
    fpga = "fpga"
    pcb = "pcb"
    mixed = "mixed"


class TemplateName(str, Enum):
    sky130 = "sky130"
    ice40 = "ice40"
    ecp5 = "ecp5"
    gowin = "gowin"
    caravel = "caravel"
    pcb = "pcb"
    empty = "empty"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_config(project_dir: Path):
    """Load config or exit with error message."""
    from openforge.config.loader import ConfigNotFoundError, load_config

    try:
        return load_config(search_dir=project_dir)
    except (FileNotFoundError, ConfigNotFoundError):
        console.print(
            f"[red]Error:[/] no openforge.yaml found in [cyan]{project_dir}[/]. "
            "Run [bold]openforge init[/] first."
        )
        raise typer.Exit(code=1)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    console.print(f"  [dim]create[/] {path}")


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_YAML_ASIC = """\
# OpenForge EDA project configuration
project:
  name: "{name}"
  top_module: "{name}"
  target_pdk: "{pdk}"

design:
  sources:
    - rtl/*.sv
    - rtl/*.v
  includes: []
  constraints:
    - constraints/timing.sdc

verification:
  simulation:
    tool: verilator
    testbenches:
      - tb/tb_{name}.sv
    coverage:
      line: true
      toggle: true

  formal:
    tool: symbiyosys
    properties: []
    depth: 100
"""

_YAML_FPGA = """\
# OpenForge EDA project -- FPGA
project:
  name: "{name}"
  top_module: "{name}"

design:
  sources:
    - rtl/*.sv
    - rtl/*.v
  includes: []
  constraints:
    - constraints/pins.{constraint_ext}

verification:
  simulation:
    tool: icarus
    testbenches:
      - tb/tb_{name}.sv
    coverage:
      line: true
"""

_YAML_PCB = """\
# OpenForge EDA project -- PCB
project:
  name: "{name}"
  top_module: "{name}"

design:
  sources: []
  includes: []
  constraints: []
"""

_RTL_COUNTER = """\
// Simple up-counter generated by OpenForge
module {name} #(
    parameter WIDTH = 8
) (
    input  logic clk,
    input  logic rst_n,
    input  logic en,
    output logic [WIDTH-1:0] count
);
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            count <= '0;
        else if (en)
            count <= count + 1;
    end
endmodule
"""

_TB_TEMPLATE = """\
`timescale 1ns / 1ps
module tb_{name};
    logic clk = 0;
    always #5 clk = ~clk;
    logic rst_n;

    {name} dut (
        .clk   (clk),
        .rst_n (rst_n)
    );

    initial begin
        rst_n = 0;
        #20 rst_n = 1;
        #200;
        $finish;
    end
endmodule
"""

_SDC_TEMPLATE = """\
create_clock -name clk -period {period} [get_ports clk]
"""


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@app.command()
def init(
    name: str = typer.Argument(..., help="Project name."),
    kind: ProjectKind = typer.Option(
        ProjectKind.asic,
        "--kind",
        "-k",
        help="Project type.",
    ),
    template: TemplateName = typer.Option(
        TemplateName.empty,
        "--template",
        "-t",
        help="Template to scaffold.",
    ),
    from_vivado: Optional[str] = typer.Option(
        None, "--from-vivado", help="Import from a Vivado .xpr project."
    ),
    from_openlane: Optional[str] = typer.Option(
        None, "--from-openlane", help="Import from an OpenLane2 directory."
    ),
    from_kicad: Optional[str] = typer.Option(
        None, "--from-kicad", help="Import from a KiCad .kicad_pro project."
    ),
    from_quartus: Optional[str] = typer.Option(
        None, "--from-quartus", help="Import from a Quartus .qpf project."
    ),
    json_output: bool = typer.Option(False, "--json", help="Output JSON."),
) -> None:
    """Create a new OpenForge project from a template or by importing an existing project.

    Examples:
        openforge project init my_chip --kind asic --template sky130
        openforge project init my_fpga --kind fpga --template ice40
        openforge project init imported --from-vivado path/to/project.xpr
    """
    # --- Importers ---
    if from_vivado:
        from openforge.project.importers import import_xpr

        project_dir = Path.cwd() / name
        project_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[bold]Importing[/] Vivado project from [cyan]{from_vivado}[/] ...")
        import_xpr(Path(from_vivado), project_dir)
        console.print(f"[green]Done![/] Imported to [cyan]{project_dir}[/]")
        if json_output:
            console.print(json_mod.dumps({"status": "ok", "path": str(project_dir)}))
        return

    if from_openlane:
        from openforge.project.importers import import_openlane_dir

        project_dir = Path.cwd() / name
        project_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[bold]Importing[/] OpenLane directory from [cyan]{from_openlane}[/] ...")
        import_openlane_dir(Path(from_openlane), project_dir)
        console.print(f"[green]Done![/] Imported to [cyan]{project_dir}[/]")
        if json_output:
            console.print(json_mod.dumps({"status": "ok", "path": str(project_dir)}))
        return

    if from_kicad:
        from openforge.project.importers import import_kicad_project

        project_dir = Path.cwd() / name
        project_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[bold]Importing[/] KiCad project from [cyan]{from_kicad}[/] ...")
        import_kicad_project(Path(from_kicad), project_dir)
        console.print(f"[green]Done![/] Imported to [cyan]{project_dir}[/]")
        if json_output:
            console.print(json_mod.dumps({"status": "ok", "path": str(project_dir)}))
        return

    if from_quartus:
        from openforge.project.importers import import_quartus_qpf

        project_dir = Path.cwd() / name
        project_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[bold]Importing[/] Quartus project from [cyan]{from_quartus}[/] ...")
        import_quartus_qpf(Path(from_quartus), project_dir)
        console.print(f"[green]Done![/] Imported to [cyan]{project_dir}[/]")
        if json_output:
            console.print(json_mod.dumps({"status": "ok", "path": str(project_dir)}))
        return

    # --- Scaffold from template ---
    project_dir = Path.cwd() / name
    if project_dir.exists():
        console.print(f"[red]Error:[/] directory [bold]{name}[/] already exists.")
        raise typer.Exit(code=1)

    console.print(
        Panel(
            f"Creating project [bold cyan]{name}[/] (kind=[green]{kind.value}[/], template=[green]{template.value}[/])",
            title="openforge project init",
        )
    )

    # Pick the right YAML template
    pdk_map = {
        TemplateName.sky130: "sky130",
        TemplateName.caravel: "sky130",
        TemplateName.ice40: "ice40",
        TemplateName.ecp5: "ecp5",
        TemplateName.gowin: "gowin",
    }
    constraint_ext_map = {
        TemplateName.ice40: "pcf",
        TemplateName.ecp5: "lpf",
        TemplateName.gowin: "cst",
    }

    if kind in (ProjectKind.fpga,) or template in (TemplateName.ice40, TemplateName.ecp5, TemplateName.gowin):
        yaml_content = _YAML_FPGA.format(
            name=name,
            constraint_ext=constraint_ext_map.get(template, "pcf"),
        )
    elif kind == ProjectKind.pcb or template == TemplateName.pcb:
        yaml_content = _YAML_PCB.format(name=name)
    else:
        yaml_content = _YAML_ASIC.format(name=name, pdk=pdk_map.get(template, "sky130"))

    _write(project_dir / "openforge.yaml", yaml_content)

    # Common directories
    (project_dir / "constraints").mkdir(parents=True, exist_ok=True)

    if kind != ProjectKind.pcb and template != TemplateName.pcb:
        _write(project_dir / "rtl" / f"{name}.sv", _RTL_COUNTER.format(name=name))
        _write(project_dir / "tb" / f"tb_{name}.sv", _TB_TEMPLATE.format(name=name))
        _write(project_dir / "constraints" / "timing.sdc", _SDC_TEMPLATE.format(period="10.0"))
    else:
        (project_dir / "schematics").mkdir(parents=True, exist_ok=True)
        (project_dir / "layout").mkdir(parents=True, exist_ok=True)
        (project_dir / "gerbers").mkdir(parents=True, exist_ok=True)
        console.print(f"  [dim]create[/] schematics/ layout/ gerbers/")

    console.print()
    console.print(f"[bold green]Done![/] Project created at [cyan]{project_dir}[/]")
    console.print(f"  cd {name} && openforge info")

    if json_output:
        console.print(json_mod.dumps({"status": "ok", "path": str(project_dir)}))


@app.command(name="open")
def open_project(
    project_dir: str = typer.Argument(".", help="Path to the project directory."),
    json_output: bool = typer.Option(False, "--json", help="Output JSON."),
) -> None:
    """Open an existing OpenForge project and print its path.

    Example:
        openforge project open ./my_chip
    """
    path = Path(project_dir).resolve()
    config = _load_config(path)

    console.print(f"[bold green]Project:[/] {config.project.name}")
    console.print(f"  [dim]Path:[/]  {path}")
    console.print(f"  [dim]Top:[/]   {config.project.top_module}")
    console.print(f"  [dim]PDK:[/]   {config.project.target_pdk or 'none'}")

    if json_output:
        console.print(json_mod.dumps({
            "name": config.project.name,
            "path": str(path),
            "top_module": config.project.top_module,
            "target_pdk": config.project.target_pdk,
        }))


@app.command()
def info(
    project_dir: str = typer.Argument(".", help="Path to the project directory."),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Show detailed info."),
    json_output: bool = typer.Option(False, "--json", help="Output JSON."),
) -> None:
    """Show project summary including sources, constraints, and config.

    Example:
        openforge project info
    """
    path = Path(project_dir).resolve()
    config = _load_config(path)

    # Resolve sources
    source_files: list[str] = []
    for pattern in config.design.sources:
        source_files.extend(str(p) for p in path.glob(pattern))

    # Resolve constraints
    constraint_files: list[str] = []
    for pattern in config.design.constraints:
        constraint_files.extend(str(p) for p in path.glob(pattern))

    # Resolve testbenches
    tb_files: list[str] = []
    if config.simulation and config.simulation.testbenches:
        for pattern in config.simulation.testbenches:
            tb_files.extend(str(p) for p in path.glob(pattern))
    if config.verification and config.verification.simulation:
        for pattern in config.verification.simulation.testbenches:
            tb_files.extend(str(p) for p in path.glob(pattern))

    if json_output:
        console.print(json_mod.dumps({
            "name": config.project.name,
            "top_module": config.project.top_module,
            "target_pdk": config.project.target_pdk,
            "source_count": len(source_files),
            "constraint_count": len(constraint_files),
            "testbench_count": len(tb_files),
            "sources": source_files,
        }))
        return

    table = Table(title=f"Project: {config.project.name}", show_header=True, header_style="bold cyan")
    table.add_column("Property", style="bold")
    table.add_column("Value")

    table.add_row("Name", config.project.name)
    table.add_row("Top module", config.project.top_module)
    table.add_row("Target PDK", config.project.target_pdk or "none")
    table.add_row("Path", str(path))
    table.add_row("RTL sources", f"{len(source_files)} files")
    table.add_row("Constraints", f"{len(constraint_files)} files")
    table.add_row("Testbenches", f"{len(tb_files)} files")

    if config.simulation:
        table.add_row("Sim tool", config.simulation.tool.value)
    if config.formal:
        table.add_row("Formal tool", config.formal.tool.value)
    if config.timing:
        table.add_row("Clock period", f"{config.timing.clock_period} ns")

    console.print(table)

    if verbose:
        if source_files:
            console.print()
            console.print("[bold]RTL sources:[/]")
            for f in source_files:
                console.print(f"  {f}")
        if constraint_files:
            console.print()
            console.print("[bold]Constraints:[/]")
            for f in constraint_files:
                console.print(f"  {f}")
        if tb_files:
            console.print()
            console.print("[bold]Testbenches:[/]")
            for f in tb_files:
                console.print(f"  {f}")


@app.command()
def validate(
    project_dir: str = typer.Argument(".", help="Path to the project directory."),
    json_output: bool = typer.Option(False, "--json", help="Output JSON."),
) -> None:
    """Check openforge.yaml consistency -- sources exist, tools available, etc.

    Example:
        openforge project validate
    """
    path = Path(project_dir).resolve()
    config = _load_config(path)

    issues: list[dict[str, str]] = []

    # Check source files exist
    source_files: list[str] = []
    for pattern in config.design.sources:
        matched = list(path.glob(pattern))
        source_files.extend(str(p) for p in matched)
        if not matched:
            issues.append({"level": "warning", "msg": f"Source glob '{pattern}' matches no files"})

    if not source_files:
        issues.append({"level": "error", "msg": "No RTL source files found"})

    # Check constraint files
    for pattern in config.design.constraints:
        if not list(path.glob(pattern)):
            issues.append({"level": "warning", "msg": f"Constraint glob '{pattern}' matches no files"})

    # Check top module name is set
    if not config.project.top_module or config.project.top_module == "top":
        issues.append({"level": "warning", "msg": "Top module is default ('top') -- consider setting it explicitly"})

    # Check build dirs
    synth_build = path / "synth_build"
    pnr_build = path / "pnr_build"
    if synth_build.exists():
        netlist = synth_build / "netlist.v"
        if not netlist.exists():
            issues.append({"level": "info", "msg": "synth_build exists but no netlist.v found"})
    if pnr_build.exists():
        def_files = list(pnr_build.glob("*.def"))
        if not def_files:
            issues.append({"level": "info", "msg": "pnr_build exists but no DEF files found"})

    if json_output:
        result = {
            "valid": not any(i["level"] == "error" for i in issues),
            "issues": issues,
        }
        console.print(json_mod.dumps(result))
        if not result["valid"]:
            raise typer.Exit(code=1)
        return

    if not issues:
        console.print(f"[green bold]VALID[/] -- openforge.yaml at [cyan]{path}[/] is consistent.")
        return

    has_error = False
    for issue in issues:
        level = issue["level"]
        msg = issue["msg"]
        if level == "error":
            console.print(f"  [red]ERROR:[/] {msg}")
            has_error = True
        elif level == "warning":
            console.print(f"  [yellow]WARN:[/]  {msg}")
        else:
            console.print(f"  [dim]INFO:[/]  {msg}")

    if has_error:
        raise typer.Exit(code=1)
