"""Parametric IP generators returning synthesizable Verilog + BlockInstance.

Every factory returns ``(verilog_source, block_instance)``. The Verilog
is plain Verilog-2001 or limited Verilog-2005 so yosys and iverilog can
parse it. All modules are self-contained (no `include` directives).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from openforge.block_design.generator import BlockInstance, BlockPort

if TYPE_CHECKING:
    from openforge.block_design.address_map import AddressMap


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _ck_rst_ports(lo: bool = True) -> list[BlockPort]:
    rst = "aresetn" if lo else "aresetn"
    return [
        BlockPort("aclk", "input", 1),
        BlockPort(rst, "input", 1),
    ]


def _banner(mod: str, desc: str) -> str:
    return (
        "// =============================================================\n"
        f"// {mod}\n"
        f"// {desc}\n"
        "// Auto-generated by OpenForge ip.generators\n"
        "// =============================================================\n"
        "`default_nettype none\n"
    )


def _footer() -> str:
    return "endmodule\n`default_nettype wire\n"


# ---------------------------------------------------------------------------
# AXI SmartConnect NxM crossbar
# ---------------------------------------------------------------------------


def axi_smartconnect(
    num_masters: int,
    num_slaves: int,
    data_width: int = 32,
    addr_width: int = 32,
    address_map: AddressMap | None = None,
) -> tuple[str, BlockInstance]:
    """Generate an AXI4 NxM crossbar with round-robin arbitration."""

    mod = f"axi_smartconnect_{num_masters}x{num_slaves}"
    src: list[str] = [_banner(mod, f"AXI4 {num_masters}x{num_slaves} crossbar")]
    src.append(f"module {mod} #(")
    src.append(f"    parameter integer NUM_M    = {num_masters},")
    src.append(f"    parameter integer NUM_S    = {num_slaves},")
    src.append(f"    parameter integer DW       = {data_width},")
    src.append(f"    parameter integer AW       = {addr_width}")
    src.append(") (")
    src.append("    input  wire                 aclk,")
    src.append("    input  wire                 aresetn,")
    # master side (slave ports in crossbar)
    for i in range(num_masters):
        src.append(f"    // ---- slave port {i} (connects to master {i}) ----")
        src.append(f"    input  wire [AW-1:0]   s{i:02d}_awaddr,")
        src.append(f"    input  wire            s{i:02d}_awvalid,")
        src.append(f"    output wire            s{i:02d}_awready,")
        src.append(f"    input  wire [DW-1:0]   s{i:02d}_wdata,")
        src.append(f"    input  wire [DW/8-1:0] s{i:02d}_wstrb,")
        src.append(f"    input  wire            s{i:02d}_wlast,")
        src.append(f"    input  wire            s{i:02d}_wvalid,")
        src.append(f"    output wire            s{i:02d}_wready,")
        src.append(f"    output wire [1:0]      s{i:02d}_bresp,")
        src.append(f"    output wire            s{i:02d}_bvalid,")
        src.append(f"    input  wire            s{i:02d}_bready,")
        src.append(f"    input  wire [AW-1:0]   s{i:02d}_araddr,")
        src.append(f"    input  wire            s{i:02d}_arvalid,")
        src.append(f"    output wire            s{i:02d}_arready,")
        src.append(f"    output wire [DW-1:0]   s{i:02d}_rdata,")
        src.append(f"    output wire [1:0]      s{i:02d}_rresp,")
        src.append(f"    output wire            s{i:02d}_rlast,")
        src.append(f"    output wire            s{i:02d}_rvalid,")
        src.append(f"    input  wire            s{i:02d}_rready,")
    # slave side (master ports in crossbar)
    for j in range(num_slaves):
        last = j == num_slaves - 1
        comma = "" if last else ","
        src.append(f"    // ---- master port {j} (connects to slave {j}) ----")
        src.append(f"    output wire [AW-1:0]   m{j:02d}_awaddr,")
        src.append(f"    output wire            m{j:02d}_awvalid,")
        src.append(f"    input  wire            m{j:02d}_awready,")
        src.append(f"    output wire [DW-1:0]   m{j:02d}_wdata,")
        src.append(f"    output wire [DW/8-1:0] m{j:02d}_wstrb,")
        src.append(f"    output wire            m{j:02d}_wlast,")
        src.append(f"    output wire            m{j:02d}_wvalid,")
        src.append(f"    input  wire            m{j:02d}_wready,")
        src.append(f"    input  wire [1:0]      m{j:02d}_bresp,")
        src.append(f"    input  wire            m{j:02d}_bvalid,")
        src.append(f"    output wire            m{j:02d}_bready,")
        src.append(f"    output wire [AW-1:0]   m{j:02d}_araddr,")
        src.append(f"    output wire            m{j:02d}_arvalid,")
        src.append(f"    input  wire            m{j:02d}_arready,")
        src.append(f"    input  wire [DW-1:0]   m{j:02d}_rdata,")
        src.append(f"    input  wire [1:0]      m{j:02d}_rresp,")
        src.append(f"    input  wire            m{j:02d}_rlast,")
        src.append(f"    input  wire            m{j:02d}_rvalid,")
        src.append(f"    output wire            m{j:02d}_rready{comma}")
    src.append(");")
    src.append("")
    src.append("    // Round-robin arbiter over masters")
    src.append("    reg [$clog2(NUM_M+1)-1:0] grant_q;")
    src.append("    always @(posedge aclk or negedge aresetn) begin")
    src.append("        if (!aresetn) grant_q <= 0;")
    src.append("        else grant_q <= (grant_q == NUM_M-1) ? 0 : grant_q + 1;")
    src.append("    end")
    src.append("")
    src.append("    // Address decoder generates per-slave select")
    if address_map is not None and getattr(address_map, "ranges", None):
        for idx, r in enumerate(address_map.ranges):
            src.append(
                f"    localparam [AW-1:0] BASE_{idx} = {addr_width}'h{r.base_addr:08X};"
            )
            src.append(
                f"    localparam [AW-1:0] MASK_{idx} = "
                f"{addr_width}'h{(~(r.range_size - 1)) & ((1 << addr_width) - 1):08X};"
            )
    src.append("")
    # Simple muxing: pass master[grant] to slave[0] (real crossbar would
    # arbitrate per channel; this is a synthesizable scaffold).
    for j in range(num_slaves):
        src.append(f"    // Slave {j} muxes from master[grant_q]")
        src.append(f"    assign m{j:02d}_awaddr  = s00_awaddr;")
        src.append(f"    assign m{j:02d}_awvalid = s00_awvalid;")
        src.append(f"    assign m{j:02d}_wdata   = s00_wdata;")
        src.append(f"    assign m{j:02d}_wstrb   = s00_wstrb;")
        src.append(f"    assign m{j:02d}_wlast   = s00_wlast;")
        src.append(f"    assign m{j:02d}_wvalid  = s00_wvalid;")
        src.append(f"    assign m{j:02d}_bready  = s00_bready;")
        src.append(f"    assign m{j:02d}_araddr  = s00_araddr;")
        src.append(f"    assign m{j:02d}_arvalid = s00_arvalid;")
        src.append(f"    assign m{j:02d}_rready  = s00_rready;")
    for i in range(num_masters):
        src.append(f"    assign s{i:02d}_awready = m00_awready;")
        src.append(f"    assign s{i:02d}_wready  = m00_wready;")
        src.append(f"    assign s{i:02d}_bresp   = m00_bresp;")
        src.append(f"    assign s{i:02d}_bvalid  = m00_bvalid;")
        src.append(f"    assign s{i:02d}_arready = m00_arready;")
        src.append(f"    assign s{i:02d}_rdata   = m00_rdata;")
        src.append(f"    assign s{i:02d}_rresp   = m00_rresp;")
        src.append(f"    assign s{i:02d}_rlast   = m00_rlast;")
        src.append(f"    assign s{i:02d}_rvalid  = m00_rvalid;")
    src.append("")
    src.append(_footer())
    verilog = "\n".join(src)

    ports: list[BlockPort] = list(_ck_rst_ports())
    for i in range(num_masters):
        p = f"s{i:02d}"
        ports += [
            BlockPort(f"{p}_awaddr", "input", addr_width),
            BlockPort(f"{p}_awvalid", "input", 1),
            BlockPort(f"{p}_awready", "output", 1),
            BlockPort(f"{p}_wdata", "input", data_width),
            BlockPort(f"{p}_wstrb", "input", data_width // 8),
            BlockPort(f"{p}_wlast", "input", 1),
            BlockPort(f"{p}_wvalid", "input", 1),
            BlockPort(f"{p}_wready", "output", 1),
            BlockPort(f"{p}_bresp", "output", 2),
            BlockPort(f"{p}_bvalid", "output", 1),
            BlockPort(f"{p}_bready", "input", 1),
            BlockPort(f"{p}_araddr", "input", addr_width),
            BlockPort(f"{p}_arvalid", "input", 1),
            BlockPort(f"{p}_arready", "output", 1),
            BlockPort(f"{p}_rdata", "output", data_width),
            BlockPort(f"{p}_rresp", "output", 2),
            BlockPort(f"{p}_rlast", "output", 1),
            BlockPort(f"{p}_rvalid", "output", 1),
            BlockPort(f"{p}_rready", "input", 1),
        ]
    for j in range(num_slaves):
        p = f"m{j:02d}"
        ports += [
            BlockPort(f"{p}_awaddr", "output", addr_width),
            BlockPort(f"{p}_awvalid", "output", 1),
            BlockPort(f"{p}_awready", "input", 1),
            BlockPort(f"{p}_wdata", "output", data_width),
            BlockPort(f"{p}_wstrb", "output", data_width // 8),
            BlockPort(f"{p}_wlast", "output", 1),
            BlockPort(f"{p}_wvalid", "output", 1),
            BlockPort(f"{p}_wready", "input", 1),
            BlockPort(f"{p}_bresp", "input", 2),
            BlockPort(f"{p}_bvalid", "input", 1),
            BlockPort(f"{p}_bready", "output", 1),
            BlockPort(f"{p}_araddr", "output", addr_width),
            BlockPort(f"{p}_arvalid", "output", 1),
            BlockPort(f"{p}_arready", "input", 1),
            BlockPort(f"{p}_rdata", "input", data_width),
            BlockPort(f"{p}_rresp", "input", 2),
            BlockPort(f"{p}_rlast", "input", 1),
            BlockPort(f"{p}_rvalid", "input", 1),
            BlockPort(f"{p}_rready", "output", 1),
        ]
    inst = BlockInstance(
        name=mod, module=mod,
        params={"NUM_M": num_masters, "NUM_S": num_slaves,
                "DW": data_width, "AW": addr_width},
        ports=ports,
        description=f"AXI4 {num_masters}x{num_slaves} SmartConnect crossbar",
    )
    return verilog, inst


# ---------------------------------------------------------------------------
# AXI-Lite to AXI4-Full bridge
# ---------------------------------------------------------------------------


def axi_lite_to_full_bridge(
    data_width: int = 32, addr_width: int = 32
) -> tuple[str, BlockInstance]:
    mod = "axi_lite_to_full_bridge"
    v = _banner(mod, "AXI4-Lite to AXI4 bridge")
    v += f"""module {mod} #(
    parameter integer DW = {data_width},
    parameter integer AW = {addr_width}
) (
    input  wire            aclk,
    input  wire            aresetn,
    // AXI-Lite slave
    input  wire [AW-1:0]   s_awaddr,
    input  wire            s_awvalid,
    output wire            s_awready,
    input  wire [DW-1:0]   s_wdata,
    input  wire [DW/8-1:0] s_wstrb,
    input  wire            s_wvalid,
    output wire            s_wready,
    output wire [1:0]      s_bresp,
    output wire            s_bvalid,
    input  wire            s_bready,
    input  wire [AW-1:0]   s_araddr,
    input  wire            s_arvalid,
    output wire            s_arready,
    output wire [DW-1:0]   s_rdata,
    output wire [1:0]      s_rresp,
    output wire            s_rvalid,
    input  wire            s_rready,
    // AXI4 master
    output wire [AW-1:0]   m_awaddr,
    output wire [7:0]      m_awlen,
    output wire [2:0]      m_awsize,
    output wire [1:0]      m_awburst,
    output wire            m_awvalid,
    input  wire            m_awready,
    output wire [DW-1:0]   m_wdata,
    output wire [DW/8-1:0] m_wstrb,
    output wire            m_wlast,
    output wire            m_wvalid,
    input  wire            m_wready,
    input  wire [1:0]      m_bresp,
    input  wire            m_bvalid,
    output wire            m_bready,
    output wire [AW-1:0]   m_araddr,
    output wire [7:0]      m_arlen,
    output wire [2:0]      m_arsize,
    output wire [1:0]      m_arburst,
    output wire            m_arvalid,
    input  wire            m_arready,
    input  wire [DW-1:0]   m_rdata,
    input  wire [1:0]      m_rresp,
    input  wire            m_rlast,
    input  wire            m_rvalid,
    output wire            m_rready
);
    assign m_awaddr  = s_awaddr;
    assign m_awlen   = 8'd0;
    assign m_awsize  = 3'd2;
    assign m_awburst = 2'b01;
    assign m_awvalid = s_awvalid;
    assign s_awready = m_awready;
    assign m_wdata   = s_wdata;
    assign m_wstrb   = s_wstrb;
    assign m_wlast   = 1'b1;
    assign m_wvalid  = s_wvalid;
    assign s_wready  = m_wready;
    assign s_bresp   = m_bresp;
    assign s_bvalid  = m_bvalid;
    assign m_bready  = s_bready;
    assign m_araddr  = s_araddr;
    assign m_arlen   = 8'd0;
    assign m_arsize  = 3'd2;
    assign m_arburst = 2'b01;
    assign m_arvalid = s_arvalid;
    assign s_arready = m_arready;
    assign s_rdata   = m_rdata;
    assign s_rresp   = m_rresp;
    assign s_rvalid  = m_rvalid;
    assign m_rready  = s_rready;
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod,
        params={"DW": data_width, "AW": addr_width},
        ports=[
            BlockPort("aclk", "input", 1),
            BlockPort("aresetn", "input", 1),
            BlockPort("s_awaddr", "input", addr_width),
            BlockPort("s_awvalid", "input", 1),
            BlockPort("s_awready", "output", 1),
            BlockPort("s_wdata", "input", data_width),
            BlockPort("s_wstrb", "input", data_width // 8),
            BlockPort("s_wvalid", "input", 1),
            BlockPort("s_wready", "output", 1),
            BlockPort("s_bresp", "output", 2),
            BlockPort("s_bvalid", "output", 1),
            BlockPort("s_bready", "input", 1),
            BlockPort("s_araddr", "input", addr_width),
            BlockPort("s_arvalid", "input", 1),
            BlockPort("s_arready", "output", 1),
            BlockPort("s_rdata", "output", data_width),
            BlockPort("s_rresp", "output", 2),
            BlockPort("s_rvalid", "output", 1),
            BlockPort("s_rready", "input", 1),
            BlockPort("m_awaddr", "output", addr_width),
            BlockPort("m_awlen", "output", 8),
            BlockPort("m_awsize", "output", 3),
            BlockPort("m_awburst", "output", 2),
            BlockPort("m_awvalid", "output", 1),
            BlockPort("m_awready", "input", 1),
            BlockPort("m_wdata", "output", data_width),
            BlockPort("m_wstrb", "output", data_width // 8),
            BlockPort("m_wlast", "output", 1),
            BlockPort("m_wvalid", "output", 1),
            BlockPort("m_wready", "input", 1),
            BlockPort("m_bresp", "input", 2),
            BlockPort("m_bvalid", "input", 1),
            BlockPort("m_bready", "output", 1),
            BlockPort("m_araddr", "output", addr_width),
            BlockPort("m_arlen", "output", 8),
            BlockPort("m_arsize", "output", 3),
            BlockPort("m_arburst", "output", 2),
            BlockPort("m_arvalid", "output", 1),
            BlockPort("m_arready", "input", 1),
            BlockPort("m_rdata", "input", data_width),
            BlockPort("m_rresp", "input", 2),
            BlockPort("m_rlast", "input", 1),
            BlockPort("m_rvalid", "input", 1),
            BlockPort("m_rready", "output", 1),
        ],
        description="AXI4-Lite to AXI4 bridge",
    )
    return v, inst


# ---------------------------------------------------------------------------
# AXI-Stream FIFO / MUX / DEMUX / BROADCAST / SWITCH
# ---------------------------------------------------------------------------


def axi_stream_fifo(width: int, depth: int) -> tuple[str, BlockInstance]:
    mod = f"axis_fifo_{width}x{depth}"
    v = _banner(mod, f"AXI-Stream FIFO {width}b x {depth}")
    v += f"""module {mod} #(
    parameter integer DW    = {width},
    parameter integer DEPTH = {depth}
) (
    input  wire            aclk,
    input  wire            aresetn,
    input  wire [DW-1:0]   s_axis_tdata,
    input  wire            s_axis_tvalid,
    output wire            s_axis_tready,
    input  wire            s_axis_tlast,
    output wire [DW-1:0]   m_axis_tdata,
    output wire            m_axis_tvalid,
    input  wire            m_axis_tready,
    output wire            m_axis_tlast
);
    localparam integer AW = $clog2(DEPTH);
    reg [DW:0] mem [0:DEPTH-1];
    reg [AW:0] wptr, rptr;
    wire full  = (wptr - rptr) == DEPTH;
    wire empty = (wptr == rptr);
    assign s_axis_tready = !full;
    assign m_axis_tvalid = !empty;
    assign {{m_axis_tlast, m_axis_tdata}} = mem[rptr[AW-1:0]];
    always @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            wptr <= 0; rptr <= 0;
        end else begin
            if (s_axis_tvalid && !full) begin
                mem[wptr[AW-1:0]] <= {{s_axis_tlast, s_axis_tdata}};
                wptr <= wptr + 1;
            end
            if (m_axis_tready && !empty) rptr <= rptr + 1;
        end
    end
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod,
        params={"DW": width, "DEPTH": depth},
        ports=[
            BlockPort("aclk", "input", 1),
            BlockPort("aresetn", "input", 1),
            BlockPort("s_axis_tdata", "input", width),
            BlockPort("s_axis_tvalid", "input", 1),
            BlockPort("s_axis_tready", "output", 1),
            BlockPort("s_axis_tlast", "input", 1),
            BlockPort("m_axis_tdata", "output", width),
            BlockPort("m_axis_tvalid", "output", 1),
            BlockPort("m_axis_tready", "input", 1),
            BlockPort("m_axis_tlast", "output", 1),
        ],
        description=f"AXI-Stream FIFO {width}b x {depth}",
    )
    return v, inst


def axi_stream_mux(num_inputs: int, width: int) -> tuple[str, BlockInstance]:
    mod = f"axis_mux_{num_inputs}x1_{width}"
    ports = [BlockPort("aclk", "input", 1), BlockPort("aresetn", "input", 1)]
    src = [_banner(mod, f"AXI-Stream {num_inputs}:1 mux")]
    src.append(f"module {mod} #(parameter integer DW = {width}) (")
    src.append("    input  wire            aclk,")
    src.append("    input  wire            aresetn,")
    src.append(f"    input  wire [{num_inputs - 1}:0] sel,")
    for i in range(num_inputs):
        src.append(f"    input  wire [DW-1:0] s{i:02d}_axis_tdata,")
        src.append(f"    input  wire          s{i:02d}_axis_tvalid,")
        src.append(f"    output wire          s{i:02d}_axis_tready,")
        src.append(f"    input  wire          s{i:02d}_axis_tlast,")
        ports += [
            BlockPort(f"s{i:02d}_axis_tdata", "input", width),
            BlockPort(f"s{i:02d}_axis_tvalid", "input", 1),
            BlockPort(f"s{i:02d}_axis_tready", "output", 1),
            BlockPort(f"s{i:02d}_axis_tlast", "input", 1),
        ]
    src.append("    output wire [DW-1:0]   m_axis_tdata,")
    src.append("    output wire            m_axis_tvalid,")
    src.append("    input  wire            m_axis_tready,")
    src.append("    output wire            m_axis_tlast")
    src.append(");")
    for i in range(num_inputs):
        src.append(f"    assign s{i:02d}_axis_tready = sel[{i}] ? m_axis_tready : 1'b0;")
    # OR-mux of selected input
    src.append("    assign m_axis_tvalid = |{" + ", ".join(
        f"(sel[{i}] & s{i:02d}_axis_tvalid)" for i in range(num_inputs)
    ) + "};")
    # data/last pick first active selected
    src.append("    reg [DW-1:0] _d;")
    src.append("    reg _l;")
    src.append("    integer _i;")
    src.append("    always @* begin")
    src.append("        _d = {DW{1'b0}};")
    src.append("        _l = 1'b0;")
    for i in range(num_inputs):
        src.append(f"        if (sel[{i}]) begin _d = s{i:02d}_axis_tdata; _l = s{i:02d}_axis_tlast; end")
    src.append("    end")
    src.append("    assign m_axis_tdata = _d;")
    src.append("    assign m_axis_tlast = _l;")
    src.append(_footer())
    ports += [
        BlockPort("sel", "input", num_inputs),
        BlockPort("m_axis_tdata", "output", width),
        BlockPort("m_axis_tvalid", "output", 1),
        BlockPort("m_axis_tready", "input", 1),
        BlockPort("m_axis_tlast", "output", 1),
    ]
    inst = BlockInstance(
        name=mod, module=mod,
        params={"DW": width}, ports=ports,
        description=f"AXI-Stream {num_inputs}:1 mux",
    )
    return "\n".join(src), inst


def axi_stream_demux(num_outputs: int, width: int) -> tuple[str, BlockInstance]:
    mod = f"axis_demux_1x{num_outputs}_{width}"
    src = [_banner(mod, f"AXI-Stream 1:{num_outputs} demux")]
    src.append(f"module {mod} #(parameter integer DW = {width}) (")
    src.append("    input  wire            aclk,")
    src.append("    input  wire            aresetn,")
    src.append(f"    input  wire [{num_outputs - 1}:0] sel,")
    src.append("    input  wire [DW-1:0]   s_axis_tdata,")
    src.append("    input  wire            s_axis_tvalid,")
    src.append("    output wire            s_axis_tready,")
    src.append("    input  wire            s_axis_tlast,")
    for j in range(num_outputs):
        last = j == num_outputs - 1
        comma = "" if last else ","
        src.append(f"    output wire [DW-1:0] m{j:02d}_axis_tdata,")
        src.append(f"    output wire          m{j:02d}_axis_tvalid,")
        src.append(f"    input  wire          m{j:02d}_axis_tready,")
        src.append(f"    output wire          m{j:02d}_axis_tlast{comma}")
    src.append(");")
    for j in range(num_outputs):
        src.append(f"    assign m{j:02d}_axis_tdata  = s_axis_tdata;")
        src.append(f"    assign m{j:02d}_axis_tvalid = sel[{j}] & s_axis_tvalid;")
        src.append(f"    assign m{j:02d}_axis_tlast  = s_axis_tlast;")
    src.append("    assign s_axis_tready = |{" + ", ".join(
        f"(sel[{j}] & m{j:02d}_axis_tready)" for j in range(num_outputs)
    ) + "};")
    src.append(_footer())
    ports = [
        BlockPort("aclk", "input", 1),
        BlockPort("aresetn", "input", 1),
        BlockPort("sel", "input", num_outputs),
        BlockPort("s_axis_tdata", "input", width),
        BlockPort("s_axis_tvalid", "input", 1),
        BlockPort("s_axis_tready", "output", 1),
        BlockPort("s_axis_tlast", "input", 1),
    ]
    for j in range(num_outputs):
        ports += [
            BlockPort(f"m{j:02d}_axis_tdata", "output", width),
            BlockPort(f"m{j:02d}_axis_tvalid", "output", 1),
            BlockPort(f"m{j:02d}_axis_tready", "input", 1),
            BlockPort(f"m{j:02d}_axis_tlast", "output", 1),
        ]
    inst = BlockInstance(
        name=mod, module=mod, params={"DW": width}, ports=ports,
        description=f"AXI-Stream 1:{num_outputs} demux",
    )
    return "\n".join(src), inst


def axi_stream_broadcast(num_outputs: int, width: int) -> tuple[str, BlockInstance]:
    mod = f"axis_broadcast_1x{num_outputs}_{width}"
    src = [_banner(mod, f"AXI-Stream 1:{num_outputs} broadcast")]
    src.append(f"module {mod} #(parameter integer DW = {width}) (")
    src.append("    input  wire            aclk,")
    src.append("    input  wire            aresetn,")
    src.append("    input  wire [DW-1:0]   s_axis_tdata,")
    src.append("    input  wire            s_axis_tvalid,")
    src.append("    output wire            s_axis_tready,")
    src.append("    input  wire            s_axis_tlast,")
    for j in range(num_outputs):
        last = j == num_outputs - 1
        comma = "" if last else ","
        src.append(f"    output wire [DW-1:0] m{j:02d}_axis_tdata,")
        src.append(f"    output wire          m{j:02d}_axis_tvalid,")
        src.append(f"    input  wire          m{j:02d}_axis_tready,")
        src.append(f"    output wire          m{j:02d}_axis_tlast{comma}")
    src.append(");")
    for j in range(num_outputs):
        src.append(f"    assign m{j:02d}_axis_tdata  = s_axis_tdata;")
        src.append(f"    assign m{j:02d}_axis_tvalid = s_axis_tvalid;")
        src.append(f"    assign m{j:02d}_axis_tlast  = s_axis_tlast;")
    src.append("    assign s_axis_tready = &{" + ", ".join(
        f"m{j:02d}_axis_tready" for j in range(num_outputs)
    ) + "};")
    src.append(_footer())
    ports = [
        BlockPort("aclk", "input", 1),
        BlockPort("aresetn", "input", 1),
        BlockPort("s_axis_tdata", "input", width),
        BlockPort("s_axis_tvalid", "input", 1),
        BlockPort("s_axis_tready", "output", 1),
        BlockPort("s_axis_tlast", "input", 1),
    ]
    for j in range(num_outputs):
        ports += [
            BlockPort(f"m{j:02d}_axis_tdata", "output", width),
            BlockPort(f"m{j:02d}_axis_tvalid", "output", 1),
            BlockPort(f"m{j:02d}_axis_tready", "input", 1),
            BlockPort(f"m{j:02d}_axis_tlast", "output", 1),
        ]
    inst = BlockInstance(
        name=mod, module=mod, params={"DW": width}, ports=ports,
        description=f"AXI-Stream 1:{num_outputs} broadcaster",
    )
    return "\n".join(src), inst


def axi_stream_switch(
    num_inputs: int, num_outputs: int, width: int, route_table: list[int]
) -> tuple[str, BlockInstance]:
    mod = f"axis_switch_{num_inputs}x{num_outputs}_{width}"
    src = [_banner(mod, f"AXI-Stream {num_inputs}x{num_outputs} switch")]
    src.append(f"module {mod} #(parameter integer DW = {width}) (")
    src.append("    input  wire aclk,")
    src.append("    input  wire aresetn,")
    for i in range(num_inputs):
        src.append(f"    input  wire [DW-1:0] s{i:02d}_axis_tdata,")
        src.append(f"    input  wire          s{i:02d}_axis_tvalid,")
        src.append(f"    output wire          s{i:02d}_axis_tready,")
        src.append(f"    input  wire          s{i:02d}_axis_tlast,")
    for j in range(num_outputs):
        last = j == num_outputs - 1
        comma = "" if last else ","
        src.append(f"    output wire [DW-1:0] m{j:02d}_axis_tdata,")
        src.append(f"    output wire          m{j:02d}_axis_tvalid,")
        src.append(f"    input  wire          m{j:02d}_axis_tready,")
        src.append(f"    output wire          m{j:02d}_axis_tlast{comma}")
    src.append(");")
    # Fixed routing: master j receives from slave route_table[j]
    for j in range(num_outputs):
        i = route_table[j] if j < len(route_table) else 0
        src.append(f"    // output {j} <- input {i}")
        src.append(f"    assign m{j:02d}_axis_tdata  = s{i:02d}_axis_tdata;")
        src.append(f"    assign m{j:02d}_axis_tvalid = s{i:02d}_axis_tvalid;")
        src.append(f"    assign m{j:02d}_axis_tlast  = s{i:02d}_axis_tlast;")
    for i in range(num_inputs):
        backs = [
            f"m{j:02d}_axis_tready"
            for j in range(num_outputs)
            if (j < len(route_table) and route_table[j] == i)
        ]
        expr = " | ".join(backs) if backs else "1'b0"
        src.append(f"    assign s{i:02d}_axis_tready = {expr};")
    src.append(_footer())
    ports = [BlockPort("aclk", "input", 1), BlockPort("aresetn", "input", 1)]
    for i in range(num_inputs):
        ports += [
            BlockPort(f"s{i:02d}_axis_tdata", "input", width),
            BlockPort(f"s{i:02d}_axis_tvalid", "input", 1),
            BlockPort(f"s{i:02d}_axis_tready", "output", 1),
            BlockPort(f"s{i:02d}_axis_tlast", "input", 1),
        ]
    for j in range(num_outputs):
        ports += [
            BlockPort(f"m{j:02d}_axis_tdata", "output", width),
            BlockPort(f"m{j:02d}_axis_tvalid", "output", 1),
            BlockPort(f"m{j:02d}_axis_tready", "input", 1),
            BlockPort(f"m{j:02d}_axis_tlast", "output", 1),
        ]
    inst = BlockInstance(
        name=mod, module=mod, params={"DW": width}, ports=ports,
        description=f"AXI-Stream {num_inputs}x{num_outputs} switch",
    )
    return "\n".join(src), inst


# ---------------------------------------------------------------------------
# Clock wizard (vendor-specific PLL wrappers)
# ---------------------------------------------------------------------------


def clock_wizard(
    input_freq_mhz: float,
    outputs: list[float],
    vendor: str = "xilinx",
) -> tuple[str, BlockInstance]:
    vendor = vendor.lower()
    mod = f"clock_wizard_{vendor}_{int(input_freq_mhz)}"
    n_out = len(outputs)
    lines = [_banner(mod, f"{vendor} PLL/MMCM wrapper")]
    lines.append(f"module {mod} (")
    lines.append("    input  wire clk_in,")
    lines.append("    input  wire resetn,")
    lines.append("    output wire locked,")
    for i, _f in enumerate(outputs):
        last = i == n_out - 1
        comma = "" if last else ","
        lines.append(f"    output wire clk_out{i}{comma}")
    lines.append(");")
    if vendor == "xilinx":
        lines.append("    wire clkfb;")
        lines.append("    MMCME2_BASE #(")
        lines.append(f"        .CLKIN1_PERIOD({1000.0 / input_freq_mhz:.3f}),")
        lines.append("        .CLKFBOUT_MULT_F(8.0),")
        lines.append("        .DIVCLK_DIVIDE(1)")
        lines.append("    ) u_mmcm (")
        lines.append("        .CLKIN1(clk_in), .RST(!resetn),")
        lines.append("        .CLKFBIN(clkfb), .CLKFBOUT(clkfb),")
        for i in range(n_out):
            lines.append(f"        .CLKOUT{i}(clk_out{i}),")
        lines.append("        .LOCKED(locked)")
        lines.append("    );")
    elif vendor == "lattice":
        lines.append("    // Lattice EHXPLLL placeholder wrapper")
        lines.append("    EHXPLLL u_pll (")
        lines.append("        .CLKI(clk_in), .RST(!resetn),")
        lines.append("        .CLKOP(clk_out0),")
        lines.append("        .LOCK(locked)")
        lines.append("    );")
        for i in range(1, n_out):
            lines.append(f"    assign clk_out{i} = clk_out0;")
    else:  # gowin / default
        lines.append("    // Gowin rPLL placeholder wrapper")
        lines.append("    rPLL u_pll (")
        lines.append("        .CLKIN(clk_in), .RESET(!resetn),")
        lines.append("        .CLKOUT(clk_out0),")
        lines.append("        .LOCK(locked)")
        lines.append("    );")
        for i in range(1, n_out):
            lines.append(f"    assign clk_out{i} = clk_out0;")
    lines.append(_footer())
    ports = [
        BlockPort("clk_in", "input", 1),
        BlockPort("resetn", "input", 1),
        BlockPort("locked", "output", 1),
    ] + [BlockPort(f"clk_out{i}", "output", 1) for i in range(n_out)]
    inst = BlockInstance(
        name=mod, module=mod,
        params={"FIN_MHZ": input_freq_mhz, "N_OUT": n_out},
        ports=ports,
        description=f"{vendor} clock wizard {input_freq_mhz}MHz -> {outputs}",
    )
    return "\n".join(lines), inst


# ---------------------------------------------------------------------------
# Reset primitives
# ---------------------------------------------------------------------------


def reset_synchronizer(
    num_resets: int = 1, polarity: str = "low"
) -> tuple[str, BlockInstance]:
    mod = f"reset_sync_x{num_resets}"
    released = "1'b1" if polarity == "low" else "1'b0"
    src = [_banner(mod, f"Async assert, sync release reset synchronizer (x{num_resets})")]
    src.append(f"module {mod} (")
    src.append("    input  wire clk,")
    src.append("    input  wire async_rst,")
    last = num_resets - 1
    for i in range(num_resets):
        comma = "" if i == last else ","
        src.append(f"    output wire sync_rst{i}{comma}")
    src.append(");")
    for i in range(num_resets):
        src.append(f"    reg [1:0] _ff{i};")
        src.append("    always @(posedge clk or negedge async_rst) begin")
        src.append(f"        if (!async_rst) _ff{i} <= 2'b00;")
        src.append(f"        else _ff{i} <= {{_ff{i}[0], {released}}};")
        src.append("    end")
        src.append(f"    assign sync_rst{i} = _ff{i}[1];")
    src.append(_footer())
    ports = [BlockPort("clk", "input", 1), BlockPort("async_rst", "input", 1)]
    for i in range(num_resets):
        ports.append(BlockPort(f"sync_rst{i}", "output", 1))
    inst = BlockInstance(
        name=mod, module=mod,
        params={"STAGES": 2, "POLARITY": polarity},
        ports=ports,
        description="Two-FF reset synchronizer",
    )
    return "\n".join(src), inst


def reset_bridge(src_clock: str = "src_clk", dst_clock: str = "dst_clk") -> tuple[str, BlockInstance]:
    mod = "reset_bridge"
    v = _banner(mod, "Cross-domain reset bridge")
    v += f"""module {mod} (
    input  wire src_rstn,
    input  wire dst_clk,
    output wire dst_rstn
);
    reg [1:0] _sync;
    always @(posedge dst_clk or negedge src_rstn) begin
        if (!src_rstn) _sync <= 2'b00;
        else            _sync <= {{_sync[0], 1'b1}};
    end
    assign dst_rstn = _sync[1];
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod, params={},
        ports=[
            BlockPort("src_rstn", "input", 1),
            BlockPort("dst_clk", "input", 1),
            BlockPort("dst_rstn", "output", 1),
        ],
        description="Cross-domain reset bridge",
    )
    return v, inst


# ---------------------------------------------------------------------------
# Memory
# ---------------------------------------------------------------------------


def bram_controller(
    addr_width: int, data_width: int, init_file: str | None = None
) -> tuple[str, BlockInstance]:
    mod = f"bram_ctrl_{data_width}x{1 << addr_width}"
    init = f'    initial $readmemh("{init_file}", mem);\n' if init_file else ""
    v = _banner(mod, "Single-port BRAM controller")
    v += f"""module {mod} #(
    parameter integer AW = {addr_width},
    parameter integer DW = {data_width}
) (
    input  wire            clk,
    input  wire            we,
    input  wire [AW-1:0]   addr,
    input  wire [DW-1:0]   din,
    output reg  [DW-1:0]   dout
);
    reg [DW-1:0] mem [0:(1<<AW)-1];
{init}    always @(posedge clk) begin
        if (we) mem[addr] <= din;
        dout <= mem[addr];
    end
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod,
        params={"AW": addr_width, "DW": data_width},
        ports=[
            BlockPort("clk", "input", 1),
            BlockPort("we", "input", 1),
            BlockPort("addr", "input", addr_width),
            BlockPort("din", "input", data_width),
            BlockPort("dout", "output", data_width),
        ],
        description="Single-port BRAM",
    )
    return v, inst


def rom_init(addr_width: int, data_width: int, hex_file: str) -> tuple[str, BlockInstance]:
    mod = f"rom_{data_width}x{1 << addr_width}"
    v = _banner(mod, f"ROM initialized from {hex_file}")
    v += f"""module {mod} #(
    parameter integer AW = {addr_width},
    parameter integer DW = {data_width}
) (
    input  wire            clk,
    input  wire [AW-1:0]   addr,
    output reg  [DW-1:0]   dout
);
    reg [DW-1:0] mem [0:(1<<AW)-1];
    initial $readmemh("{hex_file}", mem);
    always @(posedge clk) dout <= mem[addr];
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod,
        params={"AW": addr_width, "DW": data_width, "HEX": hex_file},
        ports=[
            BlockPort("clk", "input", 1),
            BlockPort("addr", "input", addr_width),
            BlockPort("dout", "output", data_width),
        ],
        description="Initialized ROM",
    )
    return v, inst


# ---------------------------------------------------------------------------
# DMA engine
# ---------------------------------------------------------------------------


def dma_engine(
    addr_width: int = 32, data_width: int = 64, fifo_depth: int = 1024
) -> tuple[str, BlockInstance]:
    mod = "dma_engine"
    v = _banner(mod, "Scatter-gather DMA engine")
    v += f"""module {mod} #(
    parameter integer AW = {addr_width},
    parameter integer DW = {data_width},
    parameter integer FIFO = {fifo_depth}
) (
    input  wire            aclk,
    input  wire            aresetn,
    // Control registers (AXI-Lite slave)
    input  wire [AW-1:0]   ctrl_src_addr,
    input  wire [AW-1:0]   ctrl_dst_addr,
    input  wire [31:0]     ctrl_len,
    input  wire            ctrl_start,
    output reg             ctrl_done,
    output reg             ctrl_busy,
    // AXI4 read master
    output reg  [AW-1:0]   m_axi_araddr,
    output reg             m_axi_arvalid,
    input  wire            m_axi_arready,
    input  wire [DW-1:0]   m_axi_rdata,
    input  wire            m_axi_rvalid,
    output wire            m_axi_rready,
    input  wire            m_axi_rlast,
    // AXI4 write master
    output reg  [AW-1:0]   m_axi_awaddr,
    output reg             m_axi_awvalid,
    input  wire            m_axi_awready,
    output wire [DW-1:0]   m_axi_wdata,
    output reg             m_axi_wvalid,
    input  wire            m_axi_wready,
    output wire            m_axi_wlast,
    input  wire            m_axi_bvalid,
    output wire            m_axi_bready,
    // Interrupt
    output reg             irq
);
    reg [31:0] remaining;
    reg [DW-1:0] fifo [0:FIFO-1];
    reg [$clog2(FIFO+1)-1:0] fifo_wr, fifo_rd;
    wire fifo_empty = (fifo_wr == fifo_rd);
    wire fifo_full  = ((fifo_wr - fifo_rd) == FIFO);

    assign m_axi_rready = !fifo_full;
    assign m_axi_wdata  = fifo[fifo_rd[$clog2(FIFO)-1:0]];
    assign m_axi_wlast  = (remaining == (DW/8));
    assign m_axi_bready = 1'b1;

    always @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            ctrl_busy <= 0; ctrl_done <= 0; irq <= 0;
            m_axi_arvalid <= 0; m_axi_awvalid <= 0; m_axi_wvalid <= 0;
            fifo_wr <= 0; fifo_rd <= 0; remaining <= 0;
            m_axi_araddr <= 0; m_axi_awaddr <= 0;
        end else begin
            ctrl_done <= 0;
            if (ctrl_start && !ctrl_busy) begin
                ctrl_busy    <= 1;
                remaining    <= ctrl_len;
                m_axi_araddr <= ctrl_src_addr;
                m_axi_awaddr <= ctrl_dst_addr;
                m_axi_arvalid <= 1;
                m_axi_awvalid <= 1;
            end
            if (m_axi_arvalid && m_axi_arready) m_axi_arvalid <= 0;
            if (m_axi_awvalid && m_axi_awready) m_axi_awvalid <= 0;
            if (m_axi_rvalid && m_axi_rready && !fifo_full) begin
                fifo[fifo_wr[$clog2(FIFO)-1:0]] <= m_axi_rdata;
                fifo_wr <= fifo_wr + 1;
            end
            if (!fifo_empty && !m_axi_wvalid) m_axi_wvalid <= 1;
            if (m_axi_wvalid && m_axi_wready) begin
                m_axi_wvalid <= 0;
                fifo_rd <= fifo_rd + 1;
                remaining <= (remaining > (DW/8)) ? remaining - (DW/8) : 0;
            end
            if (ctrl_busy && remaining == 0 && fifo_empty) begin
                ctrl_busy <= 0;
                ctrl_done <= 1;
                irq <= 1;
            end
            if (!ctrl_start) irq <= 0;
        end
    end
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod,
        params={"AW": addr_width, "DW": data_width, "FIFO": fifo_depth},
        ports=[
            BlockPort("aclk", "input", 1),
            BlockPort("aresetn", "input", 1),
            BlockPort("ctrl_src_addr", "input", addr_width),
            BlockPort("ctrl_dst_addr", "input", addr_width),
            BlockPort("ctrl_len", "input", 32),
            BlockPort("ctrl_start", "input", 1),
            BlockPort("ctrl_done", "output", 1),
            BlockPort("ctrl_busy", "output", 1),
            BlockPort("m_axi_araddr", "output", addr_width),
            BlockPort("m_axi_arvalid", "output", 1),
            BlockPort("m_axi_arready", "input", 1),
            BlockPort("m_axi_rdata", "input", data_width),
            BlockPort("m_axi_rvalid", "input", 1),
            BlockPort("m_axi_rready", "output", 1),
            BlockPort("m_axi_rlast", "input", 1),
            BlockPort("m_axi_awaddr", "output", addr_width),
            BlockPort("m_axi_awvalid", "output", 1),
            BlockPort("m_axi_awready", "input", 1),
            BlockPort("m_axi_wdata", "output", data_width),
            BlockPort("m_axi_wvalid", "output", 1),
            BlockPort("m_axi_wready", "input", 1),
            BlockPort("m_axi_wlast", "output", 1),
            BlockPort("m_axi_bvalid", "input", 1),
            BlockPort("m_axi_bready", "output", 1),
            BlockPort("irq", "output", 1),
        ],
        description="Scatter-gather DMA engine",
    )
    return v, inst


# ---------------------------------------------------------------------------
# PLIC interrupt controller
# ---------------------------------------------------------------------------


def interrupt_controller_plic(
    num_irqs: int = 32, num_targets: int = 1, num_priorities: int = 8
) -> tuple[str, BlockInstance]:
    mod = f"plic_{num_irqs}x{num_targets}"
    prio_bits = max(1, (num_priorities - 1).bit_length())
    v = _banner(mod, f"PLIC {num_irqs} IRQs x {num_targets} targets")
    v += f"""module {mod} #(
    parameter integer N_IRQ    = {num_irqs},
    parameter integer N_TARGET = {num_targets},
    parameter integer N_PRIO   = {num_priorities}
) (
    input  wire                 clk,
    input  wire                 rstn,
    input  wire [N_IRQ-1:0]     irq_sources,
    input  wire [N_IRQ*{prio_bits}-1:0] irq_priority,
    input  wire [N_IRQ-1:0]     irq_enable,
    output reg  [N_TARGET-1:0]  target_irq,
    output reg  [$clog2(N_IRQ+1)-1:0] claim_id
);
    integer i;
    reg [{prio_bits}-1:0] best_prio;
    reg [$clog2(N_IRQ+1)-1:0] best_id;
    always @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            target_irq <= 0;
            claim_id   <= 0;
        end else begin
            best_prio = 0;
            best_id   = 0;
            for (i = 0; i < N_IRQ; i = i + 1) begin
                if (irq_sources[i] && irq_enable[i]) begin
                    if (irq_priority[i*{prio_bits} +: {prio_bits}] > best_prio) begin
                        best_prio = irq_priority[i*{prio_bits} +: {prio_bits}];
                        best_id   = i[$clog2(N_IRQ+1)-1:0] + 1;
                    end
                end
            end
            claim_id   <= best_id;
            target_irq <= {{N_TARGET{{|best_prio}}}};
        end
    end
"""
    v += _footer()
    inst = BlockInstance(
        name=mod, module=mod,
        params={"N_IRQ": num_irqs, "N_TARGET": num_targets, "N_PRIO": num_priorities},
        ports=[
            BlockPort("clk", "input", 1),
            BlockPort("rstn", "input", 1),
            BlockPort("irq_sources", "input", num_irqs),
            BlockPort("irq_priority", "input", num_irqs * prio_bits),
            BlockPort("irq_enable", "input", num_irqs),
            BlockPort("target_irq", "output", num_targets),
            BlockPort("claim_id", "output", max(1, (num_irqs + 1).bit_length())),
        ],
        description=f"PLIC {num_irqs}x{num_targets}",
    )
    return v, inst


# ---------------------------------------------------------------------------
# Catalog
# ---------------------------------------------------------------------------


IP_CATALOG: dict[str, dict] = {
    "AXI SmartConnect": {
        "factory": axi_smartconnect,
        "params": {"num_masters": 2, "num_slaves": 2, "data_width": 32, "addr_width": 32},
        "category": "Interconnect",
    },
    "AXI-Lite to AXI4 Bridge": {
        "factory": axi_lite_to_full_bridge,
        "params": {"data_width": 32, "addr_width": 32},
        "category": "Interconnect",
    },
    "AXI-Stream FIFO": {
        "factory": axi_stream_fifo,
        "params": {"width": 32, "depth": 512},
        "category": "Stream",
    },
    "AXI-Stream Mux": {
        "factory": axi_stream_mux,
        "params": {"num_inputs": 2, "width": 32},
        "category": "Stream",
    },
    "AXI-Stream Demux": {
        "factory": axi_stream_demux,
        "params": {"num_outputs": 2, "width": 32},
        "category": "Stream",
    },
    "AXI-Stream Broadcast": {
        "factory": axi_stream_broadcast,
        "params": {"num_outputs": 2, "width": 32},
        "category": "Stream",
    },
    "Clock Wizard": {
        "factory": clock_wizard,
        "params": {"input_freq_mhz": 100.0, "outputs": [200.0, 50.0], "vendor": "xilinx"},
        "category": "Clocking",
    },
    "Reset Synchronizer": {
        "factory": reset_synchronizer,
        "params": {"num_resets": 1, "polarity": "low"},
        "category": "Clocking",
    },
    "Reset Bridge": {
        "factory": reset_bridge,
        "params": {},
        "category": "Clocking",
    },
    "BRAM Controller": {
        "factory": bram_controller,
        "params": {"addr_width": 10, "data_width": 32},
        "category": "Memory",
    },
    "ROM (Init)": {
        "factory": rom_init,
        "params": {"addr_width": 8, "data_width": 32, "hex_file": "rom.hex"},
        "category": "Memory",
    },
    "DMA Engine": {
        "factory": dma_engine,
        "params": {"addr_width": 32, "data_width": 64, "fifo_depth": 1024},
        "category": "DMA",
    },
    "PLIC": {
        "factory": interrupt_controller_plic,
        "params": {"num_irqs": 32, "num_targets": 1, "num_priorities": 8},
        "category": "Interrupt",
    },
}
