/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* top =  1  *)
(* src = "src/spi_master.v:7.1-134.10" *)
module spi_master(clk, rst_n, tx_data, tx_valid, tx_ready, rx_data, rx_valid, sclk, mosi, miso, cs_n);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  (* force_downto = 32'd1 *)
  (* src = "src/spi_master.v:0.0-0.0|src/spi_master.v:55.13-130.20|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  (* unused_bits = "1" *)
  wire [1:0] _185_;
  (* src = "src/spi_master.v:35.16-35.23" *)
  wire [2:0] bit_cnt;
  (* src = "src/spi_master.v:10.23-10.26" *)
  input clk;
  wire clk;
  (* src = "src/spi_master.v:34.16-34.23" *)
  wire [15:0] clk_cnt;
  (* src = "src/spi_master.v:24.23-24.27" *)
  output cs_n;
  wire cs_n;
  (* src = "src/spi_master.v:23.23-23.27" *)
  input miso;
  wire miso;
  (* src = "src/spi_master.v:22.23-22.27" *)
  output mosi;
  wire mosi;
  (* src = "src/spi_master.v:11.23-11.28" *)
  input rst_n;
  wire rst_n;
  (* src = "src/spi_master.v:17.23-17.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "src/spi_master.v:18.23-18.31" *)
  output rx_valid;
  wire rx_valid;
  (* src = "src/spi_master.v:21.23-21.27" *)
  output sclk;
  wire sclk;
  (* src = "src/spi_master.v:37.16-37.24" *)
  wire [7:0] shift_in;
  (* src = "src/spi_master.v:36.16-36.25" *)
  wire [7:0] shift_out;
  (* src = "src/spi_master.v:33.16-33.21" *)
  wire [2:0] state;
  (* src = "src/spi_master.v:14.23-14.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "src/spi_master.v:16.23-16.31" *)
  output tx_ready;
  wire tx_ready;
  (* src = "src/spi_master.v:15.23-15.31" *)
  input tx_valid;
  wire tx_valid;
  sky130_fd_sc_hd__inv_1 _186_ (
    .A(state[0]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__inv_1 _187_ (
    .A(state[1]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(state[2]),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(_052_),
    .B(tx_valid),
    .Y(_053_)
  );
  sky130_fd_sc_hd__inv_1 _191_ (
    .A(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__buf_4 _192_ (
    .A(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(_055_),
    .B(tx_data[0]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(_053_),
    .B(shift_out[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(_056_),
    .B(_057_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__inv_1 _196_ (
    .A(shift_out[1]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(_055_),
    .B(tx_data[1]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(_058_),
    .A2(_055_),
    .B1(_059_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_055_),
    .B(tx_data[2]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(_053_),
    .B(shift_out[2]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(_060_),
    .B(_061_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_1 _202_ (
    .A(shift_out[3]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_055_),
    .B(tx_data[3]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__o21ai_0 _204_ (
    .A1(_062_),
    .A2(_055_),
    .B1(_063_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_1 _205_ (
    .A(shift_out[4]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(_054_),
    .B(tx_data[4]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _207_ (
    .A1(_064_),
    .A2(_055_),
    .B1(_065_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(_055_),
    .B(tx_data[5]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_053_),
    .B(shift_out[5]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(_066_),
    .B(_067_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_055_),
    .B(tx_data[6]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_053_),
    .B(shift_out[6]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(_068_),
    .B(_069_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(_054_),
    .B(tx_data[7]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_053_),
    .B(shift_out[7]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(_070_),
    .B(_071_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_1 _217_ (
    .A(shift_in[0]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__inv_1 _218_ (
    .A(state[2]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _219_ (
    .A(_073_),
    .B(_051_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__buf_4 _220_ (
    .A(_074_),
    .X(_185_[0])
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(rx_data[0]),
    .B(_185_[0]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _222_ (
    .A1(_072_),
    .A2(_185_[0]),
    .B1(_075_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_1 _223_ (
    .A(shift_in[1]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(rx_data[1]),
    .B(_185_[0]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a21oi_1 _225_ (
    .A1(_076_),
    .A2(_185_[0]),
    .B1(_077_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_1 _226_ (
    .A(shift_in[2]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(rx_data[2]),
    .B(_074_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a21oi_1 _228_ (
    .A1(_078_),
    .A2(_185_[0]),
    .B1(_079_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_1 _229_ (
    .A(shift_in[3]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(rx_data[3]),
    .B(_074_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a21oi_1 _231_ (
    .A1(_080_),
    .A2(_185_[0]),
    .B1(_081_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_1 _232_ (
    .A(shift_in[4]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(rx_data[4]),
    .B(_074_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a21oi_1 _234_ (
    .A1(_082_),
    .A2(_185_[0]),
    .B1(_083_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_1 _235_ (
    .A(shift_in[5]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(rx_data[5]),
    .B(_074_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21oi_1 _237_ (
    .A1(_084_),
    .A2(_185_[0]),
    .B1(_085_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_1 _238_ (
    .A(shift_in[6]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(rx_data[6]),
    .B(_074_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _240_ (
    .A1(_086_),
    .A2(_185_[0]),
    .B1(_087_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__mux2_2 _241_ (
    .A0(rx_data[7]),
    .A1(shift_in[7]),
    .S(_074_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(clk_cnt[6]),
    .B(clk_cnt[7]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _243_ (
    .A(clk_cnt[4]),
    .B(clk_cnt[5]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(clk_cnt[2]),
    .B(clk_cnt[3]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(clk_cnt[0]),
    .B(clk_cnt[1]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _246_ (
    .A(_088_),
    .B(_089_),
    .C(_090_),
    .D(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(clk_cnt[14]),
    .B(clk_cnt[15]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(clk_cnt[12]),
    .B(clk_cnt[13]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _249_ (
    .A(clk_cnt[10]),
    .B(clk_cnt[11]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(clk_cnt[8]),
    .B(clk_cnt[9]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand4_1 _251_ (
    .A(_093_),
    .B(_094_),
    .C(_095_),
    .D(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _252_ (
    .A(_092_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _254_ (
    .A(state[2]),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(_098_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__inv_1 _256_ (
    .A(tx_valid),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_052_),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(_101_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_104_),
    .B(state[0]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o221ai_1 _260_ (
    .A1(_049_),
    .A2(_050_),
    .B1(_092_),
    .B2(_097_),
    .C1(_100_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand3_1 _261_ (
    .A(_105_),
    .B(_053_),
    .C(_106_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_1 _262_ (
    .A(bit_cnt[2]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand3_1 _265_ (
    .A(_073_),
    .B(state[0]),
    .C(state[1]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__inv_1 _266_ (
    .A(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o21ai_0 _267_ (
    .A1(_092_),
    .A2(_097_),
    .B1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(_104_),
    .B(state[1]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o211ai_1 _269_ (
    .A1(_109_),
    .A2(_112_),
    .B1(_106_),
    .C1(_113_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o211ai_1 _270_ (
    .A1(_092_),
    .A2(_097_),
    .B1(_111_),
    .C1(_109_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__inv_1 _271_ (
    .A(_114_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_1 _272_ (
    .A(bit_cnt[0]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_115_),
    .B(bit_cnt[1]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__inv_1 _274_ (
    .A(bit_cnt[1]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_117_),
    .B(bit_cnt[0]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand3_1 _276_ (
    .A(_116_),
    .B(_118_),
    .C(shift_out[2]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand3b_1 _278_ (
    .A_N(_120_),
    .B(shift_out[0]),
    .C(_108_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(_108_),
    .B(_107_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand3_1 _280_ (
    .A(_119_),
    .B(_121_),
    .C(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_120_),
    .B(shift_out[6]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o2111ai_1 _282_ (
    .A1(_064_),
    .A2(_120_),
    .B1(_107_),
    .C1(_108_),
    .D1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(_123_),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(_126_),
    .B(_115_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_109_),
    .B(_112_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(_115_),
    .B(_117_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor3b_1 _287_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C_N(shift_out[7]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a31oi_1 _288_ (
    .A1(_129_),
    .A2(shift_out[5]),
    .A3(_108_),
    .B1(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3_1 _289_ (
    .A(_116_),
    .B(_118_),
    .C(_062_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand3_1 _290_ (
    .A(_129_),
    .B(_058_),
    .C(_108_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand3_1 _291_ (
    .A(_132_),
    .B(_133_),
    .C(_122_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o211ai_1 _292_ (
    .A1(_122_),
    .A2(_131_),
    .B1(bit_cnt[0]),
    .C1(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand3_1 _293_ (
    .A(_127_),
    .B(_128_),
    .C(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_090_),
    .B(_091_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(_088_),
    .B(_089_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(_137_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor4_1 _297_ (
    .A(clk_cnt[12]),
    .B(clk_cnt[13]),
    .C(clk_cnt[14]),
    .D(clk_cnt[15]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor4_1 _298_ (
    .A(clk_cnt[8]),
    .B(clk_cnt[9]),
    .C(clk_cnt[10]),
    .D(clk_cnt[11]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand4_1 _299_ (
    .A(_139_),
    .B(_140_),
    .C(_141_),
    .D(_111_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a22oi_1 _300_ (
    .A1(_051_),
    .A2(_110_),
    .B1(_052_),
    .B2(_102_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand3_1 _301_ (
    .A(_114_),
    .B(_142_),
    .C(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(_144_),
    .B(mosi),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand3_1 _303_ (
    .A(_136_),
    .B(_070_),
    .C(_145_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _304_ (
    .A(cs_n),
    .B(_099_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(_146_),
    .B(_055_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21ai_0 _306_ (
    .A1(_092_),
    .A2(_097_),
    .B1(_115_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o211a_1 _307_ (
    .A1(_052_),
    .A2(_111_),
    .B1(_142_),
    .C1(_114_),
    .X(_148_)
  );
  sky130_fd_sc_hd__o22ai_1 _308_ (
    .A1(_110_),
    .A2(_147_),
    .B1(_115_),
    .B2(_148_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(_129_),
    .B(_108_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o22ai_1 _310_ (
    .A1(_149_),
    .A2(_112_),
    .B1(_117_),
    .B2(_148_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _311_ (
    .A(_128_),
    .B(_122_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _312_ (
    .A1(_107_),
    .A2(_148_),
    .B1(_150_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_1 _313_ (
    .A(sclk),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _314_ (
    .A1(_098_),
    .A2(_051_),
    .B1(state[2]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _315_ (
    .A1(_151_),
    .A2(_152_),
    .B1(_106_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(clk_cnt[0]),
    .B(clk_cnt[1]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand4_1 _317_ (
    .A(_088_),
    .B(_089_),
    .C(_090_),
    .D(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor3_1 _318_ (
    .A(_110_),
    .B(_097_),
    .C(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_1 _319_ (
    .A1(_052_),
    .A2(_155_),
    .B1(_103_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(_156_),
    .B(shift_in[0]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _321_ (
    .A(_155_),
    .B(miso),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(_157_),
    .B(_158_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_1 _323_ (
    .A(_155_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(_156_),
    .B(shift_in[1]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o21ai_0 _325_ (
    .A1(_072_),
    .A2(_159_),
    .B1(_160_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_156_),
    .B(shift_in[2]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_076_),
    .A2(_159_),
    .B1(_161_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(_156_),
    .B(shift_in[3]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o21ai_0 _329_ (
    .A1(_078_),
    .A2(_159_),
    .B1(_162_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_156_),
    .B(shift_in[4]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _331_ (
    .A1(_080_),
    .A2(_159_),
    .B1(_163_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(_156_),
    .B(shift_in[5]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o21ai_0 _333_ (
    .A1(_082_),
    .A2(_159_),
    .B1(_164_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(_156_),
    .B(shift_in[6]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _335_ (
    .A1(_084_),
    .A2(_159_),
    .B1(_165_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(_156_),
    .B(shift_in[7]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o21ai_0 _337_ (
    .A1(_086_),
    .A2(_159_),
    .B1(_166_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(state[2]),
    .B(clk_cnt[0]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o21ai_0 _339_ (
    .A1(clk_cnt[0]),
    .A2(_101_),
    .B1(_167_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(clk_cnt[0]),
    .B(clk_cnt[1]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(state[2]),
    .B(clk_cnt[1]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _342_ (
    .A1(_168_),
    .A2(_101_),
    .B1(_169_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkbuf_8 _343_ (
    .A(_073_),
    .X(_170_)
  );
  sky130_fd_sc_hd__inv_1 _344_ (
    .A(clk_cnt[2]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _345_ (
    .A(_170_),
    .B(_171_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__inv_1 _346_ (
    .A(clk_cnt[3]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2_1 _347_ (
    .A(_170_),
    .B(_172_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__inv_1 _348_ (
    .A(clk_cnt[4]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(_170_),
    .B(_173_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__inv_1 _350_ (
    .A(clk_cnt[5]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(_170_),
    .B(_174_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_1 _352_ (
    .A(clk_cnt[6]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(_170_),
    .B(_175_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_1 _354_ (
    .A(clk_cnt[7]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(_170_),
    .B(_176_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_1 _356_ (
    .A(clk_cnt[8]),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(_170_),
    .B(_177_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_1 _358_ (
    .A(clk_cnt[9]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(_170_),
    .B(_178_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_1 _360_ (
    .A(clk_cnt[10]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _361_ (
    .A(_170_),
    .B(_179_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__inv_1 _362_ (
    .A(clk_cnt[11]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _363_ (
    .A(_170_),
    .B(_180_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__inv_1 _364_ (
    .A(clk_cnt[12]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_1 _365_ (
    .A(_073_),
    .B(_181_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__inv_1 _366_ (
    .A(clk_cnt[13]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(_073_),
    .B(_182_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_1 _368_ (
    .A(clk_cnt[14]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nor2_1 _369_ (
    .A(_073_),
    .B(_183_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__inv_1 _370_ (
    .A(clk_cnt[15]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_073_),
    .B(_184_),
    .Y(_048_)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk),
    .D(_000_),
    .Q(shift_out[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(clk),
    .D(_001_),
    .Q(shift_out[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk),
    .D(_002_),
    .Q(shift_out[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(clk),
    .D(_003_),
    .Q(shift_out[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(clk),
    .D(_004_),
    .Q(shift_out[4]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(clk),
    .D(_005_),
    .Q(shift_out[5]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(clk),
    .D(_006_),
    .Q(shift_out[6]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _379_ (
    .CLK(clk),
    .D(_007_),
    .Q(shift_out[7]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(clk),
    .D(_008_),
    .Q(rx_data[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _381_ (
    .CLK(clk),
    .D(_009_),
    .Q(rx_data[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk),
    .D(_010_),
    .Q(rx_data[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _383_ (
    .CLK(clk),
    .D(_011_),
    .Q(rx_data[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_012_),
    .Q(rx_data[4]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(_013_),
    .Q(rx_data[5]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_014_),
    .Q(rx_data[6]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(_015_),
    .Q(rx_data[7]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(_016_),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(_017_),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk),
    .D(_018_),
    .Q(state[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _391_ (
    .CLK(clk),
    .D(_185_[0]),
    .Q(rx_valid),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk),
    .D(_019_),
    .Q(mosi),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfstp_2 _393_ (
    .CLK(clk),
    .D(_020_),
    .Q(cs_n),
    .SET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(_021_),
    .Q(bit_cnt[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _395_ (
    .CLK(clk),
    .D(_022_),
    .Q(bit_cnt[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clk),
    .D(_023_),
    .Q(bit_cnt[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _397_ (
    .CLK(clk),
    .D(_024_),
    .Q(sclk),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _398_ (
    .CLK(clk),
    .D(_025_),
    .Q(shift_in[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _399_ (
    .CLK(clk),
    .D(_026_),
    .Q(shift_in[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _400_ (
    .CLK(clk),
    .D(_027_),
    .Q(shift_in[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _401_ (
    .CLK(clk),
    .D(_028_),
    .Q(shift_in[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _402_ (
    .CLK(clk),
    .D(_029_),
    .Q(shift_in[4]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _403_ (
    .CLK(clk),
    .D(_030_),
    .Q(shift_in[5]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _404_ (
    .CLK(clk),
    .D(_031_),
    .Q(shift_in[6]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _405_ (
    .CLK(clk),
    .D(_032_),
    .Q(shift_in[7]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _406_ (
    .CLK(clk),
    .D(_033_),
    .Q(clk_cnt[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _407_ (
    .CLK(clk),
    .D(_034_),
    .Q(clk_cnt[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _408_ (
    .CLK(clk),
    .D(_035_),
    .Q(clk_cnt[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _409_ (
    .CLK(clk),
    .D(_036_),
    .Q(clk_cnt[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(clk),
    .D(_037_),
    .Q(clk_cnt[4]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(clk),
    .D(_038_),
    .Q(clk_cnt[5]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(clk),
    .D(_039_),
    .Q(clk_cnt[6]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _413_ (
    .CLK(clk),
    .D(_040_),
    .Q(clk_cnt[7]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(clk),
    .D(_041_),
    .Q(clk_cnt[8]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(clk),
    .D(_042_),
    .Q(clk_cnt[9]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _416_ (
    .CLK(clk),
    .D(_043_),
    .Q(clk_cnt[10]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(clk),
    .D(_044_),
    .Q(clk_cnt[11]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(clk),
    .D(_045_),
    .Q(clk_cnt[12]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(clk),
    .D(_046_),
    .Q(clk_cnt[13]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _420_ (
    .CLK(clk),
    .D(_047_),
    .Q(clk_cnt[14]),
    .RESET_B(rst_n)
  );
  (* src = "src/spi_master.v:39.5-132.8" *)
  sky130_fd_sc_hd__dfrtp_1 _421_ (
    .CLK(clk),
    .D(_048_),
    .Q(clk_cnt[15]),
    .RESET_B(rst_n)
  );
  assign tx_ready = cs_n;
endmodule
