"""Multi-Mode Multi-Corner (MMMC) timing analysis configuration and runner.

This module models MMMC the way a real signoff flow does:

* A **Corner** is a PVT + RC point with its own ``.lib`` files and derating.
* A **Mode** is a functional scenario (functional, scan, low-power) with its
  own SDC and case analysis.
* A **Scenario** pairs one mode with one corner and specifies which checks
  (setup / hold / both) to run.

The :class:`MmmcConfig` can emit real OpenROAD / Innovus Tcl. The
:class:`MmmcRunner` invokes OpenSTA for each scenario and aggregates the
results into :class:`StaReport` objects using :func:`parse_sta_report` from
``physical.sta_parser``.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from openforge.physical.sta_parser import StaReport, parse_sta_report

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class Corner(BaseModel):
    """A PVT + RC signoff corner."""

    name: str
    process: str = "tt"  # ss / tt / ff
    voltage: float = 1.80  # volts
    temperature: float = 25.0  # degrees C
    lib_files: list[Path] = Field(default_factory=list)
    rc_corner: str = "typical"  # minC / nominal / maxC
    qrc_file: Path | None = None
    derate: float = 1.0  # OCV derate factor

    @field_validator("process")
    @classmethod
    def _norm_process(cls, v: str) -> str:
        return v.lower()


class Mode(BaseModel):
    """A functional mode with its own SDC + clock activation."""

    name: str
    sdc_file: Path
    active_clocks: list[str] = Field(default_factory=list)
    case_analysis: dict[str, str] = Field(default_factory=dict)


CheckType = Literal["setup", "hold", "min_max"]


class Scenario(BaseModel):
    """One (mode x corner) pair with a check type."""

    name: str
    corner: Corner
    mode: Mode
    check_type: CheckType = "min_max"


class MmmcConfig(BaseModel):
    """Complete MMMC view definition."""

    corners: list[Corner] = Field(default_factory=list)
    modes: list[Mode] = Field(default_factory=list)
    scenarios: list[Scenario] = Field(default_factory=list)

    # ------------------------------------------------------------------
    # Tcl emitters
    # ------------------------------------------------------------------

    def to_openroad_tcl(self) -> str:
        """Emit Tcl for an OpenROAD MMMC view.

        OpenROAD uses ``define_corners``, ``read_liberty -corner``, and
        ``set_operating_conditions``.
        """
        lines: list[str] = [
            "# OpenROAD MMMC view definition",
            "# Generated by openforge.physical.mmmc",
            "",
        ]

        if self.corners:
            corner_names = " ".join(c.name for c in self.corners)
            lines.append(f"define_corners {corner_names}")
            lines.append("")

        for corner in self.corners:
            lines.append(f"# ---- corner: {corner.name} ----")
            for lib in corner.lib_files:
                lines.append(f"read_liberty -corner {corner.name} {_tcl_path(lib)}")
            lines.append(
                f"set_operating_conditions -corner {corner.name} "
                f"-voltage {corner.voltage:.3f} -temperature {corner.temperature:.2f}"
            )
            if corner.derate != 1.0:
                lines.append(
                    f"set_timing_derate -corner {corner.name} -late {corner.derate:.3f}"
                )
            lines.append("")

        for mode in self.modes:
            lines.append(f"# ---- mode: {mode.name} ----")
            lines.append(f"read_sdc {_tcl_path(mode.sdc_file)}")
            for clk in mode.active_clocks:
                lines.append(f"set_propagated_clock [get_clocks {clk}]")
            for pin, value in mode.case_analysis.items():
                lines.append(f"set_case_analysis {value} {pin}")
            lines.append("")

        for sc in self.scenarios:
            lines.append(
                f"# scenario {sc.name}: mode={sc.mode.name} corner={sc.corner.name} "
                f"check={sc.check_type}"
            )
            if sc.check_type in ("setup", "min_max"):
                lines.append(
                    f"report_checks -corner {sc.corner.name} -path_delay max -group_count 20"
                )
            if sc.check_type in ("hold", "min_max"):
                lines.append(
                    f"report_checks -corner {sc.corner.name} -path_delay min -group_count 20"
                )
            lines.append("")

        return "\n".join(lines)

    def to_innovus_tcl(self) -> str:
        """Emit Tcl for Cadence Innovus ``create_constraint_mode`` /
        ``create_rc_corner`` / ``create_delay_corner`` / ``create_analysis_view``.
        """
        lines: list[str] = [
            "# Innovus MMMC view definition",
            "# Generated by openforge.physical.mmmc",
            "",
        ]

        for mode in self.modes:
            lines.append(
                f"create_constraint_mode -name {mode.name} "
                f"-sdc_files [list {_tcl_path(mode.sdc_file)}]"
            )

        lines.append("")
        for corner in self.corners:
            libs = " ".join(_tcl_path(p) for p in corner.lib_files)
            lines.append(
                f"create_library_set -name {corner.name}_libs -timing [list {libs}]"
            )
            rc_opts = (
                f"-qx_tech_file {_tcl_path(corner.qrc_file)}"
                if corner.qrc_file
                else "-T 0.025"
            )
            lines.append(
                f"create_rc_corner -name {corner.name}_rc "
                f"-temperature {corner.temperature:.2f} {rc_opts}"
            )
            lines.append(
                f"create_delay_corner -name {corner.name}_dc "
                f"-library_set {corner.name}_libs -rc_corner {corner.name}_rc "
                f"-early_derate {corner.derate:.3f} -late_derate {corner.derate:.3f}"
            )

        lines.append("")
        for sc in self.scenarios:
            lines.append(
                f"create_analysis_view -name {sc.name} "
                f"-constraint_mode {sc.mode.name} -delay_corner {sc.corner.name}_dc"
            )

        if self.scenarios:
            setup_views = " ".join(
                sc.name for sc in self.scenarios if sc.check_type in ("setup", "min_max")
            )
            hold_views = " ".join(
                sc.name for sc in self.scenarios if sc.check_type in ("hold", "min_max")
            )
            lines.append("")
            lines.append(
                f"set_analysis_view -setup [list {setup_views}] -hold [list {hold_views}]"
            )

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # PDK defaults
    # ------------------------------------------------------------------

    @classmethod
    def sky130_default(cls) -> MmmcConfig:
        """Standard sky130_fd_sc_hd MMMC corners: tt/ss/ff."""
        lib_root = Path("$PDK_ROOT/sky130A/libs.ref/sky130_fd_sc_hd/lib")
        corners = [
            Corner(
                name="tt_025C_1v80",
                process="tt",
                voltage=1.80,
                temperature=25.0,
                lib_files=[lib_root / "sky130_fd_sc_hd__tt_025C_1v80.lib"],
                rc_corner="nominal",
                derate=1.0,
            ),
            Corner(
                name="ss_n40C_1v60",
                process="ss",
                voltage=1.60,
                temperature=-40.0,
                lib_files=[lib_root / "sky130_fd_sc_hd__ss_n40C_1v60.lib"],
                rc_corner="maxC",
                derate=1.05,
            ),
            Corner(
                name="ff_125C_1v95",
                process="ff",
                voltage=1.95,
                temperature=125.0,
                lib_files=[lib_root / "sky130_fd_sc_hd__ff_125C_1v95.lib"],
                rc_corner="minC",
                derate=0.95,
            ),
        ]
        mode = Mode(
            name="functional",
            sdc_file=Path("constraints.sdc"),
            active_clocks=["clk"],
        )
        scenarios = [
            Scenario(
                name=f"{mode.name}@{corners[0].name}",
                corner=corners[0],
                mode=mode,
                check_type="min_max",
            ),
            Scenario(
                name=f"{mode.name}@{corners[1].name}",
                corner=corners[1],
                mode=mode,
                check_type="setup",
            ),
            Scenario(
                name=f"{mode.name}@{corners[2].name}",
                corner=corners[2],
                mode=mode,
                check_type="hold",
            ),
        ]
        return cls(corners=corners, modes=[mode], scenarios=scenarios)

    @classmethod
    def asap7_default(cls) -> MmmcConfig:
        """Standard ASAP7 7.5T MMMC corners: TT/SS/FF."""
        lib_root = Path("$PDK_ROOT/asap7/asap7sc7p5t_27/LIB/NLDM")
        corners = [
            Corner(
                name="TT_0P70V_025C",
                process="tt",
                voltage=0.70,
                temperature=25.0,
                lib_files=[lib_root / "asap7sc7p5t_INVBUF_RVT_TT_nldm_211120.lib"],
                derate=1.0,
            ),
            Corner(
                name="SS_0P63V_100C",
                process="ss",
                voltage=0.63,
                temperature=100.0,
                lib_files=[lib_root / "asap7sc7p5t_INVBUF_RVT_SS_nldm_211120.lib"],
                derate=1.07,
            ),
            Corner(
                name="FF_0P77V_n40C",
                process="ff",
                voltage=0.77,
                temperature=-40.0,
                lib_files=[lib_root / "asap7sc7p5t_INVBUF_RVT_FF_nldm_211120.lib"],
                derate=0.93,
            ),
        ]
        mode = Mode(
            name="functional",
            sdc_file=Path("constraints.sdc"),
            active_clocks=["clk"],
        )
        scenarios = [
            Scenario(
                name=f"{mode.name}@{c.name}",
                corner=c,
                mode=mode,
                check_type="min_max",
            )
            for c in corners
        ]
        return cls(corners=corners, modes=[mode], scenarios=scenarios)


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


class MmmcRunner:
    """Execute every scenario in a :class:`MmmcConfig` through OpenSTA."""

    def __init__(self, config: MmmcConfig, design_root: Path):
        self.config = config
        self.design_root = Path(design_root)
        self.design_root.mkdir(parents=True, exist_ok=True)

    def run_all_scenarios(
        self,
        verilog: Path,
        def_path: Path | None = None,
        top: str = "top",
        opensta_binary: str = "sta",
    ) -> dict[str, StaReport]:
        """Run every scenario, return ``{scenario_name: StaReport}``."""
        results: dict[str, StaReport] = {}
        for sc in self.config.scenarios:
            logger.info("Running MMMC scenario %s", sc.name)
            script_path = self.design_root / f"{sc.name}.tcl"
            log_path = self.design_root / f"{sc.name}.log"
            script_path.write_text(
                self._scenario_script(sc, verilog=verilog, def_path=def_path, top=top)
            )
            try:
                log_text = self._run_opensta(opensta_binary, script_path, log_path)
            except FileNotFoundError:
                logger.warning("OpenSTA not found; empty report for %s", sc.name)
                log_text = ""
            report = parse_sta_report(log_text) if log_text else StaReport()
            results[sc.name] = report
        return results

    # ------------------------------------------------------------------

    def _scenario_script(
        self,
        scenario: Scenario,
        verilog: Path,
        def_path: Path | None,
        top: str,
    ) -> str:
        lines: list[str] = [f"# OpenSTA script for scenario {scenario.name}"]
        for lib in scenario.corner.lib_files:
            lines.append(f"read_liberty {_tcl_path(lib)}")
        lines.append(f"read_verilog {_tcl_path(verilog)}")
        lines.append(f"link_design {top}")
        if def_path is not None:
            lines.append(f"read_def {_tcl_path(def_path)}")
        lines.append(f"read_sdc {_tcl_path(scenario.mode.sdc_file)}")
        if scenario.corner.derate != 1.0:
            lines.append(f"set_timing_derate -late {scenario.corner.derate:.4f}")
        for pin, value in scenario.mode.case_analysis.items():
            lines.append(f"set_case_analysis {value} {pin}")
        if scenario.check_type in ("setup", "min_max"):
            lines.append("report_checks -path_delay max -group_count 20")
        if scenario.check_type in ("hold", "min_max"):
            lines.append("report_checks -path_delay min -group_count 20")
        lines.append("report_worst_slack -max")
        lines.append("report_worst_slack -min")
        lines.append("report_tns")
        lines.append("exit")
        return "\n".join(lines) + "\n"

    def _run_opensta(
        self,
        binary: str,
        script_path: Path,
        log_path: Path,
    ) -> str:
        if shutil.which(binary) is None:
            raise FileNotFoundError(binary)
        with log_path.open("w") as log_fh:
            subprocess.run(
                [binary, "-no_splash", "-exit", str(script_path)],
                stdout=log_fh,
                stderr=subprocess.STDOUT,
                cwd=str(self.design_root),
                check=False,
            )
        return log_path.read_text(errors="ignore")


# ---------------------------------------------------------------------------


def _tcl_path(p: Path | str) -> str:
    """Return a Tcl-friendly path (forward slashes, braced if spaces)."""
    s = str(p).replace("\\", "/")
    if " " in s:
        return "{" + s + "}"
    return s
