"""SPEF parasitic extraction for OpenForge.

A Mentor Calibre xRC replacement that produces SPEF (Standard Parasitic
Exchange Format) files from a routed DEF.
"""
from __future__ import annotations

import math
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class ParasiticResistor:
    node1: str
    node2: str
    resistance: float  # ohms


@dataclass
class ParasiticCapacitor:
    node: str
    capacitance: float  # farads


@dataclass
class ParasiticCoupling:
    node1: str
    node2: str
    capacitance: float  # farads


@dataclass
class NetParasitics:
    name: str
    total_resistance: float = 0.0
    total_capacitance: float = 0.0
    resistors: list[ParasiticResistor] = field(default_factory=list)
    capacitors: list[ParasiticCapacitor] = field(default_factory=list)
    couplings: list[ParasiticCoupling] = field(default_factory=list)
    delay_estimate_ps: float = 0.0

    def recompute_totals(self) -> None:
        self.total_resistance = sum(r.resistance for r in self.resistors)
        self.total_capacitance = (
            sum(c.capacitance for c in self.capacitors)
            + sum(c.capacitance for c in self.couplings)
        )
        # Elmore-style first-order RC delay (s -> ps).
        self.delay_estimate_ps = (
            self.total_resistance * self.total_capacitance * 1e12
        )


@dataclass
class SpefFile:
    design_name: str
    units_t: str = "1 PS"
    units_c: str = "1 FF"
    units_r: str = "1 OHM"
    nets: dict[str, NetParasitics] = field(default_factory=dict)
    ports: list[str] = field(default_factory=list)
    instances: dict[str, str] = field(default_factory=dict)

    def add_net(self, net: NetParasitics) -> None:
        self.nets[net.name] = net

    def total_capacitance(self) -> float:
        return sum(n.total_capacitance for n in self.nets.values())

    def total_resistance(self) -> float:
        return sum(n.total_resistance for n in self.nets.values())

    # ------------------------------------------------------------------
    # SPEF generation
    # ------------------------------------------------------------------

    def to_spef(self) -> str:
        """Generate SPEF format text."""
        lines: list[str] = []
        lines.append('*SPEF "IEEE 1481-1998"')
        lines.append(f'*DESIGN "{self.design_name}"')
        lines.append('*DATE "Generated by OpenForge"')
        lines.append('*VENDOR "OpenForge"')
        lines.append('*PROGRAM "openforge.parasitic_extraction"')
        lines.append('*VERSION "1.0"')
        lines.append('*DESIGN_FLOW "PIN_CAP NONE" "NAME_SCOPE LOCAL"')
        lines.append('*DIVIDER /')
        lines.append('*DELIMITER :')
        lines.append('*BUS_DELIMITER [ ]')
        lines.append(f'*T_UNIT {self.units_t}')
        lines.append(f'*C_UNIT {self.units_c}')
        lines.append(f'*R_UNIT {self.units_r}')
        lines.append('*L_UNIT 1 HENRY')
        lines.append("")

        # Name map
        if self.ports:
            lines.append("*PORTS")
            for i, p in enumerate(self.ports, 1):
                lines.append(f"{p} I")
            lines.append("")

        # Each net block
        for net in self.nets.values():
            lines.append(f"*D_NET {net.name} {net.total_capacitance * 1e15:.4f}")
            if net.capacitors or net.couplings:
                lines.append("*CAP")
                idx = 1
                for c in net.capacitors:
                    lines.append(
                        f"{idx} {c.node} {c.capacitance * 1e15:.4f}"
                    )
                    idx += 1
                for c in net.couplings:
                    lines.append(
                        f"{idx} {c.node1} {c.node2} "
                        f"{c.capacitance * 1e15:.4f}"
                    )
                    idx += 1
            if net.resistors:
                lines.append("*RES")
                for i, r in enumerate(net.resistors, 1):
                    lines.append(f"{i} {r.node1} {r.node2} {r.resistance:.4f}")
            lines.append("*END")
            lines.append("")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Extractor
# ---------------------------------------------------------------------------


@dataclass
class _WireSeg:
    layer: str
    x1: float
    y1: float
    x2: float
    y2: float
    width: float = 0.14

    @property
    def length(self) -> float:
        return math.hypot(self.x2 - self.x1, self.y2 - self.y1)

    @property
    def area(self) -> float:
        return self.length * self.width

    def is_horizontal(self) -> bool:
        return abs(self.y2 - self.y1) < 1e-6


class ParasiticExtractor:
    """Extract parasitics from a routed DEF file.

    Algorithm (simplified):
    1. Parse DEF for routed nets and their wire segments.
    2. For each wire segment: R = sheet_resistance * length / width.
    3. Compute area capacitance per layer.
    4. Compute coupling capacitance for adjacent parallel runs.
    5. Build a per-net RC tree.
    """

    def __init__(self, tech_data: Optional[dict] = None):
        self.tech: dict = tech_data or self._default_sky130_tech()

    @staticmethod
    def _default_sky130_tech() -> dict:
        return {
            "li1":  {"sheet_r": 12.800, "cap_per_um2": 0.0040, "fringe_per_um": 0.030, "default_w": 0.17},
            "met1": {"sheet_r": 0.125,  "cap_per_um2": 0.0035, "fringe_per_um": 0.027, "default_w": 0.14},
            "met2": {"sheet_r": 0.125,  "cap_per_um2": 0.0030, "fringe_per_um": 0.024, "default_w": 0.14},
            "met3": {"sheet_r": 0.047,  "cap_per_um2": 0.0025, "fringe_per_um": 0.021, "default_w": 0.30},
            "met4": {"sheet_r": 0.047,  "cap_per_um2": 0.0020, "fringe_per_um": 0.018, "default_w": 0.30},
            "met5": {"sheet_r": 0.029,  "cap_per_um2": 0.0015, "fringe_per_um": 0.015, "default_w": 1.60},
        }

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def extract(
        self,
        def_path: Path,
        on_progress: Optional[Callable[[float, str], None]] = None,
    ) -> SpefFile:
        """Extract parasitics from a routed DEF file."""
        def_path = Path(def_path)
        start = time.time()
        if on_progress:
            on_progress(0.0, "Parsing DEF")

        design_name = self._parse_design_name(def_path)
        spef = SpefFile(design_name=design_name)

        nets = self.parse_def_routing(def_path)
        if on_progress:
            on_progress(0.4, f"Computing RC for {len(nets)} nets")

        total = max(len(nets), 1)
        for i, (net_name, segments) in enumerate(nets.items()):
            np = self.compute_net_rc(segments, self.tech)
            np.name = net_name
            np.recompute_totals()
            spef.add_net(np)
            if on_progress and i % 50 == 0:
                on_progress(0.4 + 0.55 * (i / total),
                            f"Net {i}/{total}: {net_name}")

        if on_progress:
            on_progress(0.97, "Adding coupling caps")
        self._compute_couplings(nets, spef)

        if on_progress:
            on_progress(1.0, f"Done in {time.time() - start:.2f}s")
        return spef

    def write_spef(self, spef: SpefFile, output: Path) -> Path:
        output = Path(output)
        output.write_text(spef.to_spef(), encoding="utf-8")
        return output

    # ------------------------------------------------------------------
    # DEF parsing
    # ------------------------------------------------------------------

    _RE_DESIGN = re.compile(r"^\s*DESIGN\s+(\S+)\s*;")
    _RE_NET = re.compile(r"^\s*-\s*([A-Za-z0-9_/\[\].$]+)")
    _RE_ROUTED = re.compile(
        r"(?:NEW|ROUTED)\s+([A-Za-z0-9_]+)\s+\(\s*([-\d]+)\s+([-\d]+)[^)]*\)"
        r"\s*(?:\(\s*([-\d*]+)\s+([-\d*]+)[^)]*\))?",
    )

    def _parse_design_name(self, def_path: Path) -> str:
        try:
            with def_path.open("r", encoding="utf-8", errors="ignore") as fh:
                for line in fh:
                    m = self._RE_DESIGN.match(line)
                    if m:
                        return m.group(1)
        except OSError:
            pass
        return def_path.stem

    def parse_def_routing(self, def_path: Path) -> dict[str, list[_WireSeg]]:
        """Parse the NETS section of a DEF and return per-net wire segments."""
        nets: dict[str, list[_WireSeg]] = {}
        if not def_path.exists():
            return nets

        in_nets = False
        current_net: Optional[str] = None
        prev_pt: Optional[tuple[float, float]] = None
        prev_layer: Optional[str] = None
        units = 1000.0  # DEF dbu per micron, default

        try:
            with def_path.open("r", encoding="utf-8", errors="ignore") as fh:
                for raw_line in fh:
                    line = raw_line.rstrip("\n")
                    if "UNITS DISTANCE MICRONS" in line:
                        m = re.search(r"MICRONS\s+(\d+)", line)
                        if m:
                            units = float(m.group(1))
                        continue
                    if line.strip().startswith("NETS "):
                        in_nets = True
                        continue
                    if line.strip().startswith("END NETS"):
                        in_nets = False
                        current_net = None
                        continue
                    if not in_nets:
                        continue

                    nm = self._RE_NET.match(line)
                    if nm:
                        current_net = nm.group(1)
                        nets.setdefault(current_net, [])
                        prev_pt = None
                        prev_layer = None
                        continue

                    if current_net is None:
                        continue

                    for rm in self._RE_ROUTED.finditer(line):
                        layer = rm.group(1)
                        x1 = float(rm.group(2)) / units
                        y1 = float(rm.group(3)) / units
                        x2_raw = rm.group(4)
                        y2_raw = rm.group(5)
                        if x2_raw is None:
                            prev_pt = (x1, y1)
                            prev_layer = layer
                            continue
                        x2 = x1 if x2_raw == "*" else float(x2_raw) / units
                        y2 = y1 if y2_raw == "*" else float(y2_raw) / units
                        width = self.tech.get(layer, {}).get("default_w", 0.14)
                        nets[current_net].append(
                            _WireSeg(layer, x1, y1, x2, y2, width)
                        )
                        prev_pt = (x2, y2)
                        prev_layer = layer

                    if line.strip().endswith(";"):
                        current_net = None
                        prev_pt = None
                        prev_layer = None
        except OSError:
            pass

        return nets

    # ------------------------------------------------------------------
    # RC computation
    # ------------------------------------------------------------------

    def compute_net_rc(
        self, segments: list[_WireSeg], layer_data: dict,
    ) -> NetParasitics:
        net = NetParasitics(name="")
        for i, seg in enumerate(segments):
            ld = layer_data.get(seg.layer, {})
            sheet_r = float(ld.get("sheet_r", 0.1))
            cap_pa = float(ld.get("cap_per_um2", 0.003))  # fF/um^2 -> we'll
            fringe = float(ld.get("fringe_per_um", 0.02))
            length = max(seg.length, 1e-6)
            width = max(seg.width, 1e-6)

            r = sheet_r * (length / width)
            # cap in farads: area*cap (fF) + perimeter*fringe (fF), then *1e-15
            area_cap_ff = seg.area * cap_pa
            fringe_cap_ff = 2.0 * length * fringe
            cap_f = (area_cap_ff + fringe_cap_ff) * 1e-15

            n1 = f"{seg.layer}_{i}_a"
            n2 = f"{seg.layer}_{i}_b"
            net.resistors.append(ParasiticResistor(n1, n2, r))
            net.capacitors.append(ParasiticCapacitor(n1, cap_f / 2.0))
            net.capacitors.append(ParasiticCapacitor(n2, cap_f / 2.0))
        net.recompute_totals()
        return net

    def _compute_couplings(
        self,
        nets: dict[str, list[_WireSeg]],
        spef: SpefFile,
    ) -> None:
        """Add coupling caps for parallel runs on the same layer."""
        names = list(nets.keys())
        for i, na in enumerate(names):
            sa = nets[na]
            for j in range(i + 1, len(names)):
                nb = names[j]
                sb = nets[nb]
                added = 0.0
                for s1 in sa:
                    if not s1.is_horizontal() and s1.x1 == s1.x2 \
                            and s1.y1 == s1.y2:
                        continue
                    for s2 in sb:
                        if s1.layer != s2.layer:
                            continue
                        overlap = self._parallel_overlap(s1, s2)
                        if overlap <= 0:
                            continue
                        # crude coupling: 0.05 fF per um of parallel run
                        added += overlap * 0.05e-15
                if added > 0 and na in spef.nets and nb in spef.nets:
                    spef.nets[na].couplings.append(
                        ParasiticCoupling(f"{na}:1", f"{nb}:1", added)
                    )
                    spef.nets[na].recompute_totals()

    @staticmethod
    def _parallel_overlap(a: _WireSeg, b: _WireSeg) -> float:
        # Both must be axis-aligned and same orientation.
        if a.is_horizontal() and b.is_horizontal():
            if abs(a.y1 - b.y1) > 0.5:
                return 0.0
            x_overlap = max(
                0.0, min(max(a.x1, a.x2), max(b.x1, b.x2))
                - max(min(a.x1, a.x2), min(b.x1, b.x2))
            )
            return x_overlap
        if not a.is_horizontal() and not b.is_horizontal():
            if abs(a.x1 - b.x1) > 0.5:
                return 0.0
            y_overlap = max(
                0.0, min(max(a.y1, a.y2), max(b.y1, b.y2))
                - max(min(a.y1, a.y2), min(b.y1, b.y2))
            )
            return y_overlap
        return 0.0


__all__ = [
    "ParasiticResistor",
    "ParasiticCapacitor",
    "ParasiticCoupling",
    "NetParasitics",
    "SpefFile",
    "ParasiticExtractor",
]
